.ds SI @(#) 1.2 94/12/19
.Hi Index
.2C
.iM "<Dt/Action.h>" "" "\f3690\fP"
.iM "<Dt/ComboBox.h>" "" "\f376\fP"
.iM "<Dt/Dnd.h>" "" "\f3607\fP"
.iM "<Dt/Dt.h>" "" "\f384\fP"
.iM "<Dt/Dts.h>" "" "\f3645\fP"
.iM "<Dt/MenuButton.h>" "" "\f377\fP"
.iM "<Dt/SpinBox.h>" "" "\f378\fP"
.iM "<Tt/tttk.h>" "" "\f3474\fP"
.iM "<Tt/tt_c.h>" "" "\f3458\fP"
.iM "abandoned action" "" "\f319\fP"
.iM "action" "" "\f319\fP"
.iM "action label" "" "\f319\fP"
.iM "actions and data types database" "" "\f319\fP"
.iM "actions table" "" "\f319\fP"
.iM "attachment" "" "\f319\fP"
.iM "auto wraparound" "" "\f319\fP"
.iM "auto-repeat key" "" "\f320\fP"
.iM "backdrop" "" "\f320\fP"
.iM "base height" "" "\f320\fP"
.iM "base width" "" "\f320\fP"
.iM "bell" "" "\f320\fP"
.iM "blanking mode" "" "\f320\fP"
.iM "bounding box" "" "\f320\fP"
.iM "buffer argument" "" "\f320\fP"
.iM "can" "" "\f35\fP"
.iM "category" "" "\f320\fP"
.iM "character protection attribute" "" "\f321\fP"
.iM "character-spaced font" "" "\f321\fP"
.iM "client data" "" "\f321\fP"
.iM "colour set" "" "\f321\fP"
.iM "conformance" "" "4"
.iM "contexts" "" "\f321\fP"
.iM "current session" "" "\f322\fP"
.iM "current workspace" "" "\f322\fP"
.iM "data attributes" "" "\f322\fP"
.iM "data attributes table" "" "\f322\fP"
.iM "data criteria table" "" "\f322\fP"
.iM "data type" "" "\f322\fP"
.iM "data types database" "" "\f322\fP"
.iM "data typing" "" "\f322\fP"
.iM "Deposit" "" "\f3568\fP"
.iM "deserialise" "" "\f323\fP"
.iM "Display" "" "\f3570\fP"
.iM "display area" "" "\f322\fP"
.iM "drag" "" "\f323\fP"
.iM "drag and drop" "" "\f323\fP"
.iM "drop" "" "\f323\fP"
.iM "drop zone" "" "\f323\fP"
.iM "dtaction" "" "\f3693\fP"
.iM "DtActionCallbackProc(\|)" "" "\f3670\fP"
.iM "DtActionDescription(\|)" "" "\f3675\fP"
.iM "DtActionExists(\|)" "" "\f3676\fP"
.iM "DtActionIcon(\|)" "" "\f3677\fP"
.iM "DtActionInvoke(\|)" "" "\f3678\fP"
.iM "DtActionLabel(\|)" "" "\f3686\fP"
.iM "DtComboBox(\|)" "" "\f346\fP"
.iM "DtComboBoxAddItem(\|)" "" "\f365\fP"
.iM "DtComboBoxDeletePos(\|)" "" "\f366\fP"
.iM "DtComboBoxSelectItem(\|)" "" "\f367\fP"
.iM "DtComboBoxSetItem(\|)" "" "\f368\fP"
.iM "DtCreateComboBox(\|)" "" "\f369\fP"
.iM "DtCreateMenuButton(\|)" "" "\f370\fP"
.iM "DtCreateSpinBox(\|)" "" "\f371\fP"
.iM "DtDbLoad(\|)" "" "\f3687\fP"
.iM "DtDbReloadNotify(\|)" "" "\f3688\fP"
.iM "DtDndCreateSourceIcon(\|)" "" "\f3588\fP"
.iM "DtDndDragStart(\|)" "" "\f3590\fP"
.iM "DtDndDropRegister(\|)" "" "\f3598\fP"
.iM "DtDtsBufferToAttributeList(\|)" "" "\f3618\fP"
.iM "DtDtsBufferToAttributeValue(\|)" "" "\f3620\fP"
.iM "DtDtsBufferToDataType(\|)" "" "\f3622\fP"
.iM "DtDtsDataToDataType(\|)" "" "\f3624\fP"
.iM "DtDtsDataTypeIsAction(\|)" "" "\f3626\fP"
.iM "DtDtsDataTypeNames(\|)" "" "\f3627\fP"
.iM "DtDtsDataTypeToAttributeList(\|)" "" "\f3628\fP"
.iM "DtDtsDataTypeToAttributeValue(\|)" "" "\f3629\fP"
.iM "DtDtsFileToAttributeList(\|)" "" "\f3631\fP"
.iM "DtDtsFileToAttributeValue(\|)" "" "\f3632\fP"
.iM "DtDtsFileToDataType(\|)" "" "\f3634\fP"
.iM "DtDtsFindAttribute(\|)" "" "\f3635\fP"
.iM "DtDtsFreeAttributeList(\|)" "" "\f3636\fP"
.iM "DtDtsFreeAttributeValue(\|)" "" "\f3637\fP"
.iM "DtDtsFreeDataType(\|)" "" "\f3638\fP"
.iM "DtDtsFreeDataTypeNames(\|)" "" "\f3639\fP"
.iM "DtDtsIsTrue(\|)" "" "\f3640\fP"
.iM "DtDtsLoadDataTypes(\|)" "" "\f3641\fP"
.iM "DtDtsRelease(\|)" "" "\f3642\fP"
.iM "DtDtsSetDataType(\|)" "" "\f3643\fP"
.iM "DtInitialize(\|)" "" "\f382\fP"
.iM "DtMenuButton(\|)" "" "\f351\fP"
.iM "DtSpinBox(\|)" "" "\f356\fP"
.iM "DtSpinBoxAddItem(\|)" "" "\f372\fP"
.iM "DtSpinBoxDeletePos(\|)" "" "\f373\fP"
.iM "DtSpinBoxSetItem(\|)" "" "\f374\fP"
.iM "dynamic message patterns" "" "\f323\fP"
.iM "edict" "" "\f323\fP"
.iM "Edit" "" "\f3572\fP"
.iM "escape character" "" "\f323\fP"
.iM "execution host" "" "\f324\fP"
.iM "execution string" "" "\f324\fP"
.iM "fail a request" "" "\f324\fP"
.iM "folder" "" "\f324\fP"
.iM "format of entries" "" "\f37\fP"
.iM "front panel" "" "\f324\fP"
.iM "general help dialog" "" "\f324\fP"
.iM "Get_Environment" "" "\f3525\fP"
.iM "Get_Geometry" "" "\f3526\fP"
.iM "Get_Iconified" "" "\f3527\fP"
.iM "Get_Locale" "" "\f3528\fP"
.iM "Get_Mapped" "" "\f3530\fP"
.iM "Get_Modified" "" "\f3531\fP"
.iM "Get_Situation" "" "\f3533\fP"
.iM "Get_Status" "" "\f3534\fP"
.iM "Get_Sysinfo" "" "\f3536\fP"
.iM "Get_XInfo" "" "\f3538\fP"
.iM "handle a request" "" "\f324\fP"
.iM "handler" "" "\f324\fP"
.iM "hard reset" "" "\f324\fP"
.iM "height increment" "" "\f324\fP"
.iM "help topic" "" "\f325\fP"
.iM "help type" "" "\f325\fP"
.iM "help volume" "" "\f325\fP"
.iM "HelpTag" "" "\f325\fP"
.iM "home session" "" "\f325\fP"
.iM "icon name" "" "\f325\fP"
.iM "implementation-dependent" "" "\f35\fP"
.iM "initial session" "" "\f325\fP"
.iM "jump scrolling" "" "\f325\fP"
.iM "location ID" "" "\f325\fP"
.iM "login shell" "" "\f326\fP"
.iM "Lower" "" "\f3540\fP"
.iM "Mail" "" "\f3575\fP"
.iM "mail header" "" "\f326\fP"
.iM "manual pages" "format" "7"
.iM "margin bell" "" "\f326\fP"
.iM "mark" "" "\f326\fP"
.iM "may" "" "\f35\fP"
.iM "message" "" "\f326\fP"
.iM "message callback" "" "\f326\fP"
.iM "message pattern" "" "\f326\fP"
.iM "message protocol" "" "\f326\fP"
.iM "Modified" "" "\f3541\fP"
.iM "module" "" "\f326\fP"
.iM "monospaced font" "" "\f327\fP"
.iM "must" "" "\f35\fP"
.iM "netfilename" "" "\f327\fP"
.iM "notice" "" "\f327\fP"
.iM "object" "" "\f327\fP"
.iM "object content" "" "\f327\fP"
.iM "object specification (spec)" "" "\f327\fP"
.iM "object type (otype)" "" "\f327\fP"
.iM "object type identifier (otid)" "" "\f327\fP"
.iM "object-oriented messages" "" "\f327\fP"
.iM "objid" "" "\f327\fP"
.iM "observe a message" "" "\f328\fP"
.iM "observe promise" "" "\f328\fP"
.iM "obsolescent" "" "\f35\fP"
.iM "opaque" "" "\f328\fP"
.iM "opname (op)" "" "\f328\fP"
.iM "opnum" "" "\f328\fP"
.iM "option argument keyword" "" "\f328\fP"
.iM "option string" "" "\f328\fP"
.iM "overstriking" "" "\f328\fP"
.iM "palette object" "" "\f328\fP"
.iM "paragraph" "" "\f329\fP"
.iM "pattern callback" "" "\f329\fP"
.iM "Pause" "" "\f3542\fP"
.iM "pixel offset" "" "\f329\fP"
.iM "Print" "" "\f3577\fP"
.iM "procedural message" "" "\f329\fP"
.iM "procid" "" "\f329\fP"
.iM "project" "" "\f329\fP"
.iM "proportional font" "" "\f329\fP"
.iM "pseudo-terminal" "" "\f329\fP"
.iM "ptid" "" "\f329\fP"
.iM "ptype" "" "\f329\fP"
.iM "quick help dialog" "" "\f330\fP"
.iM "Quit" "" "\f3544\fP"
.iM "Raise" "" "\f3546\fP"
.iM "registration context" "" "\f330\fP"
.iM "reject a request" "" "\f330\fP"
.iM "reparenting window manager" "" "\f330\fP"
.iM "request" "" "\f330\fP"
.iM "Resume" "" "\f3547\fP"
.iM "reverse wraparound" "" "\f330\fP"
.iM "Revert" "" "\f3548\fP"
.iM "Reverted" "" "\f3549\fP"
.iM "rpc.ttdbserverd" "" "\f330\fP"
.iM "Save" "" "\f3550\fP"
.iM "Saved" "" "\f3551\fP"
.iM "scope" "" "\f330\fP"
.iM "selection extension" "" "\f331\fP"
.iM "serialise" "" "\f331\fP"
.iM "sessid" "" "\f331\fP"
.iM "session" "" "\f331\fP"
.iM "Set_Environment" "" "\f3552\fP"
.iM "Set_Geometry" "" "\f3553\fP"
.iM "Set_Iconified" "" "\f3555\fP"
.iM "Set_Locale" "" "\f3557\fP"
.iM "Set_Mapped" "" "\f3559\fP"
.iM "Set_Situation" "" "\f3560\fP"
.iM "should" "" "\f35\fP"
.iM "Signal" "" "\f3561\fP"
.iM "signal handler" "" "\f331\fP"
.iM "signature" "" "\f331\fP"
.iM "slave device" "" "\f331\fP"
.iM "slotname" "" "\f331\fP"
.iM "soft reset" "" "\f331\fP"
.iM "source" "" "\f332\fP"
.iM "source indicator" "" "\f332\fP"
.iM "spec" "" "\f332\fP"
.iM "Started" "" "\f3562\fP"
.iM "starting shell" "" "\f332\fP"
.iM "state indicator" "" "\f332\fP"
.iM "static message pattern" "" "\f332\fP"
.iM "Status" "" "\f3563\fP"
.iM "Stopped" "" "\f3565\fP"
.iM "subpanel" "" "\f332\fP"
.iM "terminal emulator" "" "\f332\fP"
.iM "text rendering" "" "\f332\fP"
.iM "tool" "" "\f332\fP"
.iM "ToolTalk API" "" "\f332\fP"
.iM "ToolTalk service" "" "\f332\fP"
.iM "ToolTalk types database" "" "\f333\fP"
.iM "topic tree" "" "\f333\fP"
.iM "Translate" "" "\f3580\fP"
.iM "ttcp" "" "\f3485\fP"
.iM "ttdt_close(\|)" "" "\f3402\fP"
.iM "ttdt_file_event(\|)" "" "\f3403\fP"
.iM "ttdt_file_join(\|)" "" "\f3405\fP"
.iM "ttdt_file_notice(\|)" "" "\f3409\fP"
.iM "ttdt_file_quit(\|)" "" "\f3411\fP"
.iM "ttdt_file_request(\|)" "" "\f3413\fP"
.iM "ttdt_Get_Modified(\|)" "" "\f3396\fP"
.iM "ttdt_message_accept(\|)" "" "\f3415\fP"
.iM "ttdt_open(\|)" "" "\f3418\fP"
.iM "ttdt_Revert(\|)" "" "\f3398\fP"
.iM "ttdt_Save(\|)" "" "\f3400\fP"
.iM "ttdt_sender_imprint_on(\|)" "" "\f3419\fP"
.iM "ttdt_session_join(\|)" "" "\f3422\fP"
.iM "ttdt_session_quit(\|)" "" "\f3427\fP"
.iM "ttdt_subcontract_manage(\|)" "" "\f3428\fP"
.iM "ttmedia_Deposit(\|)" "" "\f3430\fP"
.iM "ttmedia_load(\|)" "" "\f3432\fP"
.iM "ttmedia_load_reply(\|)" "" "\f3436\fP"
.iM "ttmedia_ptype_declare(\|)" "" "\f3438\fP"
.iM "ttmv" "" "\f3489\fP"
.iM "ttrm" "" "\f3492\fP"
.iM "ttrmdir" "" "\f3495\fP"
.iM "ttsession" "" "\f3498\fP"
.iM "tttar" "" "\f3505\fP"
.iM "tttk_block_while(\|)" "" "\f3446\fP"
.iM "tttk_message_abandon(\|)" "" "\f3448\fP"
.iM "tttk_message_create(\|)" "" "\f3450\fP"
.iM "tttk_message_destroy(\|)" "" "\f3452\fP"
.iM "tttk_message_fail(\|)" "" "\f3453\fP"
.iM "tttk_message_reject(\|)" "" "\f3454\fP"
.iM "tttk_op_string(\|)" "" "\f3455\fP"
.iM "tttk_string_op(\|)" "" "\f3456\fP"
.iM "tttk_Xt_input_handler(\|)" "" "\f3444\fP"
.iM "tt_bcontext_join(\|)" "" "\f390\fP"
.iM "tt_bcontext_quit(\|)" "" "\f391\fP"
.iM "tt_close(\|)" "" "\f393\fP"
.iM "tt_context_join(\|)" "" "\f394\fP"
.iM "tt_context_quit(\|)" "" "\f395\fP"
.iM "tt_default_file(\|)" "" "\f397\fP"
.iM "tt_default_file_set(\|)" "" "\f398\fP"
.iM "tt_default_procid(\|)" "" "\f399\fP"
.iM "tt_default_procid_set(\|)" "" "\f3100\fP"
.iM "tt_default_ptype(\|)" "" "\f3101\fP"
.iM "tt_default_ptype_set(\|)" "" "\f3102\fP"
.iM "tt_default_session(\|)" "" "\f3103\fP"
.iM "tt_default_session_set(\|)" "" "\f3104\fP"
.iM "tt_error_int(\|)" "" "\f3106\fP"
.iM "tt_error_pointer(\|)" "" "\f3107\fP"
.iM "tt_fd(\|)" "" "\f3108\fP"
.iM "tt_file_copy(\|)" "" "\f3110\fP"
.iM "tt_file_destroy(\|)" "" "\f3112\fP"
.iM "tt_file_join(\|)" "" "\f3114\fP"
.iM "tt_file_move(\|)" "" "\f3116\fP"
.iM "tt_file_netfile(\|)" "" "\f3118\fP"
.iM "tt_file_objects_query(\|)" "" "\f3120\fP"
.iM "tt_file_quit(\|)" "" "\f3122\fP"
.iM "tt_free(\|)" "" "\f3123\fP"
.iM "tt_host_file_netfile(\|)" "" "\f3124\fP"
.iM "tt_host_netfile_file(\|)" "" "\f3126\fP"
.iM "tt_icontext_join(\|)" "" "\f3128\fP"
.iM "tt_icontext_quit(\|)" "" "\f3129\fP"
.iM "tt_initial_session(\|)" "" "\f3131\fP"
.iM "tt_int_error(\|)" "" "\f3132\fP"
.iM "tt_is_err(\|)" "" "\f3133\fP"
.iM "tt_malloc(\|)" "" "\f3134\fP"
.iM "tt_mark(\|)" "" "\f3135\fP"
.iM "tt_message_accept(\|)" "" "\f3136\fP"
.iM "tt_message_address(\|)" "" "\f3137\fP"
.iM "tt_message_address_set(\|)" "" "\f3139\fP"
.iM "tt_message_args_count(\|)" "" "\f3161\fP"
.iM "tt_message_arg_add(\|)" "" "\f3141\fP"
.iM "tt_message_arg_bval(\|)" "" "\f3143\fP"
.iM "tt_message_arg_bval_set(\|)" "" "\f3145\fP"
.iM "tt_message_arg_ival(\|)" "" "\f3147\fP"
.iM "tt_message_arg_ival_set(\|)" "" "\f3148\fP"
.iM "tt_message_arg_mode(\|)" "" "\f3150\fP"
.iM "tt_message_arg_type(\|)" "" "\f3152\fP"
.iM "tt_message_arg_val(\|)" "" "\f3154\fP"
.iM "tt_message_arg_val_set(\|)" "" "\f3156\fP"
.iM "tt_message_arg_xval(\|)" "" "\f3157\fP"
.iM "tt_message_arg_xval_set(\|)" "" "\f3159\fP"
.iM "tt_message_barg_add(\|)" "" "\f3162\fP"
.iM "tt_message_bcontext_set(\|)" "" "\f3164\fP"
.iM "tt_message_callback_add(\|)" "" "\f3166\fP"
.iM "tt_message_class(\|)" "" "\f3168\fP"
.iM "tt_message_class_set(\|)" "" "\f3170\fP"
.iM "tt_message_contexts_count(\|)" "" "\f3183\fP"
.iM "tt_message_context_bval(\|)" "" "\f3172\fP"
.iM "tt_message_context_ival(\|)" "" "\f3174\fP"
.iM "tt_message_context_set(\|)" "" "\f3176\fP"
.iM "tt_message_context_slotname(\|)" "" "\f3177\fP"
.iM "tt_message_context_val(\|)" "" "\f3179\fP"
.iM "tt_message_context_xval(\|)" "" "\f3181\fP"
.iM "tt_message_create(\|)" "" "\f3184\fP"
.iM "tt_message_create_super(\|)" "" "\f3185\fP"
.iM "tt_message_destroy(\|)" "" "\f3187\fP"
.iM "tt_message_disposition(\|)" "" "\f3188\fP"
.iM "tt_message_disposition_set(\|)" "" "\f3190\fP"
.iM "tt_message_fail(\|)" "" "\f3192\fP"
.iM "tt_message_file(\|)" "" "\f3194\fP"
.iM "tt_message_file_set(\|)" "" "\f3195\fP"
.iM "tt_message_gid(\|)" "" "\f3196\fP"
.iM "tt_message_handler(\|)" "" "\f3197\fP"
.iM "tt_message_handler_ptype(\|)" "" "\f3198\fP"
.iM "tt_message_handler_ptype_set(\|)" "" "\f3199\fP"
.iM "tt_message_handler_set(\|)" "" "\f3200\fP"
.iM "tt_message_iarg_add(\|)" "" "\f3201\fP"
.iM "tt_message_icontext_set(\|)" "" "\f3203\fP"
.iM "tt_message_id(\|)" "" "\f3204\fP"
.iM "tt_message_object(\|)" "" "\f3205\fP"
.iM "tt_message_object_set(\|)" "" "\f3206\fP"
.iM "tt_message_op(\|)" "" "\f3207\fP"
.iM "tt_message_opnum(\|)" "" "\f3209\fP"
.iM "tt_message_op_set(\|)" "" "\f3208\fP"
.iM "tt_message_otype(\|)" "" "\f3210\fP"
.iM "tt_message_otype_set(\|)" "" "\f3211\fP"
.iM "tt_message_pattern(\|)" "" "\f3212\fP"
.iM "tt_message_print(\|)" "" "\f3213\fP"
.iM "tt_message_receive(\|)" "" "\f3214\fP"
.iM "tt_message_reject(\|)" "" "\f3216\fP"
.iM "tt_message_reply(\|)" "" "\f3217\fP"
.iM "tt_message_scope(\|)" "" "\f3218\fP"
.iM "tt_message_scope_set(\|)" "" "\f3220\fP"
.iM "tt_message_send(\|)" "" "\f3222\fP"
.iM "tt_message_sender(\|)" "" "\f3226\fP"
.iM "tt_message_sender_ptype(\|)" "" "\f3227\fP"
.iM "tt_message_sender_ptype_set(\|)" "" "\f3228\fP"
.iM "tt_message_send_on_exit(\|)" "" "\f3224\fP"
.iM "tt_message_session(\|)" "" "\f3229\fP"
.iM "tt_message_session_set(\|)" "" "\f3230\fP"
.iM "tt_message_state(\|)" "" "\f3231\fP"
.iM "tt_message_status(\|)" "" "\f3233\fP"
.iM "tt_message_status_set(\|)" "" "\f3234\fP"
.iM "tt_message_status_string(\|)" "" "\f3235\fP"
.iM "tt_message_status_string_set(\|)" "" "\f3236\fP"
.iM "tt_message_uid(\|)" "" "\f3237\fP"
.iM "tt_message_user(\|)" "" "\f3238\fP"
.iM "tt_message_user_set(\|)" "" "\f3240\fP"
.iM "tt_message_xarg_add(\|)" "" "\f3242\fP"
.iM "tt_message_xcontext_join(\|)" "" "\f3244\fP"
.iM "tt_message_xcontext_set(\|)" "" "\f3245\fP"
.iM "tt_netfile_file(\|)" "" "\f3247\fP"
.iM "tt_objid_equal(\|)" "" "\f3249\fP"
.iM "tt_objid_objkey(\|)" "" "\f3251\fP"
.iM "tt_onotice_create(\|)" "" "\f3252\fP"
.iM "tt_open(\|)" "" "\f3254\fP"
.iM "tt_orequest_create(\|)" "" "\f3256\fP"
.iM "tt_otype_base(\|)" "" "\f3258\fP"
.iM "tt_otype_derived(\|)" "" "\f3259\fP"
.iM "tt_otype_deriveds_count(\|)" "" "\f3260\fP"
.iM "tt_otype_hsig_args_count(\|)" "" "\f3265\fP"
.iM "tt_otype_hsig_arg_mode(\|)" "" "\f3261\fP"
.iM "tt_otype_hsig_arg_type(\|)" "" "\f3263\fP"
.iM "tt_otype_hsig_count(\|)" "" "\f3266\fP"
.iM "tt_otype_hsig_op(\|)" "" "\f3267\fP"
.iM "tt_otype_is_derived(\|)" "" "\f3269\fP"
.iM "tt_otype_opnum_callback_add(\|)" "" "\f3270\fP"
.iM "tt_otype_osig_args_count(\|)" "" "\f3276\fP"
.iM "tt_otype_osig_arg_mode(\|)" "" "\f3272\fP"
.iM "tt_otype_osig_arg_type(\|)" "" "\f3274\fP"
.iM "tt_otype_osig_count(\|)" "" "\f3277\fP"
.iM "tt_otype_osig_op(\|)" "" "\f3278\fP"
.iM "tt_pattern_address_add(\|)" "" "\f3280\fP"
.iM "tt_pattern_arg_add(\|)" "" "\f3282\fP"
.iM "tt_pattern_barg_add(\|)" "" "\f3284\fP"
.iM "tt_pattern_bcontext_add(\|)" "" "\f3286\fP"
.iM "tt_pattern_callback_add(\|)" "" "\f3288\fP"
.iM "tt_pattern_category(\|)" "" "\f3290\fP"
.iM "tt_pattern_category_set(\|)" "" "\f3292\fP"
.iM "tt_pattern_class_add(\|)" "" "\f3294\fP"
.iM "tt_pattern_context_add(\|)" "" "\f3296\fP"
.iM "tt_pattern_create(\|)" "" "\f3298\fP"
.iM "tt_pattern_destroy(\|)" "" "\f3300\fP"
.iM "tt_pattern_disposition_add(\|)" "" "\f3301\fP"
.iM "tt_pattern_file_add(\|)" "" "\f3303\fP"
.iM "tt_pattern_iarg_add(\|)" "" "\f3304\fP"
.iM "tt_pattern_icontext_add(\|)" "" "\f3306\fP"
.iM "tt_pattern_object_add(\|)" "" "\f3308\fP"
.iM "tt_pattern_opnum_add(\|)" "" "\f3311\fP"
.iM "tt_pattern_op_add(\|)" "" "\f3310\fP"
.iM "tt_pattern_otype_add(\|)" "" "\f3312\fP"
.iM "tt_pattern_print(\|)" "" "\f3313\fP"
.iM "tt_pattern_register(\|)" "" "\f3314\fP"
.iM "tt_pattern_scope_add(\|)" "" "\f3316\fP"
.iM "tt_pattern_sender_add(\|)" "" "\f3318\fP"
.iM "tt_pattern_sender_ptype_add(\|)" "" "\f3319\fP"
.iM "tt_pattern_session_add(\|)" "" "\f3320\fP"
.iM "tt_pattern_state_add(\|)" "" "\f3321\fP"
.iM "tt_pattern_unregister(\|)" "" "\f3323\fP"
.iM "tt_pattern_user(\|)" "" "\f3324\fP"
.iM "tt_pattern_user_set(\|)" "" "\f3326\fP"
.iM "tt_pattern_xarg_add(\|)" "" "\f3327\fP"
.iM "tt_pattern_xcontext_add(\|)" "" "\f3329\fP"
.iM "tt_pnotice_create(\|)" "" "\f3331\fP"
.iM "tt_pointer_error(\|)" "" "\f3333\fP"
.iM "tt_prequest_create(\|)" "" "\f3334\fP"
.iM "tt_ptr_error(\|)" "" "\f3336\fP"
.iM "tt_ptype_declare(\|)" "" "\f3337\fP"
.iM "tt_ptype_exists(\|)" "" "\f3338\fP"
.iM "tt_ptype_opnum_callback_add(\|)" "" "\f3339\fP"
.iM "tt_ptype_undeclare(\|)" "" "\f3341\fP"
.iM "tt_release(\|)" "" "\f3342\fP"
.iM "tt_session_bprop(\|)" "" "\f3343\fP"
.iM "tt_session_bprop_add(\|)" "" "\f3345\fP"
.iM "tt_session_bprop_set(\|)" "" "\f3347\fP"
.iM "tt_session_join(\|)" "" "\f3349\fP"
.iM "tt_session_prop(\|)" "" "\f3350\fP"
.iM "tt_session_propname(\|)" "" "\f3357\fP"
.iM "tt_session_propnames_count(\|)" "" "\f3359\fP"
.iM "tt_session_prop_add(\|)" "" "\f3352\fP"
.iM "tt_session_prop_count(\|)" "" "\f3354\fP"
.iM "tt_session_prop_set(\|)" "" "\f3355\fP"
.iM "tt_session_quit(\|)" "" "\f3360\fP"
.iM "tt_session_types_load(\|)" "" "\f3361\fP"
.iM "tt_spec_bprop(\|)" "" "\f3362\fP"
.iM "tt_spec_bprop_add(\|)" "" "\f3364\fP"
.iM "tt_spec_bprop_set(\|)" "" "\f3366\fP"
.iM "tt_spec_create(\|)" "" "\f3368\fP"
.iM "tt_spec_destroy(\|)" "" "\f3370\fP"
.iM "tt_spec_file(\|)" "" "\f3371\fP"
.iM "tt_spec_move(\|)" "" "\f3373\fP"
.iM "tt_spec_prop(\|)" "" "\f3375\fP"
.iM "tt_spec_propname(\|)" "" "\f3383\fP"
.iM "tt_spec_propnames_count(\|)" "" "\f3385\fP"
.iM "tt_spec_prop_add(\|)" "" "\f3377\fP"
.iM "tt_spec_prop_count(\|)" "" "\f3379\fP"
.iM "tt_spec_prop_set(\|)" "" "\f3381\fP"
.iM "tt_spec_type(\|)" "" "\f3387\fP"
.iM "tt_spec_type_set(\|)" "" "\f3389\fP"
.iM "tt_spec_write(\|)" "" "\f3391\fP"
.iM "tt_status_message(\|)" "" "\f3393\fP"
.iM "tt_trace_control(\|)" "" "\f3394\fP"
.iM "tt_type_comp" "" "\f3480\fP"
.iM "tt_xcontext_quit(\|)" "" "\f3395\fP"
.iM "tt_X_session(\|)" "" "\f389\fP"
.iM "undefined" "" "\f36\fP"
.iM "underscore" "" "\f333\fP"
.iM "unspecified" "" "\f36\fP"
.iM "value type (vtype)" "" "\f333\fP"
.iM "virtual keys" "" "\f333\fP"
.iM "width increment" "" "\f333\fP"
.iM "window menu" "" "\f333\fP"
.iM "word" "" "\f333\fP"
.iM "workspace" "" "\f333\fP"
.iM "workspace functions" "" "\f334\fP"
.iM "workspace identifier" "" "\f334\fP"
.iM "workspace manager" "" "\f334\fP"
.iM "workspace name" "" "\f334\fP"
.iM "workspace title" "" "\f334\fP"
.iM "XDR" "" "\f334\fP"
.eF e
