.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtCreateEditor 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtCreateEditor(3) \- Creates a new instance of an Editor widget.\fP
.iX "DtCreateEditor"
.iX "creation functions" "DtCreateEditor"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
Widget DtEditorCreate (
.br
.ta	0.75i 1.75i
	Widget \fIparent\fP,
.br
	String \fIname\fP, 
.br
	ArgList \fIarglist\fP,
.br
	Cardinal \fIargcount\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorCreate()\fP creates an instance of a 
\fBDtEditor\fP widget and returns the associated widget ID.
.sp .5
.IP "\fIparent\fP" 1.00i
Specifies the parent widget ID
.IP "\fIname\fP" 1.00i
Specifies the name of the created widget
.IP "\fIarglist\fP" 1.00i
Specifies the argument list
.IP "\fIargcount\fP" 1.00i
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RETURN VALUE
Returns the Editor widget ID.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP.
.sp .5
