.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorCheckForUnsavedChanges 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorCheckForUnsavedChanges(3) \- Reports whether the data in a
Editor widget has been edited.\fP
.iX "DtEditorCheckForUnsavedChanges"
.iX "DtEditor functions" "DtEditorCheckForUnsavedChanges"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
Boolean DtEditorCheckForUnsavedChanges (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorCheckForUnsavedChanges\fP allows the application to query the
Editor widget specified by \fIwidget\fP to determine if any changes
have been made 
to its contents since the data was last read by the application or saved
to a file.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RETURN VALUE
\fBDtEditorCheckForUnsavedChanges\fP returns True if changes have been 
made to the widget's contents since the last call to 
\fBDtEditorGetContents(3)\fP or \fBDtEditorSaveContentsToFile(3)\fP. 
It returns False if the data has not changed since the last call.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP, 
\fBDtEditorGetContents(3)\fP,
\fBDtEditorSaveContentsToFile(3)\fP.
.sp .5
