.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorInvokeSpellDialog 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorInvokeSpellDialog(3) \- Checks contents of an Editor
widget for spelling errors.\fP
.iX "DtEditorInvokeSpellDialog"
.iX "DtEditor functions" "DtEditorInvokeSpellDialog"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
Boolean DtEditorInvokeSpellDialog (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorInvokeSpellDialog\fP filters the contents of \fIwidget\fP through
the filter specified by \fBDtNspellFilter\fP.  The output 
is placed in a dialog which provides the capability for the user to
search for the misspelled words and to specify a replacement.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RETURN VALUE
\fBDtEditorInvokeSpellDialog\fP returns True if the widget sucessfully
excuted the spell filter, otherwise returns False.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP,
\fBDtEditorManageDialogs(3)\fP, and
\fBDtEditorUnmanageDialogs(3)\fP.
.sp .5
