.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorFormat 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorFormat(3) \- Format all or part of the contents of an
Editor.\fP
.iX "DtEditorFormat"
.iX "DtEditor functions" "DtEditorFormat"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorFormat (
.ta	0.75i 1.75i
.br
	Widget	\fIwidget\fP,
.br
	unsigned int	\fIamountToFormat\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorFormat\fP formats either the current paragraph
or the entire contents of \fIwidget\fP,
according to the current (or default) settings in the
format settings dialog.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.IP "\fIamountToFormat\fP" 1.00i
When set to DtEDITOR_FORMAT_ALL the entire contents will be
reformatted.  When set to DtEDITOR_PARAGRAPH, only the paragraph
containing the insertion cursor will be formatted.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP,
\fBDtEditorInvokeFormatDialog(3)\fP.
.sp .5
