.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorUndoEdit 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorUndoEdit(3) \- Undoes the last edit made to the text in an 
Editor.\fP
.iX "DtEditorUndoEdit"
.iX "DtEditor functions" "DtEditorUndoEdit"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorUndoEdit (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorUndoEdit\fP Undoes the last change (deletion or insertion) made 
to the text in
\fIwidget\fP.  Undoing an edit once will restore the original text.
Undoing an edit twice will restore the last change.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP. 
.sp .5
