.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorUnselect 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorUnselect(3) \- Unselects selected text in an Editor.\fP
.iX "DtEditorUnselect"
.iX "DtEditor functions" "DtEditorUnselect"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorUnselect (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorUnselect\fP selects any currently selected text in an Editor widget.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP, 
\fBDtEditorClearSelection(3)\fP,
\fBDtEditorCopyToClipboard(3)\fP,
\fBDtEditorCutToClipboard(3)\fP,
\fBDtEditorDeleteSelection(3)\fP,
\fBDtEditorSelectAll(3)\fP.
.sp .5
