.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorGotoLine 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorGotoLine(3) \- Moves the insert cursor to a specified line.\fP
.iX "DtEditorGotoLine"
.iX "DtEditor functions" "DtEditorGotoLine"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
Boolean DtEditorGotoLine (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP
	unsigned int	lineNumber)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorGotoLine\fP moves the insert cursor to the beginning of the
line specified by \fIlineNumber\fP.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.IP "\fIlineNumber\fP" 1.00i
Specifies the line number within the widget.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RETURN VALUE
\fBDtEditorGotoLine\fP returns True if the insert cursor has been moved to the
requested line.  It returns False if the cursor could not be moved,
probably because the line does not exist.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP.
.sp .5
