.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorTraverseToEditor 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorTraverseToEditor(3) \- Set keyboard traversal to Editor.\fP
.iX "DtEditorTraverseToEditor"
.iX "DtEditor functions" "DtEditorTraverseToEditor"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorTraverseToEditor (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorTraverseToEditor\fP causes the OSF/Motif keyboard traversal
to be set to \fIwidget\fP. 
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP.
.sp .5
