.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorClearSelection 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorClearSelection(3) \- Replaces the currently selected data in
an Editor widget with blanks.\fP
.iX "DtEditorClearSelection"
.iX "DtEditor functions" "DtEditorClearSelection"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorClearSelection (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorClearSelection\fP replaces the currently highlighted data in 
the Editor widget, \fIwidget\fP,  with blanks (i.e. ASCII character 0x20)
and newlines.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP, 
\fBDtEditorCopyToClipboard(3)\fP.
\fBDtEditorCutToClipboard(3)\fP.
\fBDtEditorDeleteSelection(3)\fP,
\fBDtEditorPasteFromClipboard(3)\fP,
\fBDtEditorUndoEdit(3)\fP.
.sp .5
