.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorSetOverstrike 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorSetOverstrike(3) \- Turns overstrike mode on or 
off for an Editor widget.\fP
.iX "DtEditorSetOverstrike"
.iX "DtEditor functions" "DtEditorSetOverstrike"
.sp .5
.SH SYNOPSIS
.nf
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorSetOverstrike (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP,
	Boolean	\fIoverstrike\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorSetOverstrike\fP places or removes the
Editor widget, specified by \fIwidget\fP, into or out of overstrike mode.
If overstrike mode is turned on, characters typed into the Editor
widget are inserted at the position of the insertion cursor.  
If turned off, characters entered into the Editor widget replace the
characters that directly follow the insertion cursor.  When the end of
the line is reached, characters are appended to the end of the line.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.IP "\fIoverstrike\fP" 1.00i
When set to True, \fIwidget\fP will be in overstrike mode.  When set to
False, overstrike mode is turned off.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP. 
.sp .5
