.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Novell, Inc.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" **
.TH DtEditorInvokeFormatDialog 3 ""
.BH "3 May - 1994"
.SH NAME
\fBDtEditorInvokeFormatDialog(3) \- Display dialog for setting
formatting options for an Editor.\fP
.iX "DtEditorInvokeFormatDialog"
.iX "DtEditor functions" "DtEditorInvokeFormatDialog"
.sp .5
.SH SYNOPSIS
\fB
\&#include <Dt/Editor.h>
.sp .5
void DtEditorInvokeFormatDialog (
.br
.ta	0.75i 1.75i
	Widget	\fIwidget\fP)
.fi
\fP
.SH DESCRIPTION
\fBDtEditorInvokeFormatDialog\fP displays a dialog which allows a user
to set an Editor's formatting options - margins and justification
mode.  The dialog also allows the user to format either the paragraph
containing the insertion cursor or the entire document.
.sp .5
.IP "\fIwidget\fP" 1.00i
Specifies the editor widget ID.
.sp .5
.PP
For a complete definition of Editor and its associated resources, see
\fBDtEditor(3)\fP.
.sp .5
.SH RELATED INFORMATION
\fBDtEditor(3)\fP,
\fBDtEditorFormat(3)\fP,
\fBDtEditorManageDialogs(3)\fP,
\fBDtEditorUnmanageDialogs(3)\fP.
.sp .5
