.TH Get_Situation 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Sets"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.BH "1 March 1996" 
.IX "Get_Situation.4" "" "Get_Situation.4" "" 
.SH NAME
Get_Situation \- get a tool's current working directory
.SH SYNOPSIS
.ft 3
.nf
.ta \w@Get_Situation(@u
Get_Situation(out string \f2path\fP);
.PP
.fi
.SH DESCRIPTION
The
.I Get_Situation
request
reports the current working directory.
.PP
The
.I path
argument
is the pathname of the working directory that the recipient is using.
.SH "APPLICATION USAGE"
The
.BR ttdt_session_join (3),
function can be used to register for,
and transparently process, the
.I Get_Situation
request.
.SH "SEE ALSO"
.na
.BR ttdt_session_join (3);
.I Set_Situation
request.
