.TH Get_Environment 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Set"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.BH "1 March 1996" 
.IX "Get_Environment.4" "" "Get_Environment.4" "" 
.SH NAME
Get_Environment \- get a tool's environment
.SH SYNOPSIS
.ft 3
.nf
.ta \w@Get_Environment(@u
Get_Environment(in string \f2variable\fP,
	out string \f2value\fP
	[...]);
.PP
.fi
.SH DESCRIPTION
The
.I Get_Environment
request
reports the value of the indicated environment variable(s).
.PP
The
.I variable
argument
is the name of the environment variable to get.
.PP
The
.I value
argument
is the value of the environment variable.
If no value (in other words,
.BR (char\ *)0 )
is returned for this
argument, then the variable was not present in the
handler's environment.
This condition is not an error.
If an empty string (in other words, "\|")
is returned for this argument, then the variable was present in the
handler's environment, but had a null value.
.SH "APPLICATION USAGE"
The
.BR ttdt_session_join (3),
function can be used to register for,
and transparently process, the
.I Get_Environment
request.
.SH "SEE ALSO"
.na
.BR ttdt_session_join (3);
.I Set_Environment
request.
