.\" @ (#) Intro.4
.\" Introduction section for ToolTalk 1.3 Reference Manual
.TH Intro 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Sets"
.BH "1 March 1996"
.\" (c) Copyright 1996 Sun Microsystems, Inc.
.IX "Desktop Services Message Set" "" "Desktop Services Message Set" ""
.IX "Message Set" "desktop services" "message sets" "desktop services"
.SH NAME
Intro \- introduction to the ToolTalk Desktop Services Message Set
.SH OVERVIEW
This chapter contains the Desktop Message Set definitions. These
definitions demonstrate how a message set might be designed
for desktop application integration and how the message set might be used by 
various components of both OpenWindows and Common Desktop 
Environment (CDE). Elements of this message set are used to integrate 
a desktop application that supports features common to most 
desktop activities, such as, iconifying and deiconifying an application, 
exiting the desktop, and so on.
.PP
In order to see which messages are used by various desktop programs,
use tttrace(4) to watch messages passing through the ttsession(1) process.


