.TH Lower 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Sets"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.BH "1 March 1996" 
.IX "Lower.4" "" "Lower.4" "" 
.SH NAME
Lower \- lower a tool's window(s) to the back
.SH SYNOPSIS
.ft 3
.nf
.ta \w@Lower(@u
Lower([in messageID \f2commission\fP]);
.PP
.fi
.SH DESCRIPTION
The
.I Lower
request
lowers the window(s) associated with the handling procid.
If any optional arguments are present, then it
lowers only the indicated window(s).
.PP
The
.I commission
argument
is the ID of the message, if any, that resulted in the creation
of the window(s) that should be lowered.
.SH "APPLICATION USAGE"
The
.BR ttdt_session_join (3),
and
.BR ttdt_message_accept (3),
functions can be used by Xt applications to register for,
and transparently process, the
.I Lower
request.
.SH WARNINGS
.I Lower
can also be sent as a multicast notice, as an
.I edict
to all tools in the scope of the message.
The consequences of doing so can be severe and unexpected.
.SH "SEE ALSO"
.na
.BR ttdt_message_accept (3),
.BR ttdt_session_join (3);
.I Raise
request.
