.TH Resume 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Sets"
.de Lc
.\" version of .LI that emboldens its argument
.TP \\n()Jn
\s-1\f3\\$1\f1\s+1
..
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.BH "1 March 1996" 
.IX "Resume.4" "" "Resume.4" "" 
.SH NAME
Resume \- resume a tool, operation or data performance
.SH SYNOPSIS
.ft 3
.nf
.ta \w@Resume(@u
Resume([in messageID \f2operation\fP]);
.PP
.fi
.SH DESCRIPTION
The
.I Resume
request
resumes the specified tool, operation or data performance.
.PP
If the optional
.I operation
argument is included, the handler should resume the operation
that was invoked by the specified request.
.PP
The
.I operation
argument
is the request that should be resumed.
.SH ERRORS
The ToolTalk service may return the following error
in processing the
.I Resume
request:
.PP
.RS 3
.nr )J 6
.Lc TT_DESKTOP_ENOMSG
.br
The
.I operation
argument does not refer to any message currently known by the handler.
.PP
.RE
.nr )J 0
.SH "APPLICATION USAGE"
The
.BR ttdt_session_join (3),
and
.BR ttdt_message_accept (3),
functions can be used to register for,
and help process, the
.I Resume
request.
.SH "SEE ALSO"
.na
.BR ttdt_message_accept (3),
.BR ttdt_session_join (3);
.I Pause
request.
