.TH Reverted 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Sets"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.BH "1 March 1996" 
.IX "Reverted.4" "" "Reverted.4" "" 
.SH NAME
Reverted \- an entity has been reverted
.SH SYNOPSIS
.ft 3
.nf
.ta \w@[\f2file\fP] Reverted(@u
[\f2file\fP] Reverted(in \f2type ID\fP);
.PP
.fi
.SH DESCRIPTION
The
.I Reverted
notice is
sent when all the modifications (see the
.I Modified
notice) to an entity have been discarded.
.PP
The
.I ID
argument
is the identity of the modified or reverted entity.
When its
.I type
is
.BR File ,
then the
.I ID
argument is unset (in other words, has a
value of
.BR (char\ *)0 ),
and it refers to the file or directory
named in the message's file attribute.
.SH "APPLICATION USAGE"
The
.BR ttdt_file_join (3),
function can be used to register for,
and help process, the
.I Reverted
request.
.PP
The
.I Reverted
request can be sent with
.BR ttdt_file_event (3).
.SH "SEE ALSO"
.na
.BR ttdt_file_event (3),
.BR ttdt_file_join (3);
.I Saved
notice.
