.TH Saved 4 "1 March 1996" "ToolTalk 1.3" "Desktop Services Message Sets"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.BH "1 March 1996" 
.IX "Saved.4" "" "Saved.4" "" 
.SH NAME
Saved \- an entity has been saved to persistent storage
.SH SYNOPSIS
.ft 3
.nf
.ta \w@[\f2file\fP] Saved(@u
[\f2file\fP] Saved(in \f2type ID\fP);
.PP
.fi
.SH DESCRIPTION
The
.I Saved
notice announces that
the persistent storage for an entity (such
as a file) has been updated.
.PP
The
.I ID
argument is the identity of the saved entity.
When its
.I type
is
.BR File ,
then the
.I ID
argument is unset (in other words, has a
value of
.BR (char\ *)0 ),
and it refers to the file or directory
named in the message's file attribute.
.SH "APPLICATION USAGE"
The
.BR ttdt_file_join (3),
function can be used to register for,
and help process, the
.I Saved
request.
.PP
The
.I Saved
request can be sent with
.BR ttdt_file_event (3).
.SH "SEE ALSO"
.na
.BR ttdt_file_event (3),
.BR ttdt_file_join (3).
