/* $XConsortium: entext.h /main/cde1_maint/1 1995/07/17 22:53:53 drk $ */
/* Copyright (c) 1988, 1989 Hewlett-Packard Co. */
/* Entext.h contains the dtd- and interface-independent external
forms of declarations relevant to entity declarations that occur in a
dtd or interface.   The definition form of these declarations is
contained in files entity.h generated by BUILD and entity2.h
generated by ELTDEF */

#include "entdef.h"
extern M_WCHAR m_entcon[] ;

extern M_WCHAR m_entname[] ;

extern M_ENTITY m_entities[] ;

extern M_TRIE m_enttrie[] ;

#if defined(ELTEXTERN)
extern int m_entcnt ;
extern M_ENTITY *firstent ;
extern M_ENTITY *lastent ;
#endif
