/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: sdtfprop.c
 * Contains: main() and cross-module connections
 *
 * This file was generated by dtcodegen, from project sdtfprop
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <X11/Intrinsic.h>
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/Protocols.h>
#include <Dt/Help.h>
#include <Dt/HelpQuickD.h>
#include <Dt/HelpDialog.h>
#include <Dt/Session.h>
#include <nl_types.h>
#include "sdtfprop_ui.h"
#include "sdtfprop.h"
#include "dtb_utils.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/

#include <Dt/EnvControl.h>
#include <Dt/Connect.h>

#include "sdtfprop_uc.h"

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



/* Workaround for XPG4 API compatibility */
#if !defined(NL_CAT_LOCALE)
#define NL_CAT_LOCALE 0
#endif

/* Handle for standard message catalog for the project */
nl_catd	Dtb_project_catd = (nl_catd)-1;

/*
 * command line options...
 */
static XrmOptionDescRec optionDescList[] = {
    {"-session", "*session", XrmoptionSepArg, (XPointer)NULL}
    
    /*** DTB_USER_CODE_START vvv Add structure fields below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add structure fields above ^^^ ***/
};

/*
 * Application Resources
 */
static XtResource resources[] = {
    {"session", "Session", XtRString, sizeof(String),
        XtOffsetOf(DtbAppResourceRec, session_file), XtRImmediate, (XtPointer)NULL}
    
    /*** DTB_USER_CODE_START vvv Add structure fields below vvv ***/

    ,
    {"userFont", "UserFont", XmRFontList, sizeof(XmFontList),
        XtOffsetOf(DtbAppResourceRec, user_font), XmRString,
        (XtPointer)"fixed"}

    /*** DTB_USER_CODE_END   ^^^ Add structure fields above ^^^ ***/
};

DtbAppResourceRec	dtb_app_resource_rec;


/*
 * main for application sdtfprop
 */
int 
main(
    int argc,
    char **argv
)
{
    Widget		toplevel = (Widget)NULL;
    Display		*display = (Display*)NULL;
    XtAppContext	app = (XtAppContext)NULL;
    String		*fallback_resources = (String*)NULL;
    ArgList		init_args = (ArgList)NULL;
    Cardinal		num_init_args = (Cardinal)0;
    ArgList		get_resources_args = (ArgList)NULL;
    Cardinal		num_get_resources_args = (Cardinal)0;
    Atom		save_yourself_atom = (Atom)NULL;
    XtLanguageProc	language_proc = (XtLanguageProc)NULL;
    XtPointer		language_proc_client_data = (XtPointer)NULL;
    char		*tt_proc_id = NULL;
    int			tt_fd = -1;
    Tt_status		tt_status = TT_OK;
    Tt_pattern		*tt_session_pattern = (Tt_pattern*)NULL;
    char		*ttenv = NULL;
    char		*session = NULL;
    
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***  No initialization has been done.
     ***
     *** Add local variables and code.
     ***/
    
    char	tmp_buf[MAXPATHLEN];
    char	*file_name = NULL;
    int		root_id;

    _DtEnvControl(DT_ENV_SET);	/* Set up environment variables */

    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /* NULL language_proc installs the default Xt language procedure */
    XtSetLanguageProc((XtAppContext)NULL,
        language_proc, language_proc_client_data);
    
    toplevel = XtAppInitialize(&app, "Sdtfprop",
        optionDescList, XtNumber(optionDescList),
        &argc, argv, fallback_resources,
        init_args, num_init_args);

    /*
     * Get display and verify initialization was successful.
     */
    if (toplevel == NULL)
    {
        fprintf(stderr, "Could not open display.\n");
        exit(1);
    }
    display = XtDisplayOfObject(toplevel);
    
    /*
     * Open the standard message catalog for the project.
     */
    Dtb_project_catd = catopen(DTB_PROJECT_CATALOG, NL_CAT_LOCALE);
    if (Dtb_project_catd == (nl_catd)-1)
    {
        fprintf(stderr, "WARNING: Could not open message catalog: %s. Messages will be defaults.\n",
            DTB_PROJECT_CATALOG);
    }
    
    /*
     * Save the toplevel widget so it can be fetched later as needed.
     */
    dtb_save_toplevel_widget(toplevel);
    
    /*
     * Save the command used to invoke the application.
     */
    dtb_save_command(argv[0]);
    
    XtGetApplicationResources(toplevel, (XtPointer)&dtb_app_resource_rec,
        resources, XtNumber(resources),
        get_resources_args, num_get_resources_args);
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      A connection to the X server has been established, and all
     *** initialization has been done.
     ***
     ***  Add extra initialization code after this comment.
     ***/
    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    if (dtb_app_resource_rec.session_file)
    {
        dtb_set_client_session_restoreCB((DtbClientSessionRestoreCB)NULL);
        (void)dtb_session_restore(toplevel, dtb_app_resource_rec.session_file);
    }
    
    /*
     * Initialize all global variables.
     */
    dtbSdtfpropModdialogInfo_clear(&dtb_sdtfprop_moddialog);
    dtbSdtfpropPropdialogInfo_clear(&dtb_sdtfprop_propdialog);
    
    /*
     * Set up the application's root (primary) window.
     */
    dtb_sdtfprop_propdialog.propdialog = toplevel;
    XtVaSetValues(dtb_sdtfprop_propdialog.propdialog,
        XmNallowShellResize, True,
        XmNtitle, catgets(Dtb_project_catd, 2, 2, "Properties - (None)"),
        XmNinitialState, NormalState,
        XmNmwmDecorations, MWM_DECOR_ALL | MWM_DECOR_RESIZEH,
        XmNmwmFunctions, MWM_FUNC_ALL | MWM_FUNC_RESIZE,
        NULL);
    
    dtb_sdtfprop_propdialog_initialize(&(dtb_sdtfprop_propdialog), dtb_get_toplevel_widget());
    
    
    save_yourself_atom = XmInternAtom(XtDisplay(toplevel),
    	"WM_SAVE_YOURSELF", False);
    dtb_set_client_session_saveCB((DtbClientSessionSaveCB)NULL);
    
    XmAddWMProtocolCallback(toplevel, save_yourself_atom,
    	dtb_session_save, (XtPointer)NULL);
    
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      All initially-mapped widgets have been created, but not
     *** realized. Set resources on widgets, or perform other operations
     *** that must be completed before the toplevel widget is
     *** realized.
     ***/

    file_name = ParseArgs( argc, argv );

    proginfo.topLevel = toplevel;
    proginfo.appContext = app;
    proginfo.display = display;
    proginfo.screen = XtScreen( toplevel );
    proginfo.name = "Properties";
    proginfo.user_id = geteuid();
    proginfo.group_id = getegid();
    GetGroups( &proginfo.ngroups, &proginfo.grouplist );

    /* Check for root user */
    if ( ( root_id = GetUserID( "root" ) ) == -1 )
        root_id = 0;  /* Assume root is uid 0 */

    if ( geteuid() == root_id )
        proginfo.is_root_user = True;
    else
        proginfo.is_root_user = False;

    tmp_buf[0] = '\0';
    DtGetShortHostname( tmp_buf, MAXPATHLEN );
    proginfo.host = XtNewString( tmp_buf );

    tmp_buf[0] = '\0';
    if ( ( getcwd( tmp_buf, MAXPATHLEN ) ) == NULL )
    {
        proginfo.saved_errno = errno;
        ProcessErrorMsg( FATAL, True, NULL );
    }
    else
        proginfo.directory = XtNewString( tmp_buf );

    /* Initialize the ACL support funcions */ 
    proginfo.is_acl_support = LoadDynLibForACL();

    /* Create the Application Icon */
    CreateApplicationIcon();

    /* Post UI initialization */
    PropDialogPostCreateProc( &dtb_sdtfprop_propdialog );

    /* Set an Exit function to make sure we clean up. */
    atexit( ShutdownProperties );

    InitRun( file_name );

    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    XtRealizeWidget(toplevel);

    /*
     * Initialize ToolTalk to handle Desktop Message Protocol
     */
    
    ttenv = getenv("TT_SESSION");
    if (!ttenv || strlen(ttenv) == 0)
        ttenv = getenv("_SUN_TT_SESSION");
    if (!ttenv || strlen(ttenv) == 0)
    {
        session = tt_X_session(XDisplayString(display));
        tt_default_session_set(session);
        tt_free(session);
    }
    tt_proc_id = ttdt_open(&tt_fd, "sdtfprop", "NULL", "NULL", 1);
    tt_status = tt_ptr_error(tt_proc_id);
    if (tt_status != TT_OK)
    {
        fprintf(stderr,"ttdt_open(): %s\n", tt_status_message(tt_status));
        tt_proc_id = NULL;
    }
    else
    {
        XtAppAddInput(app, tt_fd, (XtPointer)XtInputReadMask,
            tttk_Xt_input_handler, tt_proc_id);

        tt_session_pattern = ttdt_session_join(NULL, dtb_tt_contractCB,
            toplevel, NULL, True);

        atexit(dtb_tt_close);
    }
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      All automatic initialization is complete. Add any additional
     *** code that should be executed before the Xt main loop is entered.
     ***/
    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /*
     * Enter event loop
     */
    XtAppMainLoop(app);
    return 0;
}


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


