/*
 * File: sdtfprop_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module sdtfprop
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _SDTFPROP_UI_H_
#define _SDTFPROP_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct {
    Widget	r_item;
    Widget	w_item;
    Widget	x_item;
} SdtfpropModPermCboxItemsRec, *SdtfpropModPermCboxItems;
typedef struct {
    Widget	User_item;
    Widget	Group_item;
    Widget	Default_User_item;
    Widget	Default_Group_item;
    Widget	Default_Owning_User_item;
    Widget	Default_Owning_Group_item;
    Widget	Default_Other_item;
    Widget	Default_Mask_item;
} SdtfpropModClassOmenuItemsRec, *SdtfpropModClassOmenuItems;
typedef struct {
    Widget	User_item;
    Widget	Group_item;
    Widget	Default_User_item;
    Widget	Default_Group_item;
    Widget	Default_Owning_User_item;
    Widget	Default_Owning_Group_item;
    Widget	Default_Other_item;
    Widget	Default_Mask_item;
} SdtfpropModClassOmenuMenuItemsRec, *SdtfpropModClassOmenuMenuItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	moddialog;	/* object "moddialog" */
    Widget	moddialog_shellform;
    Widget	moddialog_panedwin;
    Widget	moddialog_form;
    
    Widget	modDialogBpanel;
    Widget	modDialogFooter;
    Widget	controlpane;
    Widget	mod_permissionGroup;
    Widget	mod_effectiveGroup;
    Widget	mod_classGroup;
    Widget	mod_nameGroup;
    
    Widget	mod_permCbox;	/* object "mod_permCbox" */
    SdtfpropModPermCboxItemsRec	mod_permCbox_items;
    
    Widget	mod_permLabel;
    Widget	mod_effLabel;
    Widget	mod_effPermLabel;
    
    Widget	mod_classOmenu;	/* object "mod_classOmenu" */
    Widget	mod_classOmenu_menu;
    SdtfpropModClassOmenuItemsRec	mod_classOmenu_items;
    
    Widget	mod_classOmenuLabel;
    Widget	mod_classLabel;
    Widget	mod_nameTfield;
    Widget	mod_nameLabel;
    Widget	mod_separator;
    Widget	mod_okButton;
    Widget	mod_cancelButton;
    Widget	mod_helpButton;
    Widget	mod_footerLabel;
} DtbSdtfpropModdialogInfoRec, *DtbSdtfpropModdialogInfo;

typedef struct {
    Widget	Information_item;
    Widget	Permissions_item;
} SdtfpropCategoryRboxItemsRec, *SdtfpropCategoryRboxItems;
typedef struct {
    Widget	Information_item;
    Widget	Permissions_item;
} SdtfpropCategoryRboxChoiceItemsRec, *SdtfpropCategoryRboxChoiceItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropOwnerReadItemsRec, *SdtfpropOwnerReadItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropOwnerWriteItemsRec, *SdtfpropOwnerWriteItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropOwnerExecuteItemsRec, *SdtfpropOwnerExecuteItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropGroupReadItemsRec, *SdtfpropGroupReadItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropGroupWriteItemsRec, *SdtfpropGroupWriteItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropGroupExecuteItemsRec, *SdtfpropGroupExecuteItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropOtherReadItemsRec, *SdtfpropOtherReadItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropOtherWriteItemsRec, *SdtfpropOtherWriteItems;
typedef struct {
    Widget	nolabel_item;
} SdtfpropOtherExecuteItemsRec, *SdtfpropOtherExecuteItems;
typedef struct {
    Widget	This_File_Only_item;
    Widget	All_Files_in_Parent_Folder_item;
    Widget	All_Files_in_Parent_Folder_and_its_Subfolders_item;
} SdtfpropApplyFileOmenuItemsRec, *SdtfpropApplyFileOmenuItems;
typedef struct {
    Widget	This_Folder_Only_item;
    Widget	This_Folder_and_its_Subfolders_item;
} SdtfpropApplyFolderOmenuItemsRec, *SdtfpropApplyFolderOmenuItems;
typedef struct {
    Widget	This_File_Only_item;
    Widget	All_Files_in_Parent_Folder_item;
    Widget	All_Files_in_Parent_Folder_and_its_Subfolders_item;
} SdtfpropApplyFileOmenuMenuItemsRec, *SdtfpropApplyFileOmenuMenuItems;
typedef struct {
    Widget	This_Folder_Only_item;
    Widget	This_Folder_and_its_Subfolders_item;
} SdtfpropApplyFolderOmenuMenuItemsRec, *SdtfpropApplyFolderOmenuMenuItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	propdialog;	/* object "propdialog" */
    Widget	propdialog_mainwin;
    Widget	propdialog_form;
    
    Widget	categoryCpane_frame;	/* object "categoryCpane" */
    Widget	categoryCpane;
    
    Widget	objectNameCpane;
    Widget	propLayers;
    Widget	propDialogBpanel;
    
    Widget	categoryRbox_rowcolumn;	/* object "categoryRbox" */
    Widget	categoryRbox_label;
    Widget	categoryRbox;
    SdtfpropCategoryRboxItemsRec	categoryRbox_items;
    
    Widget	fileNameGroup;
    Widget	linkNameGroup;
    Widget	separator;
    Widget	nameLabel;
    Widget	fileNameTfield;
    Widget	browseButton;
    Widget	linkLabel;
    Widget	linkNameTfield;
    Widget	infoCpane;
    Widget	permCpane;
    Widget	infoOwnerLabel;
    Widget	infoOwnerName;
    Widget	infoGroupLabel;
    Widget	infoGroupName;
    Widget	infoSizeLabel;
    Widget	infoSize;
    Widget	infoAccessLabel;
    Widget	infoAccessTime;
    Widget	infoModifyLabel;
    Widget	infoModifyTime;
    Widget	basicPermCpane;
    Widget	aclPermCpane;
    Widget	applyCpane;
    Widget	readLabel;
    Widget	writeLabel;
    Widget	executeLabel;
    Widget	ownerLabel;
    Widget	groupLabel;
    Widget	otherLabel;
    
    Widget	ownerRead;	/* object "ownerRead" */
    SdtfpropOwnerReadItemsRec	ownerRead_items;
    
    Widget	ownerWrite;	/* object "ownerWrite" */
    SdtfpropOwnerWriteItemsRec	ownerWrite_items;
    
    Widget	ownerExecute;	/* object "ownerExecute" */
    SdtfpropOwnerExecuteItemsRec	ownerExecute_items;
    
    Widget	groupRead;	/* object "groupRead" */
    SdtfpropGroupReadItemsRec	groupRead_items;
    
    Widget	groupWrite;	/* object "groupWrite" */
    SdtfpropGroupWriteItemsRec	groupWrite_items;
    
    Widget	groupExecute;	/* object "groupExecute" */
    SdtfpropGroupExecuteItemsRec	groupExecute_items;
    
    Widget	otherRead;	/* object "otherRead" */
    SdtfpropOtherReadItemsRec	otherRead_items;
    
    Widget	otherWrite;	/* object "otherWrite" */
    SdtfpropOtherWriteItemsRec	otherWrite_items;
    
    Widget	otherExecute;	/* object "otherExecute" */
    SdtfpropOtherExecuteItemsRec	otherExecute_items;
    
    Widget	ownerNameTfield;
    Widget	groupNameTfield;
    Widget	ownerName;
    Widget	groupName;
    Widget	basicPermLabel;
    Widget	effectLabel;
    Widget	ownerEffectLabel;
    Widget	groupEffectLabel;
    Widget	otherEffectLabel;
    Widget	separator2;
    Widget	aclLabel;
    Widget	aclButton;
    
    Widget	accessList_scrolledwin;	/* object "accessList" */
    Widget	accessList;
    
    Widget	addButton;
    Widget	deleteButton;
    Widget	changeButton;
    Widget	classListLabel;
    Widget	nameListLabel;
    Widget	permListLabel;
    Widget	effectListLabel;
    Widget	separator3;
    
    Widget	applyFileOmenu;	/* object "applyFileOmenu" */
    Widget	applyFileOmenu_menu;
    SdtfpropApplyFileOmenuItemsRec	applyFileOmenu_items;
    
    Widget	applyToLabel;
    
    Widget	applyFolderOmenu;	/* object "applyFolderOmenu" */
    Widget	applyFolderOmenu_menu;
    SdtfpropApplyFolderOmenuItemsRec	applyFolderOmenu_items;
    
    Widget	separator1;
    Widget	okButton;
    Widget	applyButton;
    Widget	resetButton;
    Widget	cancelButton;
    Widget	helpButton;
} DtbSdtfpropPropdialogInfoRec, *DtbSdtfpropPropdialogInfo;


extern DtbSdtfpropModdialogInfoRec dtb_sdtfprop_moddialog;
extern DtbSdtfpropPropdialogInfoRec dtb_sdtfprop_propdialog;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbSdtfpropModdialogInfo_clear(DtbSdtfpropModdialogInfo instance);
int dtbSdtfpropPropdialogInfo_clear(DtbSdtfpropPropdialogInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_sdtfprop_moddialog_initialize(
    DtbSdtfpropModdialogInfo	instance,
    Widget	parent
);
int dtb_sdtfprop_propdialog_initialize(
    DtbSdtfpropPropdialogInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */
void PropDialogOK_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogApply_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogReset_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogCancel_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogHelp_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogDelete_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogACL_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogChange_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogAdd_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogItemSelect_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void ModDialogPermChange_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void ModDialogPostCreateProc_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void ModDialogClassTypeChange_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void PropDialogBrowse_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void UpdateOwnerEffectPerm_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void UpdateGroupEffectPerm_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void UpdateOtherEffectPerm_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void ShowInfoPane_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void ShowPermPane_CB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);

/*
 * Connections
 */
void sdtfprop_mod_cancelButton_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _SDTFPROP_UI_H_ */
