/* XPM */
static char * apps [] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X    s bottomShadowColor m black c #636363636363",
"o	s iconColor2	m white	c white",
"O    s iconGray3     m white c #adadadadadad",
"+    s topShadowColor m white c #bdbdbdbdbdbd",
"@    s iconGray5     m black c #737373737373",
"#	s iconColor1	m black	c black",
"$    s iconGray7     m black c #424242424242",
"%    s iconGray4     m white c #949494949494",
"&    s iconGray2     m white c #bdbdbdbdbdbd",
"*    s iconGray8     m black c #212121212121",
"=    s iconGray6     m black c #636363636363",
"-    s iconGray1     m white c #dededededede",
";    s selectColor m white c #737373737373",
":	s iconColor3	m black	c red",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                 .                              ",
"                 .                              ",
"                 .                              ",
"                 .                              ",
"     XXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"     Xooooooooooo.Oooooooooooooooooooooooooo+   ",
"     XoOOOOOOOOOO.@OOOOOOOOOOOOOOOOOOOOOOOO#+   ",
"     XoOOOOOOOOOO.@OOOOOoOOOOOOOOOOOOOooOOO#+   ",
"     XoOOOOOOOOoo.Ooooooooooooooooo$Ooo@@OO#+   ",
"     XoOOOOOOOOOO.@%%%%%%%%%%%%%%%#&@@@##OO#+   ",
"     XoOOOOOOOOOO.@######o$#######&o@$#%OOO#+   ",
"     XoOOOOOOOOOO.@@@@@@@o$O@@@@@o&@#O@OOOO#+   ",
"   &&&&&&&&&&OOOO.@OOOOOOOoOOOOOo&@#O@OOOO*==   ",
"  O@@@@@@@@@@OOOO.O@OOOOooo##OOo&@#O@OOOO*O=&#  ",
"  O=########@#OOO.-@OOOO@@#oOOo&@#O@OOOO*O..=#  ",
"  O=#$$$$$$$@#@O-.&@@OOOOOOo$o&@#O@OOOO*O.#@##  ",
"  O=#$$$$$$$@#@O-o.@@OOOOOOoo&@#O@OOOO*O.#@###  ",
"  O=#$$$$$$$@#@O..&@@OOOOOOo&@#O@OOOO*O.#@###;  ",
"  O=@@@@@@@@@#@O-o.@@OOOOOo&@#O@OOOO*O.#@###;   ",
"  O=&=&=&=&=@#@Oo.&@@OOOOo&@#O@OOOO*O.#@####    ",
"  O=========@#@O.o.@@OOOo&@#O@OOOOO=#@@###@#+   ",
"  O=@@@@@@@@@#@Oo.&@@OOOo@#O@OOOOO*$#####@@#+   ",
"  O=&=&=&=&=@#@O.o.@@OOOo#O@OOOOO*=$####@%%#+   ",
"  O=========@#@Oo.&@@OOo#O@OOOOO*=$###@@@%O#+   ",
"  O=@@@@@@@@@#@O.o.@@Oo#O@OOOOO*=$###@@%%OO#+   ",
"  O=&=&=&=&=@#@Oo.&@@O#O@OOOOO*=$###@@%OOOO#+   ",
"  O=========@#@O.o.@@OO@OOOOO*=$###@@%OOOOO#+   ",
"  O=@@@@@@@@@#@OOo#@OOOOOOOO*=$###@@%OOOOOO#+   ",
"  O=&=&=&&&=@#@OOo#@OOOOOOO*=$###@@%OOOOOOO#+   ",
"  O=========@#@OOo#@OOOOOO*=$###@@%OOOOOOOO#+   ",
"  O@@@@@@@@@@#@OO$$OOOOOO#=$###@@%OOOOOOOOO#+   ",
"   ##########=@O$$$$OOOO.o####@@%OOOOOOOOOO#+   ",
"     XO@@@@@@@OO$$$$OOO.o#.##@@%OOOOOOOOOOO#+   ",
"     XoOOOOOOOOOO::OOOOo###$@@%OOOOOOOOOOOO#+   ",
"     XoOOOOOOOOOO::OOOOOOO@@@%OOOOOOOOOOOOO#+   ",
"     XoOOOOOOOOOO::OOOOOOOOO%OOOOOOOOOOOOOO#+   ",
"     Xo#####################################+   ",
"     X+++++++++++++++++++++++++++++++++++++++   ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
