/* XPM */
/* Designed by the User Interaction Design Group, Hewlett-Packard */
/* Copyright (c) 1993 Hewlett-Packard */
static char *favorapps48[]={
/* width height ncolors cpp [x_hot y_hot] */
"48 48 22 1 0 0",
/* colors */
"  c none m none s none",
"$    s topShadowColor m white c #bdbdbdbdbdbd",
"&    s background    m black c #949494949494",
"(    s selectColor m white c #737373737373",
"*    s bottomShadowColor m black c #636363636363",
", s white      c white     m white",
". s iconColor1 c black     m black",
"B s iconColor2 c white     m white",
"4 s iconColor3 c red       m black",
"6 s iconColor4 c green     m white",
"8 s iconColor5 c blue      m black",
"2 s iconColor6 c yellow    m white",
": s iconColor7 c cyan      m white",
"0 s iconColor8 c magenta   m black",
"<    s iconGray1     m white c #dededededede",
">    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray3     m white c #adadadadadad",
"D    s iconGray4     m white c #949494949494",
"F    s iconGray5     m black c #737373737373",
"H    s iconGray6     m black c #636363636363",
"J    s iconGray7     m black c #424242424242",
"L    s iconGray8     m black c #212121212121",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                  2                             ",
"                  2                             ",
"                  2                             ",
"                  2                             ",
"      ************2***************************  ",
"      *,,,,,,,,,,,2@,,,,,,,,,,,,,,,,,,,,,,,,,$  ",
"      *,@@@@@@@@@@2F@@@@@@@@@@@@@@@@@@@@@@@@.$  ",
"      *,@@@@@@@@@@2F@@@@@,@@@@@@@@@@@@@,,@@@.$  ",
"      *,@@@@@@@@,,2@,,,,,,,,,,,,,,,,J@,,FF@@.$  ",
"      *,@@@@@@@@@@2FDDDDDDDDDDDDDDD.>FFF..@@.$  ",
"      *,@@@@@@@@@@2F......,J.......>,FJ.D@@@.$  ",
"      *,@@@@@@@@@@2FFFFFFF,J@FFFFF,>F.@F@@@@.$  ",
"    >>>>>>>>>>@@@@2F@@@@@@@,@@@@@,>F.@F@@@@LHH  ",
"   @FFFFFFFFFF@@@@2@F@@@@,,,..@@,>F.@F@@@@L@H>. ",
"   @H........F.@@@2<F@@@@FF.,@@,>F.@F@@@@L@22H. ",
"   @H.JJJJJJJF.F@<2>FF@@@@@@,J,>F.@F@@@@L@2.F.. ",
"   @H.JJJJJJJF.F@<,2FF@@@@@@,,>F.@F@@@@L@2.F... ",
"   @H.JJJJJJJF.F@22>FF@@@@@@,>F.@F@@@@L@2.F...( ",
"   @HFFFFFFFFF.F@<,2FF@@@@@,>F.@F@@@@L@2.F...(  ",
"   @H>H>H>H>HF.F@,2>FF@@@@,>F.@F@@@@L@2.F....   ",
"   @HHHHHHHHHF.F@2,2FF@@@,>F.@F@@@@@H.FF...F.$  ",
"   @HFFFFFFFFF.F@,2>FF@@@,F.@F@@@@@LJ.....FF.$  ",
"   @H>H>H>H>HF.F@2,2FF@@@,.@F@@@@@LHJ....FDD.$  ",
"   @HHHHHHHHHF.F@,2>FF@@,.@F@@@@@LHJ...FFFD@.$  ",
"   @HFFFFFFFFF.F@2,2FF@,.@F@@@@@LHJ...FFDD@@.$  ",
"   @H>H>H>H>HF.F@,2>FF@.@F@@@@@LHJ...FFD@@@@.$  ",
"   @HHHHHHHHHF.F@2,2FF@@F@@@@@LHJ...FFD@@@@@.$  ",
"   @HFFFFFFFFF.F@@,.F@@@@@@@@LHJ...FFD@@@@@@.$  ",
"   @H>H>H>>>HF.F@@,.F@@@@@@@LHJ...FFD@@@@@@@.$  ",
"   @HHHHHHHHHF.F@@,.F@@@@@@LHJ...FFD@@@@@@@@.$  ",
"   @FFFFFFFFFF.F@@JJ@@@@@@.HJ...FFD@@@@@@@@@.$  ",
"    ..........HF@JJJJ@@@@2,....FFD@@@@@@@@@@.$  ",
"      *@FFFFFFF@@JJJJ@@@2,.2..FFD@@@@@@@@@@@.$  ",
"      *,@@@@@@@@@@44@@@@,...JFFD@@@@@@@@@@@@.$  ",
"      *,@@@@@@@@@@44@@@@@@@FFFD@@@@@@@@@@@@@.$  ",
"      *,@@@@@@@@@@44@@@@@@@@@D@@@@@@@@@@@@@@.$  ",
"      *,.....................................$  ",
"      *$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
};
