/* XPM */
static char * VIf1Key [] = {
/* width height ncolors cpp [x_hot y_hot] */
"40 39 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray5     m black c #737373737373",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray3     m white c #adadadadadad",
"O    s iconGray1     m white c #dededededede",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray6     m black c #636363636363",
"#	s iconColor2	m white	c white",
"$    s selectColor m white c #737373737373",
/* pixels */
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"      ............................      ",
"     .XoXoXooooooooooooooooooooXOX.     ",
"    .OXXoXoXXXXXXXXXXXXXXXXXXXXOX++.    ",
"    .XOoO.X.X.X.X.X.X.X.X.X.X.Xo+++.    ",
"    .oXO.XOXOXOXOXOXOXOXOXOXOXOX+++.X   ",
"    .ooXOooooooooooooooooooooooX.++.XO  ",
"    .Xo.Xo@@@@@Ooo@@OooooooooooX+++.XO  ",
"    .ooXOo@@@@@#o@@@#ooooooooooX.++.XO  ",
"    .oo.Xo@@###Oo@@@#ooooooooooX+++.XO  ",
"    .ooXOo@@@@OooX@@#ooooooooooX.++.XO  ",
"    .oo.Xo@@@@#ooo@@#ooooooooooX+++.XO  ",
"    .ooXOo@@##Oooo@@#ooooooooooX.+$.XO  ",
"    .oo.Xo@@#ooooo@@#ooooooooooX++$.XO  ",
"    .ooXOo@@#ooooo@@#ooooooooooX.+$.XO  ",
"    .oo.XoO#OoooooO##ooooooooooX++$.XO  ",
"    .ooXOooooooooooooooooooooooX.+$.XO  ",
"    .oo.XooooooooooooooooooooooO++$.XO  ",
"    .ooXOoooooooooooooooooooooXX.+$.XO  ",
"    .oo.XoooooooooooooooooooooXO++$.XO  ",
"    .ooXOooooooooooooooooooooXOX.+$.XO  ",
"    .oo.+XoXoXoXoXoXoXoXoXoXOXXO++$.XO  ",
"    .ooX+oXXXXXXXXXXXXXXXXOXXO+.++$.XO  ",
"    .o.++.++++++++++++++++++++.++.$.XO  ",
"    .oX+.+....................+.++$.XO  ",
"    .oX.++++++++++++++++++++++$+.+$.XO  ",
"    .++++.++++++++++++++++++++.++$$.XO  ",
"    .o+++++++++++++++++++++++++$+$$.XO  ",
"    .+$+.+$+$+$+$+$+$+$+$+$+$+$.$$$.XO  ",
"     .$$$$$$$$$$$$$$$$$$$$$$$$$$$$.XO   ",
"      ..$$$$$$$$$$$$$$$$$$$$$$$$..XOO   ",
"        ........................XXOO    ",
"         OXXXXXXXXXXXXXXXXXXXXXXOOO     ",
"          OOOOOOOOOOOOOOOOOOOOOOO       ",
"                                        ",
"                                        "};
