.\" $Header: Cib.1,v 1.1 93/12/06 16:36:53 xbuild_hp_cv Exp $
.TH Cib 1 "" "" HP-UX
.ds )H Hewlett-Packard Company CV
.ds ]W June 1993
.SH NAME
Cib \- Check in binaries.
.SH SYNOPSIS
.B Cib
.I paths
.SH DESCRIPTION
.I Cib
takes the files given by 
.I paths
and deposits them in the parent directory of the RCS vault pointed to
by
.IR paths.
This program does not check for locking and stores no revisions. It
simply overwrites whatever file currently exists in the parent of the
RCS vault. It should be used very carefully and only when necessary
until a fully functional binary check-in program exists. There is no
equivalent 
.I Cob
program. You can use
.I Rls
to see if your check-in was successful.
Unlike the other access commands, you never give an RCS path to
.IR Cib. 
.SH EXAMPLES
If the RCS vault in the directory /clone/foo points to /x/cdeRCS/util/RCS
The following will place the file /clone/foo/binaryfile
into /x/cdeRCS/util/binaryfile:
.IP
.I cd /clone/foo;Cib binaryfile 
.IP
.I Cib /clone/foo/binaryfile
.SH WARNINGS
This is a very dangerous command. Please use it only when you have to.
.SH AUTHOR
.I Cib
was developed by Marc Ayotte
WTG-CV, Hewlett-Packard.
.SH SEE ALSO
Co(1),
Rcs(1), Rcsdiff(1),
Rlog(1),
Ci(1),
Rls(1),
Rcslocks(1).
