/* XPM */
static char * HPHelpKit [] = {
/* width height ncolors cpp [x_hot y_hot] */
"72 72 14 1 0 0",
/* colors */
"     s iconGray2     m white c #bdbdbdbdbdbd",
".	s none	m none	c none",
"X    s iconGray4     m white c #949494949494",
"o	s iconColor1	m black	c black",
"O    s iconGray3     m white c #adadadadadad",
"+    s iconGray5     m black c #737373737373",
"@    s iconGray7     m black c #424242424242",
"#	s iconColor2	m white	c white",
"$    s iconGray6     m black c #636363636363",
"%    s iconGray1     m white c #dededededede",
"&	s iconColor5	m black	c blue",
"*	s iconColor6	m white	c yellow",
"=    s iconGray8     m black c #212121212121",
"-	s iconColor3	m black	c red",
/* pixels */
"                                                                ........",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo........",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo........",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo........",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo........",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo.OOO....",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoO  OO...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+O   OOO..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+OO OOOOX+.",
" XXXXXXXXXXXXXX@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XXXXXXX+#OOOOOOX++$",
" XXXXXXXXXXXXXX@                                      XXXXX+O%#OOOOX++$@",
" XXXXXXXXXXXXXX@ &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@ XXXX+%#%%%OOX++$@@",
" XXXXXXXXXXXXXX@ &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@ XXX+*$%#X%%XX+$@@@",
" XXXXXXXXXXXXXX@ ooooooooooooooooooooo==============o XX+*#*$%%X%%++@@@.",
" XXXXXXXXXXXXXXX                                      X+*#*#*$%%X%X$@@ X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+*#*#*+*$%%XX$@ X ",
" XXXXXXXXXXXXXXXXXXXXXXXXXXX++++++++XXXXXXXXXXXXXXXXX+*#*#*+*+*$XX$@ X X",
" XXXXXXXXXXXXXXXXXXXXXXXXXX+########+XXXXXXXXXXXXXXX+*#*#*+*+*$$$$@OX X.",
" XXXXXXXXXXXXXXXXXXXXXXXXX+#OOOOOOOO#+XXXXXXXXXXXXX+*#*#*+*+*$$$$@OX X..",
" XXXXXXXXXXXXXXXXXXXXXXXX+#OOOOOOOOOO$XXXXXXXXXXXX+*#*#*+*+*$$$$@XXOX ..",
" XXXXXXXXXXXXXXXXXXXXXXXX+#OOOOOOOOOOO$XXXXXXXXXX+*#*#*+*+*$$$$@XXOX ...",
" XXXXXXXXXXXXXXXXXXXXXXXX+#OOO$$$$#OOO$XXXXXXXXX+*#*#*+*+*$$$$$oXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXX+#OOO$XX+#OOO$XXXXXXXX+*#*#*+*+*$$$$$XoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXX+#$$$$XX+#OOO$XXXXXXX+*#*#*+*+*$$$$$XXoXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+#OOOO$XXXXXX+*#*#*+*+*$$$$$XXXoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+#OOOO$XXXXXX+*#*#*+*+*$$$$$XXXXoXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXX+#OOOO$XXXXXX+*#*#*+*+*$$$$$XXXXXoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXX+#OOO$$XXXXXX+*#*#*+*+*$$$$$XXXXXXoXXXO  ..",
" @@@@@@@@@@@@@XXXXXXXXXXXXXXX+#OOO$XXXXXX+*#*#*+*+*$$$$$XXXXXXXoXXOO ...",
"               XXXXXXXXXXXXXX+#OOO$XXXXX+*#*#*+*+*$$$$$XXXXXXXXoXXXO  ..",
" ------------@ XXXXXXXXXXXXXX+#$$$$XXXX+*#*#*+*+*$$$$$XXXXXXXXXoXXOO ...",
" ------------@ XXXXXXXXXXXXXX++++++XXX+*#*#*+*+*$$$$$XXXXXXXXXXoXXXO  ..",
" ------------@ XXXXXXXXXXXXXX+####+XX+*#*#*+*+*$$$$$XXXXXXXXXXXoXXOO ...",
" ------------@ XXXXXXXXXXXXXX+#OOO$X+*#*#*+*+*$$$$$XXXXXXXXXXXXoXXXO  ..",
" ------------@ XXXXXXXXXXXXXX+#OOO$+*#*#*+*+*$$$$$XXXXXXXXXXXXXoXXOO ...",
" ------------@ XXXXXXXXXXXXXX+#$$$$*#*#*+*+*$$$$$XXXXXXXXXXXXXXoXXXO  ..",
" ------------@ XXXXXXXXXXXXXXXXXXX+O*#*+*+*$$$$$XXXXXXXXXXXXXXXoXXOO ...",
" @@@@@@@@@@@@@ XXXXXXXXXXXXXXXXXXXO##*+*+*$$$$$XXXXXXXXXXXXXXXXoXXXO  ..",
"               XXXXXXXXXXXXXXXXXX+O#+#*+*$$$$$XXXXXXXXXXXXXXXXXoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO#XX#$*$$$$$XXXXXXXXXXXXXXXXXXoXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+O#X#$$$$$$$XXXXXXXXXXXXXXXXXXXoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO#+#$$$$$$$XXXXXXXXXXXXXXXXXXXXoXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+O##$$$$$$$XXXXXXXXXXXXXXXXXXXXXoXXOO ...",
" XX=XX=XX====%X=XXXXX=== XXXXXXO##+$$$$++XXXXXXXXXXXXXXXXXXXXXXoXXXO  ..",
" XX=%X=%X=%%%%X=%XXXX=%%=%XXXX+O#+$$$++XXXXXXXXXXXXXXXXXXXXXXXXoXXOO ...",
" XX=%X=%X=%XXXX=%XXXX=%+=%XXXXo#+$$++XXXXXXXXXXXXXXXXXXXXXXXXXXoXXXO  ..",
" XX====%X===%XX=%XXXX===%XXXXXoo$++XXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXOO ...",
" XX=%%=%X=%%%XX=%XXXX=%%XXXXXooo+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXO  ..",
" XX=%X=%X=%XXXX=%XXXX=%XXXXXXo++XXXXXXXXXXXXXXXXXXXX@@@@@@@@@@@oXXOO ...",
" XX=%X=%X====%X====%X=%XXXXXo+XXXXXXXXXXXXXXXXXXXXXX@          oXXXO  ..",
" XXX%XX%XX%%%%XX%%%%XX%XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXOO ...",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXO  ..",
" XX===XXX===%X= XX= X===%X=XXXXXX==XXX=== XX===%X===XXX=%X== XXoXXOO ...",
" XX=%%=XX=%%%X=%XX=%X=%%%X=%XXXX=%%=XX=%%=%X=%%%X=%%=%X=%=%%=%XoXXXO  ..",
" XX=%X=%X=%XXXX= =%%X=%XXX=%XXXX=%X=%X=%+=%X=%XXX=%+=%=%X=%XXXXoXXOO ...",
" XX=%X=%X===%XX=%=%XX===%X=%XXXX=%X=%X===%XX===%X===%XXXXX==%XXoXXXO  ..",
" XX=%X=%X=%%%XX=%=%XX=%%%X=%XXXX=%X=%X=%%XXX=%%%X=%%=%XXXXXX=%XoXXOO ...",
" XX=%X=%X=%XXXXX=%%XX=%XXX=%XXXX=%X=%X=%XXXX=%XXX=%X=%XXX=%X=%XoXXXO  ..",
" XX===%XX===%XXX=%XXX===%X====%XX==%XX=%XXXX===%X=%X=%XXXX==%XXoXXOO ...",
" XXX%%XXXX%%%XXXX%XXXX%%%X%%%%%XX%%XXXX%XXXXX%%%XX%XX%XXXX%%XXXoXXXO  ..",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXOO ...",
" oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXO  ..",
"........ OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOO ...",
".......  OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO  ..",
"........ OOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOO ...",
".......  OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  ..",
"........                                                             ...",
"....... . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ..",
"........................................................................",
"........................................................................"};
