/*
 * File: Rule_edit_ui.C
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module Rule_edit
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/PanedW.h>
#include <Xm/Separator.h>
#include <Xm/Label.h>
#include <Xm/RowColumn.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>
#include <Xm/PushB.h>
#include "dtb_utils.h"
#include "dtmailopts.h"
#include "Rule_edit_ui.h"


DtbRuleEditDialogInfoRec	dtb_rule_edit_dialog = 
{
    False	 /* initialized */
};

/*
 * Widget create procedure decls
 */
static int dtb_rule_edit_dialog_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_dialog_button_panel_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_controlpane_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_sep3_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_sep1_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_sep2_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_if_label_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_matchi_label_tf_gp_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_rule_on_off_checkbox_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_rule_name_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_checkbox_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_then_label_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_action_gp_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_editor_to_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_editor_cc_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_editor_to_or_cc_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_editor_from_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_editor_sub_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_store_msg_tf_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_browse_but_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_add_button_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_change_button_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_reset_button_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_cancel_button_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);
static int dtb_rule_edit_help_button_create(
    DtbRuleEditDialogInfo	instance,
    Widget	parent
);

int 
dtbRuleEditDialogInfo_clear(DtbRuleEditDialogInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_rule_edit_dialog_initialize(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_rule_edit_dialog_create(instance,
        parent);
    dtb_rule_edit_dialog_button_panel_create(instance,
        instance->dialog_panedwin);
    dtb_rule_edit_controlpane_create(instance,
        instance->dialog_form);
    dtb_rule_edit_sep3_create(instance,
        instance->controlpane);
    dtb_rule_edit_sep1_create(instance,
        instance->controlpane);
    dtb_rule_edit_sep2_create(instance,
        instance->controlpane);
    dtb_rule_edit_if_label_create(instance,
        instance->controlpane);
    dtb_rule_edit_matchi_label_tf_gp_create(instance,
        instance->controlpane);
    dtb_rule_edit_rule_on_off_checkbox_create(instance,
        instance->controlpane);
    dtb_rule_edit_rule_name_tf_create(instance,
        instance->controlpane);
    dtb_rule_edit_checkbox_create(instance,
        instance->controlpane);
    dtb_rule_edit_then_label_create(instance,
        instance->controlpane);
    dtb_rule_edit_action_gp_create(instance,
        instance->controlpane);
    dtb_rule_edit_editor_to_tf_create(instance,
        instance->matchi_label_tf_gp);
    dtb_rule_edit_editor_cc_tf_create(instance,
        instance->matchi_label_tf_gp);
    dtb_rule_edit_editor_to_or_cc_tf_create(instance,
        instance->matchi_label_tf_gp);
    dtb_rule_edit_editor_from_tf_create(instance,
        instance->matchi_label_tf_gp);
    dtb_rule_edit_editor_sub_tf_create(instance,
        instance->matchi_label_tf_gp);
    dtb_rule_edit_store_msg_tf_create(instance,
        instance->action_gp);
    dtb_rule_edit_browse_but_create(instance,
        instance->action_gp);
    dtb_rule_edit_add_button_create(instance,
        instance->dialog_button_panel);
    dtb_rule_edit_change_button_create(instance,
        instance->dialog_button_panel);
    dtb_rule_edit_reset_button_create(instance,
        instance->dialog_button_panel);
    dtb_rule_edit_cancel_button_create(instance,
        instance->dialog_button_panel);
    dtb_rule_edit_help_button_create(instance,
        instance->dialog_button_panel);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->sep3,
        XmNtopWidget, instance->action_gp,
        NULL);
    
    XtVaSetValues(instance->sep1,
        XmNtopWidget, instance->rule_on_off_checkbox,
        NULL);
    
    XtVaSetValues(instance->sep2,
        XmNtopWidget, instance->matchi_label_tf_gp,
        NULL);
    
    XtVaSetValues(instance->if_label,
        XmNtopWidget, instance->sep1,
        NULL);
    
    XtVaSetValues(instance->matchi_label_tf_gp,
        XmNtopWidget, instance->if_label,
        NULL);
    
    XtVaSetValues(instance->rule_on_off_checkbox,
        XmNleftWidget, instance->rule_name_tf_rowcolumn,
        NULL);
    
    XtVaSetValues(instance->checkbox,
        XmNleftWidget, instance->rule_name_tf_rowcolumn,
        XmNtopWidget, instance->rule_name_tf_rowcolumn,
        NULL);
    
    XtVaSetValues(instance->then_label,
        XmNtopWidget, instance->sep2,
        NULL);
    
    XtVaSetValues(instance->action_gp,
        XmNtopWidget, instance->then_label,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    dtb_children_align(instance->matchi_label_tf_gp,
		DTB_GROUP_COLUMNS,
		DTB_ALIGN_NONE,
		DTB_ALIGN_LABELS,
		0, 1, 0, 0, 5);
    
    dtb_children_align(instance->action_gp,
		DTB_GROUP_ROWS,
		DTB_ALIGN_HCENTER,
		DTB_ALIGN_NONE,
		0, 1, 0, 13, 0);
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->editor_to_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->editor_cc_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->editor_to_or_cc_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->editor_from_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->editor_sub_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->matchi_label_tf_gp,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->rule_on_off_checkbox,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->rule_name_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->checkbox,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->store_msg_tf_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->action_gp,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->controlpane,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->dialog_form);
    XtManageChild(instance->dialog_button_panel);
    XtVaGetValues(instance->dialog_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->dialog_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->add_button,
		XmNactivateCallback, editor_add_cb,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->change_button,
		XmNactivateCallback, editor_change_cb,
		(XtPointer)&(*instance));
	XtAddCallback(instance->reset_button,
		XmNactivateCallback, editor_reset_cb,
		(XtPointer)&(*instance));
	XtAddCallback(instance->cancel_button,
		XmNactivateCallback, Rule_edit_cancel_button_CB1,
		(XtPointer)&(*instance));
	XtAddCallback(instance->help_button,
		XmNactivateCallback, editor_help_cb,
		(XtPointer)&(*instance));
return 0;
}



static int 
dtb_rule_edit_dialog_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    String	title_str = NULL;
    
    if (instance->dialog == NULL) {
        title_str = XtNewString(catgets(Dtb_project_catd, 3, 1, "Mailer - Rules Editor"));
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, title_str);  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->dialog =
            XmCreateDialogShell(parent,
                "dtb_Rule_edit_dialog", args, n);
        XtFree(title_str);
        title_str = NULL;
    }
    if (instance->dialog == NULL)
        return -1;

    if (instance->dialog_shellform == NULL) {
        instance->dialog_shellform =
            XtVaCreateWidget("dtb_Rule_edit_dialog_shellform",
                xmFormWidgetClass,
                instance->dialog,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->dialog, "white"),
                NULL);
    }
    if (instance->dialog_shellform == NULL)
        return -1;

    if (instance->dialog_panedwin == NULL) {
        instance->dialog_panedwin =
            XtVaCreateWidget("dialog_panedwin",
                xmPanedWindowWidgetClass,
                instance->dialog_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->dialog_shellform, "white"),
                NULL);
    }
    if (instance->dialog_panedwin == NULL)
        return -1;

    if (instance->dialog_form == NULL) {
        instance->dialog_form =
            XtVaCreateWidget("dialog_form",
                xmFormWidgetClass,
                instance->dialog_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNbackground, dtb_cvt_string_to_pixel(instance->dialog_panedwin, "white"),
                NULL);
    }
    if (instance->dialog_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_dialog_button_panel_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel == NULL) {
        instance->dialog_button_panel =
            XtVaCreateWidget("dialog_button_panel",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_controlpane_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane == NULL) {
        instance->controlpane =
            XtVaCreateWidget("controlpane",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, -1,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, -1,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                NULL);
    }
    if (instance->controlpane == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_sep3_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->sep3 == NULL) {
        instance->sep3 =
            XtVaCreateWidget("sep3",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 2,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, -2,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 15,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 11,
                XmNy, 540,
                NULL);
    }
    if (instance->sep3 == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_sep1_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->sep1 == NULL) {
        instance->sep1 =
            XtVaCreateWidget("sep1",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, -2,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 23,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 10,
                XmNy, 104,
                XmNx, 0,
                NULL);
    }
    if (instance->sep1 == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_sep2_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->sep2 == NULL) {
        instance->sep2 =
            XtVaCreateWidget("sep2",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 5,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, -3,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 11,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 10,
                XmNy, 323,
                NULL);
    }
    if (instance->sep2 == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_if_label_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 34, "If message meets these criteria:\n"));
    if (instance->if_label == NULL) {
        instance->if_label =
            XtVaCreateWidget("if_label",
                xmLabelWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 33,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 8,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 122,
                XmNx, 33,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->if_label == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_matchi_label_tf_gp_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->matchi_label_tf_gp == NULL) {
        instance->matchi_label_tf_gp =
            XtVaCreateWidget("matchi_label_tf_gp",
                xmFormWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 146,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNy, 156,
                XmNx, 146,
                NULL);
    }
    if (instance->matchi_label_tf_gp == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_rule_on_off_checkbox_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[23];	/* need 18 args (add 5 to be safe) */
    int	n = 0;
    Widget	rule_on_off_checkbox_items[2];
    
    if (instance->rule_on_off_checkbox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNleftOffset, 31);  ++n;
        XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET);  ++n;
        XtSetArg(args[n], XmNtopOffset, 21);  ++n;
        XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNradioBehavior, True);  ++n;
        XtSetArg(args[n], XmNentryClass, xmToggleButtonWidgetClass);  ++n;
        XtSetArg(args[n], XmNnumColumns, 1);  ++n;
        XtSetArg(args[n], XmNspacing, 0);  ++n;
        XtSetArg(args[n], XmNrowColumnType, XmWORK_AREA);  ++n;
        XtSetArg(args[n], XmNentryVerticalAlignment, XmALIGNMENT_BASELINE_BOTTOM);  ++n;
        XtSetArg(args[n], XmNorientation, XmVERTICAL);  ++n;
        XtSetArg(args[n], XmNpacking, XmPACK_TIGHT);  ++n;
        XtSetArg(args[n], XmNisHomogeneous, True);  ++n;
        XtSetArg(args[n], XmNy, 21);  ++n;
        XtSetArg(args[n], XmNx, 528);  ++n;
        instance->rule_on_off_checkbox =
            XmCreateRadioBox(parent,
                "rule_on_off_checkbox", args, n);
    }
    if (instance->rule_on_off_checkbox == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 43, "On"));
    if (instance->rule_on_off_checkbox_items.On_item == NULL) {
        instance->rule_on_off_checkbox_items.On_item =
            XtVaCreateManagedWidget("On_item",
                xmToggleButtonWidgetClass,
                instance->rule_on_off_checkbox,
                XmNset, True,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->rule_on_off_checkbox_items.On_item == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 44, "Off"));
    if (instance->rule_on_off_checkbox_items.Off_item == NULL) {
        instance->rule_on_off_checkbox_items.Off_item =
            XtVaCreateManagedWidget("Off_item",
                xmToggleButtonWidgetClass,
                instance->rule_on_off_checkbox,
                XmNset, False,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->rule_on_off_checkbox_items.Off_item == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_rule_name_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[25];	/* need 20 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->rule_name_tf_rowcolumn == NULL) {
        instance->rule_name_tf_rowcolumn =
            XtVaCreateWidget("rule_name_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 138,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 28,
                XmNtopAttachment, XmATTACH_FORM,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                XmNy, 28,
                XmNx, 138,
                NULL);
    }
    if (instance->rule_name_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 50, "Rule name:"));
    if (instance->rule_name_tf_label == NULL) {
        instance->rule_name_tf_label =
            XtVaCreateWidget("rule_name_tf_label",
                xmLabelWidgetClass,
                instance->rule_name_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->rule_name_tf_label == NULL)
        return -1;

    if (instance->rule_name_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->rule_name_tf =
            XmCreateTextField(instance->rule_name_tf_rowcolumn,
                "rule_name_tf", args, n);
    }
    if (instance->rule_name_tf == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_checkbox_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[24];	/* need 19 args (add 5 to be safe) */
    int	n = 0;
    Widget	checkbox_items[1];
    
    if (instance->checkbox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNleftOffset, -7);  ++n;
        XtSetArg(args[n], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET);  ++n;
        XtSetArg(args[n], XmNtopOffset, 9);  ++n;
        XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET);  ++n;
        XtSetArg(args[n], XmNradioBehavior, False);  ++n;
        XtSetArg(args[n], XmNentryClass, xmToggleButtonWidgetClass);  ++n;
        XtSetArg(args[n], XmNnumColumns, 1);  ++n;
        XtSetArg(args[n], XmNspacing, 0);  ++n;
        XtSetArg(args[n], XmNrowColumnType, XmWORK_AREA);  ++n;
        XtSetArg(args[n], XmNentryVerticalAlignment, XmALIGNMENT_BASELINE_BOTTOM);  ++n;
        XtSetArg(args[n], XmNorientation, XmVERTICAL);  ++n;
        XtSetArg(args[n], XmNpacking, XmPACK_TIGHT);  ++n;
        XtSetArg(args[n], XmNisHomogeneous, True);  ++n;
        XtSetArg(args[n], XmNy, 64);  ++n;
        XtSetArg(args[n], XmNx, 131);  ++n;
        instance->checkbox =
            XmCreateRadioBox(parent,
                "checkbox", args, n);
    }
    if (instance->checkbox == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 52, "Skip remaining rules if message matches this rule"));
    if (instance->checkbox_items.Skip_remaining_rules_if_message_matches_this_rule_item == NULL) {
        instance->checkbox_items.Skip_remaining_rules_if_message_matches_this_rule_item =
            XtVaCreateManagedWidget("Skip_remaining_rules_if_message_matches_this_rule_item",
                xmToggleButtonWidgetClass,
                instance->checkbox,
                XmNset, True,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->checkbox_items.Skip_remaining_rules_if_message_matches_this_rule_item == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_then_label_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 53, "Then do this:"));
    if (instance->then_label == NULL) {
        instance->then_label =
            XtVaCreateWidget("then_label",
                xmLabelWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 31,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 8,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 340,
                XmNx, 31,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->then_label == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_action_gp_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    
    if (instance->action_gp == NULL) {
        instance->action_gp =
            XtVaCreateWidget("action_gp",
                xmFormWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 85,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 2,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNy, 361,
                XmNx, 85,
                NULL);
    }
    if (instance->action_gp == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_editor_to_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[17];	/* need 12 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->editor_to_tf_rowcolumn == NULL) {
        instance->editor_to_tf_rowcolumn =
            XtVaCreateWidget("editor_to_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                NULL);
    }
    if (instance->editor_to_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 10, "To:"));
    if (instance->editor_to_tf_label == NULL) {
        instance->editor_to_tf_label =
            XtVaCreateWidget("editor_to_tf_label",
                xmLabelWidgetClass,
                instance->editor_to_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->editor_to_tf_label == NULL)
        return -1;

    if (instance->editor_to_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->editor_to_tf =
            XmCreateTextField(instance->editor_to_tf_rowcolumn,
                "editor_to_tf", args, n);
    }
    if (instance->editor_to_tf == NULL)
        return -1;

    
    /*
     * Call user (Post-)Create procs
     */
    create_match_tf(instance->editor_to_tf, (XtPointer)NULL, (XtPointer)instance);
    return 0;
}



static int 
dtb_rule_edit_editor_cc_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[17];	/* need 12 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->editor_cc_tf_rowcolumn == NULL) {
        instance->editor_cc_tf_rowcolumn =
            XtVaCreateWidget("editor_cc_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                NULL);
    }
    if (instance->editor_cc_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 46, "Cc:"));
    if (instance->editor_cc_tf_label == NULL) {
        instance->editor_cc_tf_label =
            XtVaCreateWidget("editor_cc_tf_label",
                xmLabelWidgetClass,
                instance->editor_cc_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->editor_cc_tf_label == NULL)
        return -1;

    if (instance->editor_cc_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->editor_cc_tf =
            XmCreateTextField(instance->editor_cc_tf_rowcolumn,
                "editor_cc_tf", args, n);
    }
    if (instance->editor_cc_tf == NULL)
        return -1;

    
    /*
     * Call user (Post-)Create procs
     */
    create_match_tf(instance->editor_cc_tf, (XtPointer)NULL, (XtPointer)instance);
    return 0;
}



static int 
dtb_rule_edit_editor_to_or_cc_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[17];	/* need 12 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->editor_to_or_cc_tf_rowcolumn == NULL) {
        instance->editor_to_or_cc_tf_rowcolumn =
            XtVaCreateWidget("editor_to_or_cc_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                NULL);
    }
    if (instance->editor_to_or_cc_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 54, "To or Cc:"));
    if (instance->editor_to_or_cc_tf_label == NULL) {
        instance->editor_to_or_cc_tf_label =
            XtVaCreateWidget("editor_to_or_cc_tf_label",
                xmLabelWidgetClass,
                instance->editor_to_or_cc_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->editor_to_or_cc_tf_label == NULL)
        return -1;

    if (instance->editor_to_or_cc_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->editor_to_or_cc_tf =
            XmCreateTextField(instance->editor_to_or_cc_tf_rowcolumn,
                "editor_to_or_cc_tf", args, n);
    }
    if (instance->editor_to_or_cc_tf == NULL)
        return -1;

    
    /*
     * Call user (Post-)Create procs
     */
    create_match_tf(instance->editor_to_or_cc_tf, (XtPointer)NULL, (XtPointer)instance);
    return 0;
}



static int 
dtb_rule_edit_editor_from_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[17];	/* need 12 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->editor_from_tf_rowcolumn == NULL) {
        instance->editor_from_tf_rowcolumn =
            XtVaCreateWidget("editor_from_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                NULL);
    }
    if (instance->editor_from_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 14, "From:"));
    if (instance->editor_from_tf_label == NULL) {
        instance->editor_from_tf_label =
            XtVaCreateWidget("editor_from_tf_label",
                xmLabelWidgetClass,
                instance->editor_from_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->editor_from_tf_label == NULL)
        return -1;

    if (instance->editor_from_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->editor_from_tf =
            XmCreateTextField(instance->editor_from_tf_rowcolumn,
                "editor_from_tf", args, n);
    }
    if (instance->editor_from_tf == NULL)
        return -1;

    
    /*
     * Call user (Post-)Create procs
     */
    create_match_tf(instance->editor_from_tf, (XtPointer)NULL, (XtPointer)instance);
    return 0;
}



static int 
dtb_rule_edit_editor_sub_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[17];	/* need 12 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->editor_sub_tf_rowcolumn == NULL) {
        instance->editor_sub_tf_rowcolumn =
            XtVaCreateWidget("editor_sub_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                NULL);
    }
    if (instance->editor_sub_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 15, "Subject:"));
    if (instance->editor_sub_tf_label == NULL) {
        instance->editor_sub_tf_label =
            XtVaCreateWidget("editor_sub_tf_label",
                xmLabelWidgetClass,
                instance->editor_sub_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->editor_sub_tf_label == NULL)
        return -1;

    if (instance->editor_sub_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->editor_sub_tf =
            XmCreateTextField(instance->editor_sub_tf_rowcolumn,
                "editor_sub_tf", args, n);
    }
    if (instance->editor_sub_tf == NULL)
        return -1;

    
    /*
     * Call user (Post-)Create procs
     */
    create_match_tf(instance->editor_sub_tf, (XtPointer)NULL, (XtPointer)instance);
    return 0;
}



static int 
dtb_rule_edit_store_msg_tf_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[17];	/* need 12 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->store_msg_tf_rowcolumn == NULL) {
        instance->store_msg_tf_rowcolumn =
            XtVaCreateWidget("store_msg_tf_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                NULL);
    }
    if (instance->store_msg_tf_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 55, "Store message to:"));
    if (instance->store_msg_tf_label == NULL) {
        instance->store_msg_tf_label =
            XtVaCreateWidget("store_msg_tf_label",
                xmLabelWidgetClass,
                instance->store_msg_tf_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->store_msg_tf_label == NULL)
        return -1;

    if (instance->store_msg_tf == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 38);  ++n;
        instance->store_msg_tf =
            XmCreateTextField(instance->store_msg_tf_rowcolumn,
                "store_msg_tf", args, n);
    }
    if (instance->store_msg_tf == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_browse_but_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 56, "Select Mailbox..."));
    if (instance->browse_but == NULL) {
        instance->browse_but =
            XtVaCreateWidget("browse_but",
                xmPushButtonWidgetClass,
                parent,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->browse_but == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_add_button_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 47, "Add"));
    if (instance->add_button == NULL) {
        instance->add_button =
            XtVaCreateWidget("add_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 19,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 2,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 110,
                XmNy, 457,
                XmNx, 601,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->add_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_change_button_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 48, "Change"));
    if (instance->change_button == NULL) {
        instance->change_button =
            XtVaCreateWidget("change_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 39,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 21,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 117,
                XmNy, 457,
                XmNx, 701,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->change_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_reset_button_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 7, "Reset"));
    if (instance->reset_button == NULL) {
        instance->reset_button =
            XtVaCreateWidget("reset_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 59,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 41,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 117,
                XmNy, 457,
                XmNx, 801,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->reset_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_cancel_button_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 8, "Cancel"));
    if (instance->cancel_button == NULL) {
        instance->cancel_button =
            XtVaCreateWidget("cancel_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 79,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 61,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 117,
                XmNy, 457,
                XmNx, 901,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->cancel_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_rule_edit_help_button_create(
    DtbRuleEditDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 3, 9, "Help"));
    if (instance->help_button == NULL) {
        instance->help_button =
            XtVaCreateWidget("help_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 98,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 81,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 110,
                XmNy, 457,
                XmNx, 1001,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->help_button == NULL)
        return -1;

    return 0;
}

