/*
 *+SNOTICE
 *
 *	$Revision: 1.2 $
 *
 *	RESTRICTED CONFIDENTIAL INFORMATION:
 *	
 *	The information in this document is subject to special
 *	restrictions in a confidential disclosure agreement between
 *	HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
 *	document outside HP, IBM, Sun, USL, SCO, or Univel without
 *	Sun's specific written approval.  This document and all copies
 *	and derivative works thereof must be returned or destroyed at
 *	Sun's request.
 *
 *	Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
 *
 *+ENOTICE
 */

#ifndef I_HAVE_NO_IDENT
#pragma ident "@(#)StringTab.c	1.37 05/21/96"
#endif

#include <X11/Intrinsic.h>

String ApplicationFallbacks[] = {
"Dtmail*ComposeDialog*menubar*File.mnemonic: F",
"Dtmail*ComposeDialog*menubar*File.Include.mnemonic: I",
"Dtmail*ComposeDialog*menubar*File.Save_As.mnemonic: A",
"Dtmail*ComposeDialog*menubar*File.Save_Outgoing_Mail.mnemonic: M",
"Dtmail*ComposeDialog*menubar*File.Send.mnemonic: S",
"Dtmail*ComposeDialog*menubar*File.Send_As.mnemonic: n",
"Dtmail*ComposeDialog*menubar*File.Close.mnemonic: C",
"Dtmail*ComposeDialog*menubar*Edit.mnemonic: E",
"Dtmail*ComposeDialog*menubar*Edit.Undo.mnemonic: U",
"Dtmail*ComposeDialog*menubar*Edit.Cut.mnemonic: t",
"Dtmail*ComposeDialog*menubar*Edit.Copy.mnemonic: C",
"Dtmail*ComposeDialog*menubar*Edit.Paste.mnemonic: P",
"Dtmail*ComposeDialog*menubar*Paste_Special.mnemonic: l",
"Dtmail*ComposeDialog*menubar*Edit.Clear.mnemonic: e",
"Dtmail*ComposeDialog*menubar*Edit.Delete.mnemonic: D",
"Dtmail*ComposeDialog*menubar*Edit.Select_All.mnemonic: S",
"Dtmail*ComposeDialog*menubar*Edit.Find/Change.mnemonic: F",
"Dtmail*ComposeDialog*menubar*Edit.Check_Spelling.mnemonic: k",
"Dtmail*ComposeDialog*menubar*Attachments.mnemonic: A",
"Dtmail*menubar*Attachments.Add_File.mnemonic: F",
"Dtmail*menubar*Attachments.Save_As.mnemonic: A",
"Dtmail*menubar*Attachments.Delete.mnemonic: D",
"Dtmail*menubar*Attachments.Undelete.mnemonic: U",
"Dtmail*menubar*Attachments.Rename.mnemonic: R",
"Dtmail*menubar*Attachments.Select_All.mnemonic: S",
"Dtmail*menubar*Attachments.Open.mnemonic: O",
"Dtmail*menubar*Attachments.Print.mnemonic: P",
"Dtmail*ComposeDialog*menubar*Format.mnemonic: r",
"Dtmail*ComposeDialog*menubar*Format.Word_Wrap.mnemonic: W",
"Dtmail*ComposeDialog*menubar*Format.Settings.mnemonic: S",
"Dtmail*ComposeDialog*menubar*Format.Use_Template.mnemonic: T",
"Dtmail*ComposeDialog*menubar*Format.Use_Draft.mnemonic: D",
"Dtmail*ComposeDialog*menubar*Format.Include_Signature.mnemonic: I",
"Dtmail*ComposeDialog*menubar*Format.Signature.mnemonic: e",
"Dtmail*ComposeDialog*menubar*Format.Vacation_Message.mnemonic: V",
"Dtmail*ComposeDialog*menubar*Format.Aliases.mnemonic: A",
"Dtmail*ComposeDialog*menubar*Format.Add_Bcc.mnemonic: B",
"Dtmail*menubar*Mailbox.mnemonic: x",
"Dtmail*menubar*Mailbox.Check_for_New_Mail.mnemonic: M",
"Dtmail*menubar*Mailbox.Show_Mailboxes_with_New_Mail.mnemonic: S",
"Dtmail*menubar*Mailbox.Select_All_Messages.mnemonic: A",
"Dtmail*menubar*Mailbox.New_Mailbox.mnemonic: N",
"Dtmail*menubar*Mailbox.Open_Mailbox.mnemonic: O",
"Dtmail*menubar*Mailbox.Destroy_Deleted_Messages.mnemonic: D",
"Dtmail*menubar*Mailbox.Close.mnemonic: C",
"Dtmail*menubar*Message.mnemonic: M",
"Dtmail*menubar*Message*Open.mnemonic: O",
"Dtmail*menubar*Message*Copy_Selected_Text.mnemonic: x",
"Dtmail*menubar*Message*Select_All_Text.mnemonic: T",
"Dtmail*menubar*Save_As_Text.mnemonic: A",
"Dtmail*menubar*Message*Attachments.mnemonic: h",
"Dtmail*menubar*Message*Copy_To_Mailbox.mnemonic: C",
"Dtmail*menubar*Message*Print_One.mnemonic: e",
"Dtmail*menubar*Message*Print.mnemonic: P",
"Dtmail*menubar*Message*Search.mnemonic: S",
"Dtmail*menubar*Message*Undelete_Last.mnemonic: L",
"Dtmail*menubar*Message*Undelete_From_List.mnemonic: U",
"Dtmail*menubar*Compose.mnemonic: C",
"Dtmail*menubar*Compose.New_Message.mnemonic: M",
"Dtmail*menubar*Compose.New__Use_Template.mnemonic: N",
"Dtmail*menubar*Compose.Forward.mnemonic: F",
"Dtmail*menubar*Compose.Forward__no_Attachments.mnemonic: s",
"Dtmail*menubar*Compose.Reply.mnemonic: R",
"Dtmail*menubar*Compose.Reply_to_All.mnemonic: A",
"Dtmail*menubar*Compose.Reply__Include_Message.mnemonic: I",
"Dtmail*menubar*Compose.Reply_to_All__Include_Message.mnemonic: e",
"Dtmail*menubar*Compose.Continue_Composing_Draft.mnemonic: C",
"Dtmail*menubar*View.mnemonic: V",
"Dtmail*menubar*View.Next.mnemonic: N",
"Dtmail*menubar*View.Previous.mnemonic: P",
"Dtmail*menubar*View.Abbreviated_Headers.mnemonic: H",
"Dtmail*menubar*View.By_Date/Time.mnemonic: D",
"Dtmail*menubar*View.By_Sender.mnemonic: S",
"Dtmail*menubar*View.By_Subject.mnemonic: b",
"Dtmail*menubar*View.By_Size.mnemonic: z",
"Dtmail*menubar*View.By_Status.mnemonic: t",
"Dtmail*menubar*Options.mnemonic: O",
"Dtmail*menubar*Options.Basic.mnemonic: B",
"Dtmail*menubar*Options.Aliases.mnemonic: A",
"Dtmail*menubar*Options.Compose_Window.mnemonic: C",
"Dtmail*menubar*Options.Notification.mnemonic: N",
"Dtmail*menubar*Options.Message_View.mnemonic: M",
"Dtmail*menubar*Options.Move_Menu_Setup.mnemonic: p",
"Dtmail*menubar*Options.Signature.mnemonic: S",
"Dtmail*menubar*Options.Templates.mnemonic: T",
"Dtmail*menubar*Options.Toolbar.mnemonic: r",
"Dtmail*menubar*Options.Vacation_Message.mnemonic: V",
"Dtmail*menubar*Options.Advanced.mnemonic: d",
"Dtmail*menubar*Move.mnemonic: e",
"Dtmail*menubar*Move.Inbox.mnemonic: I",
"Dtmail*menubar*Other_Mailboxes.mnemonic: O",
"Dtmail*menubar*Select_Mailbox.mnemonic: S",
"Dtmail*menubar*Help.mnemonic: H",
"Dtmail*menubar*Help.Overview.mnemonic: v",
"Dtmail*menubar*Help.Tasks.mnemonic: T",
"Dtmail*menubar*Help.Reference.mnemonic: R",
"Dtmail*menubar*Help.On_Item.mnemonic: O",
"Dtmail*menubar*Help.Using_Help.mnemonic: U",
"Dtmail*menubar*Help.About_Mailer.mnemonic: A",
"Dtmail*Send.acceleratorText: F3",
"Dtmail*menubar*Send.accelerator: <Key>F3",
"Dtmail*ComposeDialog*menubar*File.Close.accelerator: Alt<Key>F4",
"Dtmail*ComposeDialog*menubar*File.Close.acceleratorText: Alt+F4",
"Dtmail*ComposeDialog*menubar*Edit.Undo.accelerator: Ctrl<Key>Z",
"Dtmail*ComposeDialog*menubar*Edit.Undo.acceleratorText: Ctrl+Z",
"Dtmail*ComposeDialog*menubar*Edit.Cut.accelerator: Ctrl<Key>X",
"Dtmail*ComposeDialog*menubar*Edit.Cut.acceleratorText: Ctrl+X",
"Dtmail*ComposeDialog*menubar*Edit.Copy.accelerator: Ctrl<Key>C",
"Dtmail*ComposeDialog*menubar*Edit.Copy.acceleratorText: Crtl+C",
"Dtmail*ComposeDialog*menubar*Edit.Paste.accelerator: Ctrl<Key>V",
"Dtmail*ComposeDialog*menubar*Edit.Paste.acceleratorText: Crtl+V",
"Dtmail*ComposeDialog*menubar*Edit.Delete.accelerator: Delete",
"Dtmail*ComposeDialog*menubar*Edit.Delete.acceleratorText: Delete",
"Dtmail*ComposeDialog*menubar*Edit.Find/Change.accelerator: Ctrl<Key>F",
"Dtmail*ComposeDialog*menubar*Edit.Find/Change.acceleratorText: Ctrl+F",
"Dtmail*Help.On_Item.accelerator: <Key>F1",
"Dtmail*Help.On_Item.acceleratorText: F1",
"Dtmail*menubar*Mailbox.Check_for_New_Mail.accelerator: Ctrl<Key>M",
"Dtmail*menubar*Mailbox.Check_for_New_Mail.acceleratorText: Ctrl+M",
"Dtmail*menubar*Options.Basic.accelerator: Ctrl<Key>I",
"Dtmail*menubar*Options.Basic.acceleratorText: Ctrl+I",
"Dtmail*menubar*Mailbox.Close.accelerator: Alt<Key>F4",
"Dtmail*menubar*Mailbox.Close.acceleratorText: Alt+F4",
"Dtmail*menubar*Message*Print.accelerator: Ctrl<Key>P",
"Dtmail*menubar*Message*Print.acceleratorText: Ctrl+P",
"Dtmail*menubar*Message*Copy_Selected_Text.accelerator: Ctrl<Key>S",
"Dtmail*menubar*Message*Copy_Selected_Text.acceleratorText: Ctrl+S",
"Dtmail*menubar*Compose.New_Message.accelerator: Ctrl<Key>N",
"Dtmail*menubar*Compose.New_Message.acceleratorText: Ctrl+N",
"Dtmail*menubar*Compose.Reply.accelerator: Ctrl<Key>R",
"Dtmail*menubar*Compose.Reply.acceleratorText: Ctrl+R",
"Dtmail*menubar*Message*Delete.accelerator: Ctrl<Key>D",
"Dtmail*menubar*Message*Delete.acceleratorText: Ctrl+D",
"*Message_View*Work_Area.width: 600",
"*Message_View*Work_Area.height: 400",
"Dtmail*separateViewWindow*Work_Area.width: 600",
"Dtmail*separateViewWindow*Work_Area.height: 400",
"Dtmail*Message_Send*scrollHorizontal:	False",
"Dtmail*Message_Send*wordWrap:		True",
"Dtmail*Message_View*scrollHorizontal:	False",
"Dtmail*Message_View*wordWrap:		True",
"Dtmail*Mail_View*scrollVertical:	True",
"Dtmail*menubar*marginHeight:	1",
"Dtmail*menubar*tearOffModel:	TEAR_OFF_DISABLED",
/*
"Dtmail*menubar*Move.tearOffModel:	TEAR_OFF_ENABLED",
*/
"Dtmail*AttachAreaMenuBar*marginHeight:	1",
"Dtmail*HeaderArea*To*marginHeight:	1",
"Dtmail*HeaderArea*Subject*marginHeight:	1",
"Dtmail*HeaderArea*Cc*marginHeight:	1",
"Dtmail*View*Separator*separatorType: SHADOW_ETCHED_IN",
"Dtmail*Work_Area*Text*columns: 72",
"Dtmail*interval:	5",
"Dtmail*Next:		True",
"Dtmail*Next*default:	True",
"Dtmail*PrintScript: lp -dpubs3 ",
"Dtmail*From*label:	From:",
"Dtmail*Text*label:	Text:",
"Dtmail*Start*default:	True",
"Dtmail*Message_List*scrollBarDisplayPolicy:	STATIC",
"Dtmail*Message_List*visibleItemCount:	15",
"Dtmail*Message_List*width:	600",
"Dtmail*Message_List*listSizePolicy:	VARIABLE",
"Dtmail*Message_List*viewHeight:	7",
"Dtmail*Message_List*doubleClickInterval: 400",
"Dtmail*Message_List*selectionPolicy:      EXTENDED_SELECT",
"Dtmail*Work_Area*Text*editMode:	MULTI_LINE_EDIT",
"Dtmail*find*To.columns: 1",
"Dtmail*find*From.columns: 1",
"Dtmail*find*Subject.columns: 1",
"Dtmail*find*Cc.columns: 1",
"Dtmail*ComposeDialog*HeaderArea*form_*columns: 70",
"Dtmail*ComposeDialog*menubar*File.Save_Outgoing_Mail.indicatorType: XmONE_OF_MANY",
"Dtmail*ComposeDialog*menubar*File.Save_Outgoing_Mail.set: TRUE",
"Dtmail*ComposeDialog*menubar*File.Save_Outgoing_Mail.visibleWhenOff: TRUE",
"Dtmail*ComposeDialog*Text*columns: 72",
"Dtmail*ComposeDialog.iconName: Compose Window",
"Dtmail*menubar*Compose.tearOffModel:	TEAR_OFF_ENABLED",
"Dtmail*ComposeDialog*menubar*Attachments.Show_List.indicatorType: XmONE_OF_MANY",
"Dtmail*ComposeDialog*menubar*Attachments.Show_List.set: TRUE",
"Dtmail*ComposeDialog*menubar*Attachments.Show_List.visibleWhenOff: TRUE",
"Dtmail*ComposeDialog*menubar*Format.Word_Wrap.indicatorType: XmONE_OF_MANY",
"Dtmail*ComposeDialog*menubar*Format.Word_Wrap.set: TRUE",
"Dtmail*ComposeDialog*menubar*Format.Word_Wrap.visibleWhenOff: TRUE",
"Dtmail*menubar*View.Abbreviated_Headers.indicatorType: XmONE_OF_MANY",
"Dtmail*menubar*View.Abbreviated_Headers.set: TRUE",
"Dtmail*menubar*View.Abbreviated_Headers.visibleWhenOff: TRUE",
NULL
};
