
#
#	$Revision: 1.1 $
#
#  @(#)Makefile.old	1.5 01/18/94	cde_app_builder/src/ab
#
# 	RESTRICTED CONFIDENTIAL INFORMATION:
#	
#	The information in this document is subject to special
#	restrictions in a confidential disclosure agreement between
#	HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
#	document outside HP, IBM, Sun, USL, SCO, or Univel without
#	Sun's specific written approval.  This document and all copies
#	and derivative works thereof must be returned or destroyed at
#	Sun's request.
#
#	Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
#
#

PROJECTDIR = ../../..

LIBPART	  =	doc

SOURCES.c = 

SOURCES.h.shipped = 
SOURCES.h.shared= 
SOURCES.h.unshared= 

SOURCES.h = \
		$(SOURCES.h.shipped)	\
		$(SOURCES.h.shared)	\
		$(SOURCES.h.unshared)

SOURCES.uil = 

SOURCES.xres = 

SOURCES.misc = 

IMAGES = 

#PROGRAM = ab
PROGRAM =

CPPFLAGS        +=  -I$(MOTIFHOME)/include -I$(OPENWINHOME)/include

LDFLAGS		+=  -L$(MOTIFHOME)/lib

ULIBS		+= 

X_LIBS		= -lXm -lDtWidget -lDtTerm -lDtHelp -lDtSvc -lXpm -lUil -lMrm -lbento -lXt -lX11 -lnsl
LDLIBS		= $(X_LIBS) -lgen -lC -lm

.PARALLEL: $(PROGRAM)
.INIT:  $(PROJECTDIR)/Makefile.include
include $(PROJECTDIR)/Makefile.include
