
#
#	$Revision: 1.1 $
#
#  @(#)Makefile	3.18 20 Oct 1993	cde_app_builder/src
#
# 	RESTRICTED CONFIDENTIAL INFORMATION:
#	
#	The information in this document is subject to special
#	restrictions in a confidential disclosure agreement between
#	HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
#	document outside HP, IBM, Sun, USL, SCO, or Univel without
#	Sun's specific written approval.  This document and all copies
#	and derivative works thereof must be returned or destroyed at
#	Sun's request.
#
#	Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
#
#

#
# Add demo and doc later
#

PROJECTDIR = ../..

DIRS =		\
	help

# inst Put back in later.

TARGETS = all clean install scour sources targets

.KEEP_STATE:
.NO_PARALLEL:

# This is done as a for loop to force pmake to do them sequentially
$(TARGETS):
	@if [ $@ = clean ] || [ $@ = scour ] ; then			\
		$(RM) core .make.depend* .make*lock ;			\
	fi ;								\
	if [ $@ = scour ] ; then					\
		$(RM) -rf core .make* include/ab/* include/ab_private/* ; \
	fi ; 								\
	for DIR in $(DIRS) ; do						\
		$(MAKE) $$DIR TARGET=$@ ;				\
	done

$(DIRS):: FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:

