$ *****************************************************************************
$ **
$ **  File:        dtconfig.msg
$ **
$ **  Project:     CDE Session Management (dtconfig)
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtconfig
$ **
$ **
$ *****************************************************************************

$set 10
1 can only be run by the super user. \n
$
2 The CDE environment is now set as the default user interface. This\n\
interface will appear on login for all users of the system.\n\
To see this change take effect you must shutdown and restart your system.\n
$
3 The Command line is now set as the default user interface. This\n\
interface will appear on login for all users of the system.\n\
To see this change take effect you must shutdown and restart your system.\n
4 The CDE environment is Already set as the default User Interface.\n
$
5 The Command line is already set as the default User Interface.\n
$
6 usage: %s\n\
  -e (enable auto-start of dtlogin)\n\
  -d (disable auto-start of dtlogin)\n\
  -kill (kill dtlogin)\n\
  -reset (reset dtlogin - reread configuration files)\n
$
7 Too many arguments \n
$
8  Needs one argument \n
$
9  Could not disable xdm, Please refer to xdm man pages to disable\n\
xdm and try again. \n 
$
10 Dtlogin is not running \n
