# $XConsortium: todis1.sed,v 1.1 91/02/16 09:51:44 rws Exp $
#  Copyright (c) 1990 by Sun Microsystems, Inc.
#  A Sed script for converting to the PHIGS DIS C binding 
#
# Par_st
s/PARCL/PST_ARCL/g
s/PAROP/PST_AROP/g
# Pasf
s/PBUNDLED/PASF_BUNDLED/g
s/PINDIVIDUAL/PASF_INDIV/g
# Paspect
s/PLINETYPE/PASPECT_LINETYPE/g
s/PLINEWIDTH_SCALE_FACTOR/PASPECT_LINEWIDTH/g
s/PPOLYLINE_COLOUR_INDEX/PASPECT_LINE_COLR_IND/g
s/PMARKERTYPE/PASPECT_MARKERTYPE/g
s/PMARKERSIZE_SCALE_FACTOR/PASPECT_MARKERSIZE/g
s/PPOLYMARKER_COLOUR_INDEX/PASPECT_MARKER_COLR_IND/g
s/PTEXT_FONT/PASPECT_TEXT_FONT/g
s/PTEXT_PRECISION/PASPECT_TEXT_PREC/g
s/PCHARACTER_EXPANSION_FACTOR/PASPECT_CHAR_EXPAN/g
s/PCHARACTER_SPACING/PASPECT_CHAR_SPACE/g
s/PTEXT_COLOUR_INDEX/PASPECT_TEXT_COLR_IND/g
s/PINTERIOR_STYLE_INDEX/PASPECT_INT_STYLE_IND/g
s/PINTERIOR_STYLE/PASPECT_INT_STYLE/g
s/PINTERIOR_COLOUR_INDEX/PASPECT_INT_COLR_IND/g
s/PEDGE_FLAG/PASPECT_EDGE_FLAG/g
s/PEDGETYPE/PASPECT_EDGETYPE/g
s/PEDGEWIDTH_SCALE_FACTOR/PASPECT_EDGEWIDTH/g
s/PEDGE_COLOUR_INDEX/PASPECT_EDGE_COLR_IND/g
s/PPOLYLINE_SHADING_METHOD/PASPECT_LINE_SHAD_METH/g
s/PINTERIOR_SHADING_METHOD/PASPECT_INT_SHAD_METH/g
s/PAREA_PROPERTIES/PASPECT_REFL_PROPS/g
s/PINTERIOR_REFLECTANCE_EQUATION/PASPECT_INT_REFL_EQN/g
s/PBACK_INTERIOR_STYLE_INDEX/PASPECT_BACK_INT_STYLE_IND/g
s/PBACK_INTERIOR_STYLE/PASPECT_BACK_INT_STYLE/g
s/PBACK_INTERIOR_COLOUR/PASPECT_BACK_INT_COLR/g
s/PBACK_INTERIOR_SHADING_METHOD/PASPECT_BACK_INT_SHAD_METH/g
s/PBACK_AREA_PROPERTIES/PASPECT_BACK_REFL_PROPS/g
s/PBACK_INTERIOR_REFLECTANCE_EQUATION/PASPECT_BACK_INT_REFL_EQN/g
s/PCURVE_APPROXIMATION_CRITERIA/PASPECT_CURVE_APPROX_CRIT/g
s/PSURFACE_APPROXIMATION_CRITERIA/PASPECT_SURF_APPROX_CRIT/g
# Pattrs
s/PPOLYLINE/PATTR_LINE/g
s/PPOLYMARKER/PATTR_MARKER/g
s/PTEXT/PATTR_TEXT/g
s/PINTERIOR/PATTR_INT/g
s/PEDGE[^_]/PATTR_EDGE/g
# Pclip_ind
s/PCLIP/PIND_CLIP/g
s/PNOCLIP/PIND_NO_CLIP/g
# Pcolr_avail;
s/PCOLOUR/PAVAIL_COLR/g
s/PMONOCHROME/PAVAIL_MONOCHR/g
# Pcompose_type;
s/PPRECONCATENATE/PTYPE_PRECONCAT/g
s/PPOSTCONCATENATE/PTYPE_POSTCONCAT/g
s/PREPLACE/PTYPE_REPLACE/g
# Pconf_res;
s/PMAINTAIN/PRES_MAINTAIN/g
s/PABANDON/PRES_ABANDON/g
s/PUPDATE/PRES_UPD/g
# Pctrl_flag;
s/PCONDITIONALLY/PFLAG_COND/g
s/PALWAYS/PFLAG_ALWAYS/g
# Pdc_units;
s/PDC_METERS/PDC_METRES/g
# Pdefer_mode;
s/PASAP/PDEFER_ASAP/g
s/PBNIG/PDEFER_BNIG/g
s/PBNIL/PDEFER_BNIL/g
s/PASTI/PDEFER_ASTI/g
s/PWAIT/PDEFER_WAIT/g
# Pdisp_empty;
s/Pdisp_empty/Pdisp_surf_empty/g
s/PSURF_NOTEMPTY/PSURF_NOT_EMPTY/g
# Pdyn_mod;
s/PIRG/PDYN_IRG/g
s/PIMM/PDYN_IMM/g
s/PCBS/PDYN_CBS/g
# Pecho;
s/Pecho/Pecho_switch/g
s/PES_ECHO/PSWITCH_ECHO/g
s/PES_NOECHO/PSWITCH_NO_ECHO/g

# Pelem_type;
s/PEL_NIL/PELEM_NIL/g
s/PEL_POLYLINE3/PELEM_POLYLINE3/g
s/PEL_POLYLINE/PELEM_POLYLINE/g
s/PEL_POLYMARKER3/PELEM_POLYMARKER3/g
s/PEL_POLYMARKER/PELEM_POLYMARKER/g
s/PEL_TEXT3/PELEM_TEXT3/g
s/PEL_TEXT/PELEM_TEXT/g
s/PEL_ANNO_TEXT_REL3/PELEM_ANNO_TEXT_REL3/g
s/PEL_ANNO_TEXT_REL/PELEM_ANNO_TEXT_REL/g
s/PEL_FILL_AREA3/PELEM_FILL_AREA3/g
s/PEL_FILL_AREA/PELEM_FILL_AREA/g
s/PEL_FILL_AREA_SET3/PELEM_FILL_AREA_SET3/g
s/PEL_FILL_AREA_SET/PELEM_FILL_AREA_SET/g
s/PEL_CELL_ARRAY3/PELEM_CELL_ARRAY3/g
s/PEL_CELL_ARRAY/PELEM_CELL_ARRAY/g
s/PEL_GDP3/PELEM_GDP3/g
s/PEL_GDP/PELEM_GDP/g
s/PEL_LINE_IND/PELEM_LINE_IND/g
s/PEL_MARKER_IND/PELEM_MARKER_IND/g
s/PEL_TEXT_IND/PELEM_TEXT_IND/g
s/PEL_INT_IND/PELEM_INT_IND/g
s/PEL_EDGE_IND/PELEM_EDGE_IND/g
s/PEL_LINETYPE/PELEM_LINETYPE/g
s/PEL_LINEWIDTH_SCALE/PELEM_LINEWIDTH/g
s/PEL_LINE_COLR_IND/PELEM_LINE_COLR_IND/g
s/PEL_MARKER_TYPE/PELEM_MARKER_TYPE/g
s/PEL_MARKER_SIZE_SCALE/PELEM_MARKER_SIZE/g
s/PEL_MARKER_COLR_IND/PELEM_MARKER_COLR_IND/g
s/PEL_TEXT_FONT/PELEM_TEXT_FONT/g
s/PEL_TEXT_PREC/PELEM_TEXT_PREC/g
s/PEL_CHAR_EXPAN/PELEM_CHAR_EXPAN/g
s/PEL_CHAR_SPACE/PELEM_CHAR_SPACE/g
s/PEL_TEXT_COLR_IND/PELEM_TEXT_COLR_IND/g
s/PEL_CHAR_HT/PELEM_CHAR_HT/g
s/PEL_CHAR_UP_VEC/PELEM_CHAR_UP_VEC/g
s/PEL_TEXT_PATH/PELEM_TEXT_PATH/g
s/PEL_TEXT_ALIGN/PELEM_TEXT_ALIGN/g
s/PEL_ANNO_CHAR_HT/PELEM_ANNO_CHAR_HT/g
s/PEL_ANNO_CHAR_UP_VEC/PELEM_ANNO_CHAR_UP_VEC/g
s/PEL_ANNO_PATH/PELEM_ANNO_PATH/g
s/PEL_ANNO_ALIGN/PELEM_ANNO_ALIGN/g
s/PEL_ANNO_STYLE/PELEM_ANNO_STYLE/g
s/PEL_INT_STYLE_IND/PELEM_INT_STYLE_IND/g
s/PEL_INT_STYLE/PELEM_INT_STYLE/g
s/PEL_INT_COLR_IND/PELEM_INT_COLR_IND/g
s/PEL_EDGE_FLAG/PELEM_EDGE_FLAG/g
s/PEL_EDGETYPE/PELEM_EDGETYPE/g
s/PEL_EDGEWIDTH_SCALE/PELEM_EDGEWIDTH/g
s/PEL_EDGE_COLR_IND/PELEM_EDGE_COLR_IND/g
s/PEL_PAT_SIZE/PELEM_PAT_SIZE/g
s/PEL_PAT_REF_POINT_VECS/PELEM_PAT_REF_POINT_VECS/g
s/PEL_PAT_REF_POINT/PELEM_PAT_REF_POINT/g
s/PEL_ADD_NAMES_SET/PELEM_ADD_NAMES_SET/g
s/PEL_REMOVE_NAMES_SET/PELEM_REMOVE_NAMES_SET/g
s/PEL_INDIV_ASF/PELEM_INDIV_ASF/g
s/PEL_HLHSR_ID/PELEM_HLHSR_ID/g
s/PEL_LOCAL_MODEL_TRAN3/PELEM_LOCAL_MODEL_TRAN3/g
s/PEL_LOCAL_MODEL_TRAN/PELEM_LOCAL_MODEL_TRAN/g
s/PEL_GLOBAL_MODEL_TRAN3/PELEM_GLOBAL_MODEL_TRAN3/g
s/PEL_GLOBAL_MODEL_TRAN/PELEM_GLOBAL_MODEL_TRAN/g
s/PEL_MODEL_CLIP_VOL3/PELEM_MODEL_CLIP_VOL3/g
s/PEL_MODEL_CLIP_VOL/PELEM_MODEL_CLIP_VOL/g
s/PEL_MODEL_CLIP_IND/PELEM_MODEL_CLIP_IND/g
s/PEL_RESTORE_MODEL_CLIP_VOL/PELEM_RESTORE_MODEL_CLIP_VOL/g
s/PEL_VIEW_IND/PELEM_VIEW_IND/g
s/PEL_EXECUTE_STRUCT/PELEM_EXEC_STRUCT/g
s/PEL_LABEL/PELEM_LABEL/g
s/PEL_APPL_DATA/PELEM_APPL_DATA/g
s/PEL_GSE/PELEM_GSE/g
s/PEL_PICK_ID/PELEM_PICK_ID/g
s/PEL_ALL/PELEM_ALL/g
s/PEL_POLYLINE_SET3_DATA/PELEM_POLYLINE_SET3_DATA/g
s/PEL_FILL_AREA_SET3_DATA/PELEM_FILL_AREA_SET3_DATA/g
s/PEL_TRIANGLE_STRIP3_DATA/PELEM_TRI_STRIP3_DATA/g
s/PEL_QUADRILATERAL_MESH3_DATA/PELEM_QUAD_MESH3_DATA/g
s/PEL_SET_OF_FILL_AREA_SET3_DATA/PELEM_SET_OF_FILL_AREA_SET3_DATA/g
s/PEL_NON_UNIFORM_B_SPLINE_CURVE/PELEM_NUNI_BSP_CURVE/g
s/PEL_NON_UNIFORM_B_SPLINE_SURFACE/PELEM_NUNI_BSP_SURF/g
s/PEL_EXTENDED_CELL_ARRAY3/PELEM_CELL_ARRAY3_PLUS/g
s/PEL_TEXT_COLR/PELEM_TEXT_COLR/g
s/PEL_MARKER_COLR/PELEM_MARKER_COLR/g
s/PEL_EDGE_COLR/PELEM_EDGE_COLR/g
s/PEL_LINE_COLR/PELEM_LINE_COLR/g
s/PEL_CURVE_APPROX_CRITERIA/PELEM_CURVE_APPROX_CRIT/g
s/PEL_LINE_SHADING_METHOD/PELEM_LINE_SHAD_METH/g
s/PEL_INT_COLR/PELEM_INT_COLR/g
s/PEL_BACK_INT_COLR/PELEM_BACK_INT_COLR/g
s/PEL_BACK_INT_STYLE_IND/PELEM_BACK_INT_STYLE_IND/g
s/PEL_BACK_INT_STYLE/PELEM_BACK_INT_STYLE/g
s/PEL_AREA_PROPERTIES/PELEM_REFL_PROPS/g
s/PEL_BACK_AREA_PROPERTIES/PELEM_BACK_REFL_PROPS/g
s/PEL_INT_SHADING_METHOD/PELEM_INT_SHAD_METH/g
s/PEL_BACK_INT_SHADING_METHOD/PELEM_BACK_INT_SHAD_METH/g
s/PEL_INT_REFLECTANCE_EQUATION/PELEM_INT_REFL_EQN/g
s/PEL_BACK_INT_REFLECTANCE_EQUATION/PELEM_BACK_INT_REFL_EQN/g
s/PEL_SURFACE_APPROX_CRITERIA/PELEM_SURF_APPROX_CRIT/g
s/PEL_PARA_SURF_CHARACTERISTICS/PELEM_PARA_SURF_CHARACS/g
s/PEL_FACE_DISTINGUISHING_MODE/PELEM_FACE_DISTING_MODE/g
s/PEL_FACE_CULLING_MODE/PELEM_FACE_CULL_MODE/g
s/PEL_LIGHT_SOURCE_STATE/PELEM_LIGHT_SRC_STATE/g
s/PEL_DEPTH_CUE_IND/PELEM_DCUE_IND/g
s/PEL_COLR_MAP_IND/PELEM_COLR_MAP_IND/g
s/PEL_RENDERING_COLR_MODEL/PELEM_RENDERING_COLR_MODEL/g
s/PEL_NUM_EL_TYPES/PELEM_NUM_EL_TYPES/g
# Perr_mode;
s/PERROR_OFF/PERR_OFF/g
s/PERROR_ON/PERR_ON/g
# Phor_align;
s/PHOR_NORMAL/PHOR_NORM/g
s/PHOR_CENTRE/PHOR_CTR/g
