.TH tt_error_int 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_error_int" "" "tt_error_int(3)" ""
.SH NAME
tt_error_int \- return an integer error object that encodes the code
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'int tt_error_int('u
int tt_error_int(Tt_status \f2ttrc\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_error_int (\|)
function
returns an integer error object that encodes a
.B Tt_status
return value, which is within
the range of TT_OK == 0 <= ttrc < TT_STATUS_LAST.
.PP
The
.I ttrc
argument is the
.B Tt_status
code that is to be encoded.
.SH "RETURN VALUE"
Upon successful completion, the
.BR tt_error_int (\|)
function returns the encoded
.B Tt_status
code.
.SH "APPLICATION USAGE"
The integer error objects are negative integers;
an application should use this call only when
the valid integer values are non-negative.
.SH "SEE ALSO"
.na
.BR tt_c (5).
