.TH tt_int_error 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_int_error" "" "tt_int_error(3)" ""
.SH NAME
tt_int_error \- return the status of an error object
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'Tt_status tt_int_error('u
Tt_status tt_int_error(int \f2return_val\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_int_error (\|)
function returns the status of an error object.
.PP
The
.I return_val
argument is the integer returned by a ToolTalk function.
.SH "RETURN VALUE"
Upon successful completion, the
.BR tt_int_error (\|)
function returns either
.BR \s-1TT_OK\s+1 ,
if the integer is not an
error object, or the encoded
.B Tt_status
value if the integer is an error object.
.SH "SEE ALSO"
.na
.BR tt_c (5),
.BR tt_int_error (3).
