.de Lc
.\" version of .LI that emboldens its argument
.TP \\n()Jn
\s-1\f3\\$1\f1\s+1
..
.TH tt_message_status 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_message_status" "" "tt_message_status(3)" ""
.SH NAME
tt_message_status \- retrieve the status attribute from a message
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'int tt_message_status('u
int tt_message_status(Tt_message \f2m\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_message_status (\|)
function
retrieves the status attribute from the specified message.
.PP
The
.I m
argument is the opaque handle for the message involved in this operation.
.SH "RETURN VALUE"
Upon successful completion, the
.BR tt_message_status (\|)
function returns an integer that describes the status
stored in the status attribute of this message.
The application can use
.BR tt_int_error (3)
to extract one of the following
.B Tt_status
values from the returned integer:
.PP
.RS 3
.nr )J 8
.Lc TT_OK
The operation completed successfully.
.Lc TT_ERR_NOMP
.br
The
.BR ttsession (1)
process is not running and the ToolTalk service cannot restart it.
.Lc TT_ERR_POINTER
.br
The pointer passed does not point to an object of
the correct type for this operation.
.PP
.RE
.nr )J 0
.SH "SEE ALSO"
.na
.BR tt_c (5),
.BR tt_message_status_string (3),
.BR tt_int_error (3).
