.de Lc
.\" version of .LI that emboldens its argument
.TP \\n()Jn
\s-1\f3\\$1\f1\s+1
..
.TH tt_message_handler 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_message_handler" "" "tt_message_handler(3)" ""
.SH NAME
tt_message_handler \- retrieve the handler attribute from a message
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'char *tt_message_handler('u
char *tt_message_handler(Tt_message \f2m\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_message_handler (\|)
function
retrieves the handler attribute from the specified message.
.PP
The
.I m
argument is the opaque handle for the message involved in this operation.
.SH "RETURN VALUE"
Upon successful completion, the
.BR tt_message_handler (\|)
function returns the character value that uniquely identifies the
process that is to handle the message
.RB ( Tt_state =
.BR \s-1TT_CREATED\s+1
or
.BR \s-1TT_SENT\s+1 )
or the process that
did handle the message
.RB ( Tt_state
=
.BR \s-1TT_SENT\s+1
or
.BR \s-1TT_HANDLED\s+1 ).
The application can use
.BR tt_ptr_error (3)
to extract one of the following
.B Tt_status
values from the returned pointer:
.PP
.RS 3
.nr )J 8
.Lc TT_OK
The operation completed successfully.
.Lc TT_ERR_NOMP
.br
The
.BR ttsession (1)
process is not running and the ToolTalk service cannot restart it.
.Lc TT_ERR_POINTER
.br
The pointer passed does not point to an object of
the correct type for this operation.
.PP
.RE
.nr )J 0
.SH "APPLICATION USAGE"
The application should use
.BR tt_free (3)
to free any data stored in the address returned by the
ToolTalk API.
.SH "SEE ALSO"
.na
.BR tt_c (5),
.BR tt_ptr_error (3),
.BR tt_free (3).
