.de Lc
.\" version of .LI that emboldens its argument
.TP \\n()Jn
\s-1\f3\\$1\f1\s+1
..
.TH tt_pattern_print 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_pattern_print.3" "" "tt_pattern_print.3" "" 
.SH NAME
tt_pattern_print \- format a pattern
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'char *tt_pattern_print('u
char *tt_pattern_print(Tt_pattern \f2p\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_pattern_print (\|)
function formats a pattern in the same way a message
is formatted for the
.BR ttsession (1)
trace and returns a string containing it.
.PP
The
.I p
argument is the pattern to be formatted.
.SH "RETURN VALUE"
Upon successful completion, the
.BR tt_pattern_print (\|)
function returns the formatted string.
The application can use
.BR tt_ptr_error (3)
to extract one of the following
.B Tt_status
values from the returned pointer:
.PP
.RS 3
.nr )J 8
.Lc TT_OK
The operation completed successfully.
.br
.Lc TT_ERR_NOMEM
.br
There is insufficient memory available to perform the function.
.br
.Lc TT_ERR_POINTER
.br
The pointer passed does not point to an object of
the correct type for this operation.
.PP
.RE
.nr )J 0
.SH "APPLICATION USAGE"
The
.BR tt_pattern_print (\|)
function allows an application writer to dump out patterns
for debugging.
.SH "SEE ALSO"
.na
.BR tt_c (5),
.BR tt_ptr_error (3).
