.TH tt_release 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_release.3" "" "tt_release.3" "" 
.SH NAME
tt_release \- free storage allocated on the ToolTalk API allocation stack
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'void tt_release('u
void tt_release(int \f2mark\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_release (\|)
function
frees all storage allocated on the ToolTalk API allocation stack
since
.I mark
was returned by
.BR tt_mark (3).
.PP
The
.I mark
argument is an
integer that marks the application's storage position in the ToolTalk API
allocation stack.
.SH "APPLICATION USAGE"
This function frees all storage allocated since the
.BR tt_mark (3)
call that returned
.I mark
and is typically called at the end of a procedure to release all
storage allocated within the procedure.
.SH "SEE ALSO"
.na
.BR tt_c (5),
.BR tt_mark (3).
