.de LI
.\" simulate -mm .LIs by turning them into .TPs
.TP \\n()Jn
\\$1
..
.TH tt_trace_control 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tt_trace_control.3" "" "tt_trace_control.3" "" 
.SH NAME
tt_trace_control \- control client-side tracing
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tt_c.h>
.sp 0.5v
.ta \w'int tt_trace_control('u
int tt_trace_control(int \f2onoff\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tt_trace_control (\|)
function
sets or clears an internal flag controlling all client-side tracing.
The intent of this is to be called from debugger breakpoints,
allowing a programmer to narrow the trace to the suspect area.
.PP
The value of the
.I onoff
argument affects tracing as follows:
.PP
.RS 3
.nr )J 4
.LI \00
Tracing is turned off.
.LI \01
Tracing is turned on.
.LI \(mi1
Tracing is turned on if it was off and vice-versa.
.PP
.RE
.nr )J 0
.SH "RETURN VALUE"
The
.BR tt_trace_control (\|)
function returns the previous setting of the trace flag.
.SH "APPLICATION USAGE"
This call does not return one of the
.BR TT_xxx
type of errors or warnings, but only the numbers 1 or zero.
.SH "SEE ALSO"
.na
.BR tt_c (5),
.BR ttsession (1).
