.TH tttk_op_string 3 "1 March 1996" "ToolTalk 1.3" "ToolTalk Functions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "tttk_op_string.3" "" "tttk_op_string.3" "" 
.SH NAME
tttk_op_string \- map a ToolTalk op code to a string
.SH SYNOPSIS
.ft 3
.nf
#include <Tt/tttk.h>
.sp 0.5v
.ta \w'char *tttk_op_string('u
char *tttk_op_string(Tttk_op \f2opcode\fP);
.PP
.fi
.SH DESCRIPTION
The
.BR tttk_op_string (\|)
function
returns a string containing the op for
.IR opcode .
.SH "RETURN VALUE"
Upon successful completion, the
.BR tttk_op_string (\|)
function returns a string that can be freed using
.BR tt_free (3);
otherwise, it returns
.BR \s-1NULL\s+1 .
.SH "APPLICATION USAGE"
The distinctions in the
.B Tttk_op
enumerated type are for programmer convenience, and elements of
.B Tttk_op
do not necessarily map one-to-one with op strings, since ToolTalk
allows ops to be overloaded.
For example,
.BR \s-1TTME_EDIT\s+1
and
.BR \s-1TTME_COMPOSE\s+1
are overloaded on the same op
.RI ( Edit ),
and the messages
only vary by the
.B Tt_mode
of the first argument.
.SH "SEE ALSO"
.na
.BR tttk (5),
.BR tt_message_op (3),
.BR tt_free (3).
