/* XPM */
static char * MVIctrSubPnl_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"58 40 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	c #272735354747",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor2	m white	c white",
"#	s iconColor1	m black	c black",
/* pixels */
"                                                          ",
"                       ........                           ",
"                     ..XXXXXXXX..                         ",
"                   ..XX        XX..                       ",
"                  .XX            XX.                      ",
"                 .X                X.                     ",
"  o oooooooooooo.Xooooooooooooooooooo.Xooooooooooooooo o  ",
" o oooooooooooo.Xooooooooooooooooooooo.Xooooooooooooooo   ",
"  XXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXX  ",
"   XXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXX X ",
" XXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXX X  ",
"    XXXXXXXXX.XXXXXXXXXXXXO+XXXXXXXXXXXX.XXXXXXXXXXXXXX   ",
"  XXXXXXXXXXX.XXXXXXXXXXXO@O+XXXXXXXXXXX.XXXXXXXXXXXXXXX  ",
" X XXXXXXXXXX.XXXXXXXXXXO@++O+XXXXXXXXXX.XXXXXXXXXXXXXX X ",
"  X XXXXXXXXX.XXXXXXXXXO@++++O+XXXXXXXXX.XXXXXXXXXXXXX X  ",
"    XXXXXXXXX.XXXXXXXXO@++++++O+XXXXXXXX.XXXXXXXXXXXXX X  ",
"  XXXXXXXXXXX.XXXXXXXOOOOOOOOOO+XXXXXXXX.XXXXXXXXXXXXXX   ",
" X  XXXXXXXXX.XXXXXXXO++++++++++XXXXXXXX.XXXXXXXXXXXXX  X ",
"  XXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXX  ",
"    XXXXXXXXXX.XXXXXXXXXXXXXXX@XXXXXXXX.XXXXXXXXXXXXXXX   ",
" X XXXXXXXXXXX.XXXXXXXXXXXXXXX@@XXXXXXX.XXXXXXXXXXXXXX X  ",
"  XX XXX XXXX X.XXX XXXXXXX XX@#@XXXXX.XXXXXXXXXXXXX XX   ",
"   X X XXXX XXX.XX X XXXX XXX @##@XXXX.XXX XX XX X XX  X  ",
"  X X   X X X X . X    X X    @###@XX.X XX  X XX XXX      ",
" X       X    X  .X   X    X  @####@ X X X    X   X  X    ",
"                  .           @#####@ X                   ",
"                  X..         @######@                    ",
"                   XX..       @#######@                   ",
"                     XX...... @########@                  ",
"                       XXXXXX @#####@@@@                  ",
"                              @##@##@                     ",
"                              @#@ @##@                    ",
"                              @@  @##@                    ",
"                                   @##@                   ",
"                                   @##@                   ",
"                                    @@                    ",
"                                                          ",
"                                                          ",
"                                                          ",
"                                                          "};
