/* XPM */
static char * VImseClick [] = {
/* width height ncolors cpp [x_hot y_hot] */
"110 75 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor3	m black	c red",
"X    s iconGray7     m black c #424242424242",
"o    s iconGray3     m white c #adadadadadad",
"O    s iconGray2     m white c #bdbdbdbdbdbd",
"+    s iconGray1     m white c #dededededede",
"@	s iconColor1	m black	c black",
/* pixels */
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              ",
"                  .                                                                                           ",
"                  .                                                                                           ",
"                 ...                                                                                          ",
"                 ...                                                                                          ",
"                 ...                                                                                          ",
"                .....                                                                                         ",
"      .         .....                                                                                         ",
"     ...        .....                                                                                         ",
"     ....      .......                                                                                        ",
"      ...      ........                                                                                       ",
"      ....     .....                                                                                          ",
"       ...    .  ...                                                                                          ",
"       ..        ...                                                                                          ",
"          .                                                                                                   ",
"         ...     ...                                                                                          ",
"         ....    ...                                                                                          ",
"          ...    ...                                                                                          ",
"          ....   ...                                                                                          ",
"           ...   ...                     XXXXXXXXX                                                            ",
"            .  . ...                XXXXXoooooooooXXX                                                         ",
"              .. ...          XXXXXXXXoooooooooooooooXXX                                                      ",
"             .......   XXXXXXXooooooooXXooooooooooooooooXXX                                                   ",
"              ......XXXXoooooooooooooooooXXooooooooooooXXXOXXX         XXXXXXXXXX                             ",
"          XXXXX..oooooooXXooooooooooooooooooXXooooXXXXOOOOOOOOXXX XXXXXOOOOOOOOOOXXXXX                        ",
"       XXXXooooo....oooooooXXooooooooooooooooXXXXOOOOOOOOOOOOOOXXXOOOOOOOOOOOOOOOOOOOOXXX                     ",
"      XXXoooooooo...oooooooooXXooooooooooXXXOOOOOOOOOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOOOOOOOOXX                   ",
"      XooXXooooooo.oooooooooooooXXoXXXXOOOOOOOOOOOOOOOOOOOOXOOOOOO+OOOOOOOOOOOOOOOOOOOOOOOOXX                 ",
"      XooooXXXoooooooooooooooooXXXXOOOOOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXX               ",
"      XoooooooXXooooooooooXXXOOOOOOOOOOOOOOOOOOOOOOOOOOXOOOOO+O+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX              ",
"       XooooooooXXooooXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOXOOOOO+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX             ",
"      XOO@ooooooooXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXOOOO+OOOOOOOOOOOOOOOO+OOOOOOOOOOOOOOOOOOOOOX            ",
"      XO@@O@ooooooXOXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXOOOOOO+OOOOOOOOOO+OOOOOOOOOOOOOOOOOOOOOOOOOOOX           ",
"      XOOOO@O@ooooXOOO@@OOOOOOOOOOOOOOOOOOOOOOOOOOOXOOOO+O+OOOOOOOO+OOO+O+OOO+OOOOOOOOOOOOOOOOOOOOOX          ",
"      XOOOOOO@O@ooXOOOOO@@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O+OOOOOOOOO+OOOO++OOOOOOOOOOOOOOOOOOOO+OOOOX         ",
"      XOOOOOOOO@OXXOOOOOOOO@@OOOOOOOOOOOOOOOOOOOOOXOOO+++OOOOOOOOOOO+OO+OOOOOO+OOOOOOOOOOOOOOOOO+OOOX         ",
"      XXOOOOOOOOOXO@@OOOOOOOO@@@OOOOOOOOOOOOOOOOOXOOO+O+OOOOOOOOO++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OOOX        ",
"        XXOOOOOOOOO@O@@OOOOOOOOO@@OOOOOOOOOOOOOOOXOOO++O+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO++OOX        ",
"          XXOOOOOOOOO@O@@OOOOOOOOO@@OOOOOOOOOOOOOOOOOOO++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX       ",
"            XXOOOOOOOOO@OO@OOOOOOOOO@@OOOOOOOOOOXOO+O+O+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO++OOX       ",
"              XXOOOOOOOOO@OO@OOOOOOOOO@@@OOOOOOOXOOOO+++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O+OOOX      ",
"                XXOOOOOOOOO@@O@OOOOOOOOOO@@OOOOOXOOOO+O+O+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO++++OOX      ",
"                  XXOOOOOOOOO@OO@OOOOOOOOOO@@OOOOXOOO+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO++OOOOXX      ",
"                    XXOOOOOOOOO@OO@OOOOOOOOOO@@OOXOOOOOO+O+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO++++OOOXX      ",
"                      XXOOOOOOOOO@@O@OOOOOOOOOO@@OXOOOOOOOOO++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O+OOOOO@OX      ",
"                        XXOOOOOOOOOO@O@OOOOOOOOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OOOOOOOOXOOX      ",
"                          XXOOOOOOOOOO@O@OOOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXOOOX      ",
"                            XXOOOOOOOOOO@O@@OOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXOOOOOX      ",
"                              XXOOOOOOOOOO@O@@OOOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXOOOOOOOX      ",
"                                XXOOOOOOOOOO@O@@OOOOOOOOOOOOXXOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXOOOOOOOOOXX      ",
"                                  XXOOOOOOOOOO@O@@OOOOOOOOOOOOOXXXXXXOOOOOOOOOOOOOOXXXXXOOOOOOOOOOOOOXOX      ",
"                                    XXOOOOOOOOOO@OO@OOOOOOOOOOOOOOOOOOOXXXXXXXXXOOOOOOOOOOOOOOOOOOOOXOOX      ",
"                                      XXOOOOOOOOOO@OO@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXOOX      ",
"                                        XXOOOOOOOOOO@@O@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXOOOX      ",
"                                          XXOOOOOOOOOO@OO@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXOXOOOOOX      ",
"                                            XXOOOOOOOOOO@@OXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXOXXOOOOOOOX      ",
"                                              XXOOOOOOOOOOOXXOOXXXXOOOOOOOOOOOOOOOOOOXXXXOOXXOOOOOOOOO@       ",
"                                                XXOOOOOOOOOOOOOXXXOOOOOXOXXOXXXOXXOOOXXXXOOOOOOOOOOOO@        ",
"                                                  XXOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXOOOOOOOOOOOOOOOOOO@         ",
"                                                    XXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@          ",
"                                                      XXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@X            ",
"                                                        @@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@@               ",
"                                                           @@@@OOOOOOOOOOOOOOOOOOOOOOOOO@@@@                  ",
"                                                               @@@@@@OOOOOOOOOOOOO@@@@@@                      ",
"                                                                     @@@@@@@@@@@@@                            ",
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              ",
"                                                                                                              "};
