#!/bin/sh
sccs edit audio_control_stubs.c
sccs edit audio_control.bil
sccs edit audio_control_ui.c audio_control_ui.h
sccs edit dtb_utils.c dtb_utils.h
sccs edit sdtactrl.msg sdtactrl.bip
sccs edit sdtactrl.c sdtactrl.h
