/* XPM */
static char * unitylogo [] = {
/* width height ncolors cpp [x_hot y_hot] */
"110 37 6 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s foreground	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconColor1	m black	c black",
"O	s iconColor3	m black	c red",
"+    s iconGray8     m black c #212121212121",
/* pixels */
"                                                                                                    ..........",
"                                                                                                    ..........",
"                                                                                                    ..........",
"                                                                                                    ..........",
"                             .                                                                      ..........",
"                             ...                                                                    ..........",
"           XXXXXXXXXXXXXXXXX...XXXXXXXXXXXXXXXXX          ooo    ooo  ooooooooo ..............................",
"          XXXXXXXXXXXXXXXXXX...XXXXXXXXXXXXXXXXXX         ooo    ooo .oooooooooo..............................",
"         XXXXXXXXXXXXXXX ..... .   XXXXXXXXXXXXXXX        ooo    ooo .ooo    ooo..............................",
"         XXXXXXXXXXXXX   ....        XXXXXXXXXXXXX        ooo    ooo .ooo    ooo..............................",
"         XXXXXXXXXXXX    ....         XXXXXXXXXXXX        oooooooooo .ooo    ooo..............................",
"         XXXXXXXXXXX   . ....   . .    XXXXXXXXXXX        oooooooooo .oooooooooo..............................",
"         XXXXXXXXXXX   ......   .OOOO   XXXXXXXXXX        ooo    ooo .ooooooooo ..............................",
"         XXXXXXXXXX  .........  OOOOOO  XXXXXXXXXX        ooo    ooo .ooo       ..............................",
"         XXXXXXXXXX ..OOOOO...  OOOOOO   XXXXXXXXX        ooo    ooo .ooo       ..............................",
"         XXXXXXXXXX .OOOOOOO..  OOOOOO.  XXXXXXXXX        ooo    ooo  ooo       ..............................",
"         XXXXXXXXX  OOOOOOOOO...OOOOOO..  XXXXXXXX                                                  ..........",
"         XXXXXXXXX OOOOOOOOOOO...OOOO...  XXXXXXXX                                                  ..........",
"         XXXXXXXXX OOOOOOOOOOO..........  XXXXXXXX                                                  ..........",
"         XXXXXXXXXOOOOO....OOOO...  .. .OOXXXXXXXX                                                  ..........",
"         XXXXXXXXXOOOO......OOO........OOOXXXXXXXX      ......................................................",
"         XXXXXXXXXXOOO......OOO........OOXXXXXXXXX      ..+++++++++..++++++++++...+++.......+++...............",
"         XXXXXXXXXXOOO......OOOO......OOOXXXXXXXXX      ..+++++++++..+++++++++++..++++.....++++...............",
"         XXXXXXXXXXOOO......OOOOO....OOOXXXXXXXXXX      .....+++.....+++.....+++..+++++...+++++...............",
"         XXXXXXXXXXXOOO....OOOOOOOOOOOOOXXXXXXXXXX      .....+++.....+++.....+++..++++++.++++++...............",
"         XXXXXXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXXXX      .....+++.....+++++++++++..+++.+++++.+++...............",
"         XXXXXXXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXXXX      .....+++.....++++++++++...+++..+++..+++...............",
"         XXXXXXXXXXXXXXOOOOOOOOOOOOOOXXXXXXXXXXXXX      .....+++.....+++.....+++..+++.......+++...............",
"         XXXXXXXXXXXXXXXOOOOOOOOOOOXXXXXXXXXXXXXXX      .....+++.....+++.....+++..+++.......+++...............",
"          XXXXXXXXXXXXXXXXXXOOOXXXXXXXXXXXXXXXXXX       ..+++++++++..+++++++++++..+++.......+++...............",
"           XXXXXXXXXXXXXXXXX...XXXXXXXXXXXXXXXXX        ..+++++++++..++++++++++...+++.......+++...............",
"                           ....                                    .                                ..........",
"                              .                                    .                                ..........",
"                                                                   .                                ..........",
"                                                                   .                                ..........",
"                                                                                                    ..........",
"                                                                                                    .........."};
