#!/bin/sh
######################################################################
#
#     Xreset
#
#     Common Desktop Environment (CDE)
#
#     (c) Copyright 1993 Hewlett-Packard Company
#     (c) Copyright 1993 International Business Machines Corp.
#     (c) Copyright 1993 Sun Microsystems, Inc.
#
#     $Revision: 1.5 $
#
######################################################################

#
# This script is run as root after the session terminates but
# before the display is closed...
#
