#!/bin/sh
######################################################################
#
#     Xstartup
#
#     Common Desktop Environment (CDE)
#
#     (c) Copyright 1993 Hewlett-Packard Company
#     (c) Copyright 1993 International Business Machines Corp.
#     (c) Copyright 1993 Sun Microsystems, Inc.
#     
#     $Revision: 1.6 $
#
######################################################################

#
# This script is run as root after the user is verified...
#

#
# Sun platform has a fallback console which logs messages to a
# "/tmp/wscon..." file if a system console is not run on the desktop.  
# Start this fallback console if present on system.
#

if [ -x /usr/openwin/bin/fbconsole ]; then
     /usr/openwin/bin/fbconsole &
fi

