.TH dtenvvar 5 "7 July 1994"
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.SH NAME
dtenvvar \- CDE environment variables
.SH DESCRIPTION
.\"---
.\"--- The _1st_index_term_ and _2nd_index_term_ will appear in the manual
.\"--- index.  _format_of_1st_ and _format_of_2nd_ specify formatting for
.\"--- these index entries.
.\"---
The CDE desktop sets up and uses a number of environment variables to find
certain files and do certain things.
Components tied into CDE then use 
these environment variables to locate specific types of files.
Environment 
variables used within the CDE desktop are:
.SS  CEPATH
Used by ToolTalk when in Classing Engine mode, where the Classing
Engine where to find the databases.
Refer to \fBttsession(1)\fP and \fBtt_type_comp(1)\fP for more information.
.SS  COLUMNS
Set by the terminal emulator.
Refer to \fBdtterm(1)\fP for more information.
.SS  DISPLAY
Is set to the associated display name.
Refer to \fBdtlogin(1)\fP and \fBttsession(1)\fP for more information.
.SS DTAPPSEARCHPATH 
Used to search for Application Manager applications. Refer
to \fBdtappgather(1)\fP and \fBdtsearchpath(1)\fP for more
information.
.SS DTDATABASESEARCHPATH
Used to collect filetype and action definitions, as expressed in
\f(CW*.dt\fR files.  Refer to \fBdtsearchpath(1)\fP,
\fBdtaction(1)\fP, \fBdtactionfile(4)\fP, and \fBdtdtsfile(4)\fP for 
more information.
.SS DTHELPSEARCHPATH 
System specified variable used to locate desktop help files.
Refer to \fBdtsearchpath(1)\fP and \fBdthelpgen(1)\fP for more information.
.SS DTHELPUSERSEARCHPATH 
User specified variable used to locate desktop help files.
Refer to \fBdtsearchpath(1)\fP and \fBdthelpgen(1)\fP for more information.
.SS DTMOUNTPOINT 
Used to set the name of the file system's mount point, such as '/nfs'
or '/net'.  Refer to \fBdtspcd(1)\fP and \fBdtsearchpath(1)\fP for more
information.
.SS DTPRINTCWD
If set to an existing, usable directory, then this setting
causes \fBdtlp\fP to execute the \fBlp\fP
command pipeline from that
directory.  By default, uses the current directory
from which \fBdtlp\fB is invoked.
Refer to \fBdtlp(1)\fP for more information.
.SS DTPRINTFILEREMOVE
Remove the file after printing it.
This functionality is intended for temporary files generated by
components such as the Text Editor and Help system\(emfiles that
don't need to persist beyond the act of printing.
Value must be \f(CWTrue\fR
or \f(CWFalse\fR (case is ignored).
Default is \f(CWFalse\fR.
Refer to \fBdtlp(1)\fP for more information.
.SS DTPRINTSILENT
Print the file silently, without posting the PRINT dialog.
Value must be \f(CWTrue\fR
or \f(CWFalse\fR (case is ignored).
Default is \f(CWFalse\fR.
Refer to \fBdtlp(1)\fP for more information.
.SS DTPRINTUSERFILENAME
Use this value as the name of file as it should appear in the
PRINT dialog.
Default is print_file.
Refer to \fBdtlp(1)\fP for more information.
.SS DTSCREENSAVERLIST  
Used to set the default desktop screen saver 
action list.  Used by \fBdtstyle\fP to determine the list
of available screen savers.
Refer to \fBdtstyle(1)\fP for more information.
.SS DTSPSYSAPPHOSTS
Used by system administrators as an input to \fBdtsearchpath\fP to
create the DTAPPSEARCHPATH environment variable. It is the primary
environment variable and drives the remaining search paths for
filetypes and actions, for desktop icons, and for help files.  Refer
to \fBdtappgather(1)\fP and \fBdtsearchpath(1)\fP for more
information.
.SS DTSPSYSDATABASEHOSTS
Used by system administrators as an input to \fBdtsearchpath\fP to
create the DTDATABASESEARCHPATH environment variable. Refer to
\fBdtsearchpath(1)\fP for more information.
.SS DTSPSYSHELP
Used by system administrators as an input to \fBdtsearchpath\fP to
create the DTHELPSEARCHPATH environment variable. Refer to
\fBdtsearchpath(1)\fP for more information.
.SS DTSPSYSICON
Used by system administrators as an input to \fBdtsearchpath\fP to
create the XMICONSEARCHPATH and XMICONBMSEARCHPATH environment
variables. Refer to \fBdtsearchpath(1)\fP for
more information.
.SS DTSPUSERAPPHOSTS
Used by end users as an input to \fBdtsearchpath\fP to
create the DTAPPSEARCHPATH environment variable. Refer to
\fBdtappgather(1)\fP and \fBdtsearchpath(1)\fP for more information.
.SS DTSPUSERDATABASEHOSTS
Used by end users as an input to \fBdtsearchpath\fP to
create the DTDATABASESEARCHPATH environment variable. Refer to
\fBdtsearchpath(1)\fP for more information.
.SS DTSPUSERHELP
Used by end users as an input to \fBdtsearchpath\fP to
create the DTHELPSEARCHPATH environment variable. Refer to
\fBdtsearchpath(1)\fP for more information.
.SS DTSPUSERICON
Used by end users as an input to \fBdtsearchpath\fP to create the
XMICONSEARCHPATH and XMICONBMSEARCHPATH environment variables. Refer
to \fBdtsearchpath(1)\fP for more information.
.SS DTTAGOPT
Used by dthelptag.  Refer
to \fBdthelptag(1)\fP for more information.
.SS DTUSERSESSION 
Used to control the location of the end user's subdirectory where the
Application Manager will be rooted.  Also used by the Help system to
store data on a per user-session-display basis. Refer to
\fBdtappgather(1)\fP or \fBdthelpview(1)\fP for more information.
.SS  EDITOR
Is set to
.B /usr/dt/bin/dtpad
Refer to \fBdtlogin(1)\fP for more information.
.SS  HOME
Is set to the home directory of the user.
Refer to \fBdtlogin(1)\fP and \fBdtmail(1)\fP for more information.
.SS  KBD_LANG
Is set to the value of LANG for applicable languages.
Refer to \fBdtlogin(1)\fP for more information.
.SS  LANG
Is set to the current NLS language (if any).
Refer to \fBdtlogin(1)\fP for more information.
.SS  LC_ALL
Is set to the current NLS language (if any).
Refer to \fBdtlogin(1)\fP for more information.
.SS  LC_MESSAGES
Is set to the current NLS language (if any).
Refer to \fBdtlogin(1)\fP for more information.
.SS  LINES
Set by the terminal emulator.
Refer to \fBdtterm(1)\fP for more information.
.SS  LOGNAME
Is set to the user name.
Refer to \fBdtlogin(1)\fP for more information.
.SS LPDEST
Set the printer destination for the file.
Refer to \fBdtlp(1)\fP for more information.
.SS  MAIL
Is set to
.B /usr/mail/$USER
(system dependent).
Refer to \fBdtlogin(1)\fP for more information.
.SS  MAILRC
Used by the dtmail as the mailer's startup file.
Refer to \fBdtmail(1)\fP for more information.
.SS  MANPATH
\fPdtsearchpath\P appends \fB/usr/dt/man\fP to it.
Refer to \fBdtsearchpath(1)\fP for more information.
.SS  NLSPATH
Determine the location of message catalogues for the processing of
.IR LC_MESSAGES .
Refer to \fBdtterm(1)\fP for more information.
.SS  PATH
Is set to the value of the userPath resource.
Refer to \fBdtlogin(1)\fP for more information.
.SS  SHELL
Is set to the user's default shell (from
.BR /etc/passwd ).
Refer to \fBdtlogin(1)\fP and \fBdtterm(1)\fP for more information.
.SS  TERM
Is set to
.B dtterm
the default CDE terminal emulator.
Refer to \fBdtterm(1)\fP and \fBdtlogin(1)\fP for more information.
.SS  TERMINAL_EMULATOR
Set by the terminal emulator.
Refer to \fBdtterm(1)\fP for more information.
.SS  TTPATH
Used by ToolTalk.  It tells ToolTalk where to find the ToolTalk
types database when in XDR mode.
Refer to \fBttsession(1)\fP for more information.
.SS  TTSESSION_CMD
This specifies the shell command to be used by all ToolTalk clients
for auto-starting \fBttsession\fP.
Refer to \fBttsession(1)\fP for more information.
.SS  TT_ARG_TRACE_WIDTH
Used by ToolTalk.  It specifies the number of bytes of argument
and context values to write when in trace mode.
Refer to \fBttsession(1)\fP for more information.
.SS  TT_FILE
Set by ttsession when it invokes a tool to recieve a message.
Refer to \fBttsession(1)\fP for more information.
.SS  TT_SESSION
\fBttsession\fP uses this varible to communicate its session ID
to the tools that it starts.
Refer to \fBttsession(1)\fP for more information.
.SS  TT_TOKEN
Used to inform the ToolTalk client library that it has been invoked
by \fBttsession\fP.
Refer to \fBttsession(1)\fP for more information.
.SS  TT_TRACE_SCRIPT
If set, tells libtt to turn on client-side tracing as specified in the
trace script
Refer to \fBttrace(1)\fP for more information.
.SS  TZ
Is set to the value of the
.B timeZone
resource or system default.
Refer to \fBdtlogin(1)\fP for more information.
.SS  USER
Is set to the user name.
Refer to \fBdtlogin(1)\fP for more information.
.SS  WINDOWID
Set by the terminal emulator.
Refer to \fBdtterm(1)\fP for more information.
.SS  XAPPLRESDIR
Specifies the name of a directory that contains application
specific resources.
Refer to \fBdtterm(1)\fP and \fBdtwm(1)\fP for more information.
.SS  XAUTHORITY
May be set to an authority file.
Refer to \fBdtlogin(1)\fP for more information.
.SS  XENVIRONMENT
Specifies the name of a resource file with user- or machine
specific resources.
Refer to \fBdtterm(1)\fP and \fBdtwm(1)\fP for more information.
.SS  XFILESEARCHPATH
Defines a language-dependent location of app-defaults.
Refer to \fBdtterm(1)\fP and \fBdtwm(1)\fP for more information.
.SS  XMICONSEARCHPATH  
Used to locate desktop icons.
Refer to \fBdtsearchpath(1)\fP for more information.
.SS  XMICONBMSEARCHPATH 
Used to locate bitmap (2 color) desktop icons.
Refer to \fBdtsearchpath(1)\fP for more information.
.SS  XMODIFIER
Specifies which input method to use.
Refer to \fBdtterm(1)\fP for more information.
.PP
.PP
.SH "SEE ALSO"
.BR dtaction (1)
.BR dtactionfile (4)
.BR dtappgather (1)
.BR dtappintegrate (1)
.BR dtcm (1)
.BR dthelpgen (1)
.BR dthelptag (1)
.BR dthelpview (1)
.BR dtlogin (1)
.BR dtlp (1)
.BR dtsearchpath (1)
.BR dtspcd (1)
.BR dtstyle (1)
.BR dtterm (1)
.BR dtdtsfile (4)
.BR dtwm (1)
.BR tt_type_comp (1)
.BR ttsession (1)
.BR tttrace (1)
