/*
 * File: sdt_firstlogin_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module sdt_firstlogin
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _SDT_FIRSTLOGIN_UI_H_
#define _SDT_FIRSTLOGIN_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct {
    Widget	Item1_item;
} SdtFirstloginRadioboxItemsRec, *SdtFirstloginRadioboxItems;
typedef struct {
    Widget	Item1_item;
} SdtFirstloginRadioboxChoiceItemsRec, *SdtFirstloginRadioboxChoiceItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	mainwindow;	/* object "mainwindow" */
    Widget	mainwindow_mainwin;
    Widget	mainwindow_form;
    
    Widget	controlpane2;
    Widget	separator;
    Widget	label2;
    
    Widget	radiobox_rowcolumn;	/* object "radiobox" */
    Widget	radiobox_label;
    Widget	radiobox;
    SdtFirstloginRadioboxItemsRec	radiobox_items;
    
    Widget	label3;
    Widget	separator2;
    Widget	button;
    Widget	button2;
} DtbSdtFirstloginMainwindowInfoRec, *DtbSdtFirstloginMainwindowInfo;


extern DtbSdtFirstloginMainwindowInfoRec dtb_sdt_firstlogin_mainwindow;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbSdtFirstloginMainwindowInfo_clear(DtbSdtFirstloginMainwindowInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_sdt_firstlogin_mainwindow_initialize(
    DtbSdtFirstloginMainwindowInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */
void FL_Select_OK_Button(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void FL_Create_Choices(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void FL_Create_OK_Button(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void FL_Main_Window_Created(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);

/*
 * Connections
 */
void sdt_firstlogin_button2_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _SDT_FIRSTLOGIN_UI_H_ */
