/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: sdt_firstlogin.c
 * Contains: main() and cross-module connections
 *
 * This file was generated by dtcodegen, from project sdt_firstlogin
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <X11/Intrinsic.h>
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/Protocols.h>
#include <Dt/Help.h>
#include <Dt/HelpQuickD.h>
#include <Dt/HelpDialog.h>
#include <nl_types.h>
#include "sdt_firstlogin_ui.h"
#include "sdt_firstlogin.h"
#include "dtb_utils.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/

#include <Dt/EnvControl.h>

/*
 * Application Resources
 */
static XtResource resources[] = {
    {"session", "Session", XtRString, sizeof(String),
         XtOffsetOf(DtbAppResourceRec, session_file), 
	 XtRImmediate, (XtPointer)NULL}
    ,{ "labelFont", "LabelFont", XmRFontList, sizeof(XmFontList), 
	XtOffsetOf(DtbAppResourceRec, label_font),
        XmRString, "-dt-interface system-medium-r-normal-m*-*-*-*-*-*-*-*-*:" }
    ,{"infile", "Infile", XtRString, sizeof(String),
       XtOffsetOf(DtbAppResourceRec, in_file), XtRImmediate, (XtPointer)NULL}
    ,{"outfile", "Outfile", XtRString, sizeof(String),
       XtOffsetOf(DtbAppResourceRec, out_file), XtRImmediate, (XtPointer)NULL}
};



/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



/* Workaround for XPG4 API compatibility */
#if !defined(NL_CAT_LOCALE)
#define NL_CAT_LOCALE 0
#endif

/* Handle for standard message catalog for the project */
nl_catd	Dtb_project_catd = (nl_catd)-1;

/*
 * command line options...
 */
static XrmOptionDescRec optionDescList[] = {
    {"-session", "*session", XrmoptionSepArg, (XPointer)NULL}
    
    /*** DTB_USER_CODE_START vvv Add structure fields below vvv ***/
    ,{"-infile", "infile", XrmoptionSepArg, (XPointer)NULL}
    ,{"-outfile", "outfile", XrmoptionSepArg, (XPointer)NULL}
    /*** DTB_USER_CODE_END   ^^^ Add structure fields above ^^^ ***/
};

DtbAppResourceRec	dtb_app_resource_rec;


/*
 * main for application sdt_firstlogin
 */
int 
main(
    int argc,
    char **argv
)
{
    Widget		toplevel = (Widget)NULL;
    XtAppContext	app = (XtAppContext)NULL;
    String		*fallback_resources = (String*)NULL;
    ArgList		init_args = (ArgList)NULL;
    Cardinal		num_init_args = (Cardinal)0;
    ArgList		get_resources_args = (ArgList)NULL;
    Cardinal		num_get_resources_args = (Cardinal)0;
    XtLanguageProc	language_proc = (XtLanguageProc)NULL;
    XtPointer		language_proc_client_data = (XtPointer)NULL;
    
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***  No initialization has been done.
     ***
     *** Add local variables and code.
     ***/

    /*
     * Set up NLSPATH, app-defaults, etc. environment for this DT client.
     */

    _DtEnvControl(DT_ENV_SET);


    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /* NULL language_proc installs the default Xt language procedure */
    XtSetLanguageProc((XtAppContext)NULL,
        language_proc, language_proc_client_data);
    
    toplevel = XtAppInitialize(&app, "Sdt_firstlogin",
        optionDescList, XtNumber(optionDescList),
        &argc, argv, fallback_resources,
        init_args, num_init_args);

    /*
     * Get display and verify initialization was successful.
     */
    if (toplevel == NULL)
    {
        fprintf(stderr, "Could not open display.\n");
        exit(1);
    }
    
    /*
     * Open the standard message catalog for the project.
     */
    Dtb_project_catd = catopen(DTB_PROJECT_CATALOG, NL_CAT_LOCALE);
    if (Dtb_project_catd == (nl_catd)-1)
    {
        fprintf(stderr, "WARNING: Could not open message catalog: %s. Messages will be defaults.\n",
            DTB_PROJECT_CATALOG);
    }
    
    /*
     * Save the toplevel widget so it can be fetched later as needed.
     */
    dtb_save_toplevel_widget(toplevel);
    
    /*
     * Save the command used to invoke the application.
     */
    dtb_save_command(argv[0]);
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      A connection to the X server has been established, and all
     *** initialization has been done.
     ***
     ***  Add extra initialization code after this comment.
     ***/

    XtGetApplicationResources(toplevel, (XtPointer)&dtb_app_resource_rec,
    resources, XtNumber(resources),
    get_resources_args, num_get_resources_args);


    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /*
     * Initialize all global variables.
     */
    dtbSdtFirstloginMainwindowInfo_clear(&dtb_sdt_firstlogin_mainwindow);
    
    /*
     * Set up the application's root (primary) window.
     */
    dtb_sdt_firstlogin_mainwindow.mainwindow = toplevel;
    XtVaSetValues(dtb_sdt_firstlogin_mainwindow.mainwindow,
        XmNallowShellResize, True,
        XmNtitle, catgets(Dtb_project_catd, 2, 1, "First Login"),
        XmNinitialState, NormalState,
        XmNbackground, dtb_cvt_string_to_pixel(dtb_sdt_firstlogin_mainwindow.mainwindow, "Black"),
        NULL);
    
    dtb_sdt_firstlogin_mainwindow_initialize(&(dtb_sdt_firstlogin_mainwindow), dtb_get_toplevel_widget());
    
    
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      All initially-mapped widgets have been created, but not
     *** realized. Set resources on widgets, or perform other operations
     *** that must be completed before the toplevel widget is
     *** realized.
     ***/

    XtVaSetValues(dtb_sdt_firstlogin_mainwindow.label2, 
	      	XmNfontList, dtb_app_resource_rec.label_font,
		NULL);

    XtVaSetValues(dtb_sdt_firstlogin_mainwindow.label3, 
	      	XmNfontList, dtb_app_resource_rec.label_font,
		NULL);

    XtVaSetValues(dtb_sdt_firstlogin_mainwindow.radiobox_label, 
	      	XmNfontList, dtb_app_resource_rec.label_font,
		NULL);

    XtVaSetValues(dtb_sdt_firstlogin_mainwindow.button, 
	      	XmNfontList, dtb_app_resource_rec.label_font,
		NULL);

    XtVaSetValues(dtb_sdt_firstlogin_mainwindow.button2, 
	      	XmNfontList, dtb_app_resource_rec.label_font,
		NULL);

    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    XtRealizeWidget(toplevel);

    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      All automatic initialization is complete. Add any additional
     *** code that should be executed before the Xt main loop is entered.
     ***/
    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /*
     * Enter event loop
     */
    XtAppMainLoop(app);
    return 0;
}


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


