.\"----------------------------------------------------------------------------
.\" **
.\" **
.\" ** (c) Copyright 1994 Hewlett-Packard Company
.\" ** (c) Copyright 1994 International Business Machines Corp.
.\" ** (c) Copyright 1994 Sun Microsystems, Inc.
.\" ** (c) Copyright 1994 Unix Systems Labs, Inc., a subsidiary of Novell, Inc.
.\" **
.\" **
.\" **
.\"----------------------------------------------------------------------------
.TH dtsdldtd 4 "11 Jan 1994"
.BH "11 Jan 1994"
.\"----------------------------------------------------------------------------
.\"--- NAME
.SH NAME
dtsdldtd \- Semantic Delivery Language (SDL) format and semantics.
.\"--- --------------------------------------------------------
.\"--- DESCRIPTION 
.SH DESCRIPTION
.LP
Note: Currently the content for this manpage is present in the form of 
a frame document ../doc/cde1/spec/oli/sdl.mif.  It needs to be moved
over into this man page for XOpen consumption.

.sp 1
.\"----------------------------------------------------------------------------
.\"--- SEE ALSO
.\"---
.SH "SEE ALSO"
.BR DtCreateHelpDialog (3),
.BR DtCreateQuickHelpDialog (3)
