/*                                                                      *
 * (c) Copyright 1993, 1994 Hewlett-Packard Company                     *
 * (c) Copyright 1993, 1994 International Business Machines Corp.       *
 * (c) Copyright 1993, 1994 Sun Microsystems, Inc.                      *
 * (c) Copyright 1993, 1994 Novell, Inc.                                *
 */

#ifndef _DTRLPSTAT_H
#define _DTRLPSTAT_H

#include "dtlpstat.h"
#include <rpc/rpc.h>            /* always need this */
#include "lpstat.h"             /* need this too: will be generated by rpcgen*/

#ifdef __cplusplus
extern "C" {
#endif

#ifdef NO_SPERROR
extern char RemoteLpstatErrorString[];
#else
extern char *RemoteLpstatErrorString;
#endif

#ifdef __cplusplus
extern int GetRemotePrintJobs(char *server, char *printer,
			      StatusLineList *return_job_list,
	                      int *return_n_jobs);
#else
extern int GetRemotePrintJobs();
#endif

extern int FreeRemotePrintJobs();

#ifdef __cplusplus
}  /* Close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _DTRLPSTAT_H */
