.\" @ (#) Intro.6
.\" Introduction section for ToolTalk 1.3 Reference Manual
.TH Intro 6 "1 March 1996" "ToolTalk 1.3" "ToolTalk  Demos"
.BH "1 March 1996"
.\" (c) Copyright 1996 Sun Microsystems, Inc.
.IX "ToolTalk Demos" "" "ToolTalk Demos" ""
.SH NAME
Intro \- Tooltalk Demos
.SH OVERVIEW
This section describes available ToolTalk demo programs.
Currently there is only one very simple demo program. Programmers
in search of more examples are encouraged  to use \fBtttrace(1)\fR
to trace actual ToolTalk client programs and see how they use
the ToolTalk API to do what they do.
