.TH ttsample1 6 "1 March 1996" "ToolTalk 1.3" "ToolTalk Demos" 
.BH "1 March 1996"
.IX "broadcast" "" "broadcast.6" ""
.SH "NAME"
ttsample1, broadcast \- demonstrate simple use of ToolTalk
.SH SYNOPSIS
.ft 3
.nf
broadcast
.ft 3
.nf
.SH DESCRIPTION
.PP
The
.BR broadcast 
utility
is provided as demo code for the ToolTalk product.  This
program is compiled by copying the files in 
the directory /usr/dt/share/examples/tt
to a convenient spot and invoking the
.BR make (1)
utility.
This will pop up an application
with a single button, slider, and a scale reflecting the value
last received.
By starting several instances of the application, setting the slider
in each to a different value, and pushing the button in each instance,
the effect of broadcasting the value can be seen.
The 
.BR ttsnoop (1)
and
.BR tttrace (1)
utilities can be used to monitor the contents of the ToolTalk messages sent by
.BR broadcast. 
.SH "SEE ALSO"
.na
.BR ttsnoop (1)
.BR tttrace (1)
.BR ttsession (1)
.SH DIAGNOSTICS
If you try and invoke broadcast (or any ToolTalk application)
and you get a message saying the application could not start
ToolTalk, or ttsession, make sure that you have one of the
environment variables DISPLAY or TT_SESSION set, and that
ttsession is in your PATH, or that the TTSESSION_CMD environment
variable indicates where the ttsession program resides. For
more information on ttsession and the environment variables it
uses, see the ttsession man page.
