.TH DTCONVERTVF 1
.\" *************************************************************************
.\" **  (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" **  (c) Copyright 1993, 1994 International Business Machines Corp.
.\" **  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" **  (c) Copyright 1993, 1994 Novell, Inc.
.\" *************************************************************************
.SH NAME
\fBdtconvertvf \(em Convert VUE 3.0 action/filetype files to DT syntax. \fP
.sp 1
.SH SYNOPSIS
.B dtconvertvf 
.nf
.in 10
.fi
.sp 1
.SH DESCRIPTION
Dtconvertvf is a filter script for converting VUE 3.0 action and filetype
databases to the new CDE 1.0 datatypes syntax.  If the input is a VUE 3.0
filetype file (*.vf) then its output will be converted to a CDE 1.0 datatypes
file.  It is up to the user to name the output file accordingly.  To be
recognized by CDE 1.0 it must have the, \fB.dt\fP, suffix.
.sp 1
.SH EXAMPLE
To convert a single action/filetype file to CDE 1.0 syntax:
.in 10
.sp 1
dtconvertvf < file.vf > file.dt
.sp 1
.in -10
.P
To convert all action/filetype files in current directory to CDE 1.0 syntax:
.ds
.nf
.in 10
.sp 1
for vffile in *.vf; do
	dtfile=${vffile%.vf}.dt
	dtconvertvf < $vffile > $dtfile
done
.sp 1
.in -10
.de
.SH COPYRIGHT
.P
Copyright 1993 Hewlett-Packard Company
.sp 1
.SH ORIGIN
Hewlett-Packard Company
