.de LI
.\" simulate -mm .LIs by turning them into .TPs
.TP \\n()Jn
\\$1
..
.TH tttk 5 "1 March 1996" "ToolTalk 1.3" "ToolTalk Definitions"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "Tt/tttk.h" "" "Tt/tttk.h \(em ToolTalk definitions" ""
.SH "NAME"
tttk, Tttttk \- ToolTalk definitions
.SH "SYNOPSIS"
.ft 3
.nf
#include <Tt/tttk.h>
.PP
.fi
.SH "DESCRIPTION"
.PP
The
.BR <Tt/tttk.h> 
header defines the following enumeration data type,
with at least the following members:
.PP
.RS 3
.nr )J 6
.na
.LI \f3Tttk_op\fP
.br
.BR \s-1TTDT_CREATED\s+1 ,
.BR \s-1TTDT_DELETED\s+1 ,
.BR \s-1TTDT_DO_COMMAND\s+1 ,
.BR \s-1TTDT_GET_ENVIRONMENT\s+1 ,
.BR \s-1TTDT_GET_GEOMETRY\s+1 ,
.BR \s-1TTDT_GET_ICONIFIED\s+1 ,
.BR \s-1TTDT_GET_LOCALE\s+1 ,
.BR \s-1TTDT_GET_MAPPED\s+1 ,
.BR \s-1TTDT_GET_MODIFIED\s+1 ,
.BR \s-1TTDT_GET_SITUATION\s+1 ,
.BR \s-1TTDT_GET_STATUS\s+1 ,
.BR \s-1TTDT_GET_SYSINFO\s+1 ,
.BR \s-1TTDT_GET_XINFO\s+1 ,
.BR \s-1TTDT_LOWER\s+1 ,
.BR \s-1TTDT_MODIFIED\s+1 ,
.BR \s-1TTDT_MOVED\s+1 ,
.BR \s-1TTDT_OP_LAST\s+1 ,
.BR \s-1TTDT_OP_NONE\s+1 ,
.BR \s-1TTDT_PAUSE\s+1 ,
.BR \s-1TTDT_QUIT\s+1 ,
.BR \s-1TTDT_RAISE\s+1 ,
.BR \s-1TTDT_RESUME\s+1 ,
.BR \s-1TTDT_REVERT\s+1 ,
.BR \s-1TTDT_REVERTED\s+1 ,
.BR \s-1TTDT_SAVE\s+1 ,
.BR \s-1TTDT_SAVED\s+1 ,
.BR \s-1TTDT_SET_ENVIRONMENT\s+1 ,
.BR \s-1TTDT_SET_GEOMETRY\s+1 ,
.BR \s-1TTDT_SET_ICONIFIED\s+1 ,
.BR \s-1TTDT_SET_LOCALE\s+1 ,
.BR \s-1TTDT_SET_MAPPED\s+1 ,
.BR \s-1TTDT_SET_SITUATION\s+1 ,
.BR \s-1TTDT_SET_XINFO\s+1 ,
.BR \s-1TTDT_SIGNAL\s+1 ,
.BR \s-1TTDT_STARTED\s+1 ,
.BR \s-1TTDT_STATUS\s+1 ,
.BR \s-1TTDT_STOPPED\s+1 ,
.BR \s-1TTME_ABSTRACT\s+1 ,
.BR \s-1TTME_COMPOSE\s+1 ,
.BR \s-1TTME_DEPOSIT\s+1 ,
.BR \s-1TTME_DISPLAY\s+1 ,
.BR \s-1TTME_EDIT\s+1 ,
.BR \s-1TTME_INTERPRET\s+1 ,
.BR \s-1TTME_MAIL\s+1 ,
.BR \s-1TTME_MAIL_COMPOSE\s+1 ,
.BR \s-1TTME_MAIL_EDIT\s+1 ,
.BR \s-1TTME_PRINT\s+1 ,
.BR \s-1TTME_TRANSLATE\s+1
.PP
.RE
.nr )J 0
.PP
.ad
The header declares the following global
string constants for some standard vtypes:
.PP
.ft 3
.nf
extern const char  *Tttk_boolean:
extern const char  *Tttk_file:
extern const char  *Tttk_height:
extern const char  *Tttk_integer:
extern const char  *Tttk_message_id:
extern const char  *Tttk_string:
extern const char  *Tttk_title:
extern const char  *Tttk_width:
extern const char  *Tttk_xoffset:
extern const char  *Tttk_yoffset:
.PP
.fi
.PP
The header declares the following as functions:
.PP
.ft 3
.nf
.ta \w'int ttdt_Get_Modified('u
int ttdt_Get_Modified(Tt_message \f2context\fP,
	const char *\f2pathname\fP,
	Tt_scope \f2the_scope\fP,
	XtAppContext \f2app2run\fP,
	int \f2ms_timeout\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_Revert('u
Tt_status ttdt_Revert(Tt_message \f2context\fP,
	const char *\f2pathname\fP,
	Tt_scope \f2the_scope\fP,
	XtAppContext \f2app2run\fP,
	int \f2ms_timeout\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_Save('u
Tt_status ttdt_Save(Tt_message \f2context\fP,
	const char *\f2pathname\fP,
	Tt_scope \f2the_scope\fP,
	XtAppContext \f2app2run\fP,
	int \f2ms_timeout\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_close('u
Tt_status ttdt_close(const char *\f2procid\fP,
	const char *\f2new_procid\fP,
	int \f2sendStopped\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_file_event('u
Tt_status ttdt_file_event(Tt_message \f2context\fP,
	Tttk_op \f2event\fP,
	Tt_pattern *\f2patterns\fP,
	int \f2send\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_pattern *ttdt_file_join('u
Tt_pattern *ttdt_file_join(const char *\f2pathname\fP,
	Tt_scope \f2the_scope\fP,
	int \f2join\fP,
	Ttdt_file_cb \f2cb\fP,
	void *\f2clientdata\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_message ttdt_file_notice('u
Tt_message ttdt_file_notice(Tt_message \f2context\fP,
	Tttk_op \f2op\fP,
	Tt_scope \f2scope\fP,
	const char *\f2pathname\fP,
	int \f2send_and_destroy\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_file_quit('u
Tt_status ttdt_file_quit(Tt_pattern *\f2patterns\fP,
	int \f2quit\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_message ttdt_file_request('u
Tt_message ttdt_file_request(Tt_message \f2context\fP,
	Tttk_op \f2op\fP,
	Tt_scope \f2scope\fP,
	const char *\f2pathname\fP,
	Ttdt_file_cb \f2cb\fP,
	void *\f2client_data\fP,
	int \f2send_and_destroy\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_pattern *ttdt_message_accept('u
Tt_pattern *ttdt_message_accept(Tt_message \f2contract\fP,
	Ttdt_contract_cb \f2cb\fP,
	void *\f2clientdata\fP,
	Widget \f2shell\fP,
	int \f2accept\fP,
	int \f2sendStatus\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'char *ttdt_open('u
char *ttdt_open(int *\f2ttfd\fP,
	const char *\f2toolname\fP,
	const char *\f2vendor\fP,
	const char *\f2version\fP,
	int \f2sendStarted\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_sender_imprint_on('u
Tt_status ttdt_sender_imprint_on(const char *\f2handler\fP,
	Tt_message \f2contract\fP,
	char **\f2display\fP,
	int *\f2width\fP,
	int *\f2height\fP,
	int *\f2xoffset\fP,
	int *\f2yoffset\fP,
	XtAppContext \f2app2run\fP,
	int \f2ms_timeout\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_pattern *ttdt_session_join('u
Tt_pattern *ttdt_session_join(const char *\f2sessid\fP,
	Ttdt_contract_cb \f2cb\fP,
	Widget \f2shell\fP,
	void *\f2clientdata\fP,
	int \f2join\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttdt_session_quit('u
Tt_status ttdt_session_quit(const char *\f2sessid\fP,
	Tt_pattern *\f2sess_pats\fP,
	int \f2quit\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_pattern *ttdt_subcontract_manage('u
Tt_pattern *ttdt_subcontract_manage(Tt_message \f2subcontract\fP,
	Ttdt_contract_cb \f2cb\fP,
	Widget \f2shell\fP,
	void *\f2clientdata\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttmedia_Deposit('u
Tt_status ttmedia_Deposit(Tt_message \f2load_contract\fP,
	const char *\f2buffer_id\fP,
	const char *\f2media_type\fP,
	const unsigned char *\f2new_contents\fP,
	int \f2new_len\fP,
	const char *\f2pathname\fP,
	XtAppContext \f2app2run\fP,
	int \f2ms_timeout\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_message ttmedia_load('u
Tt_message ttmedia_load(Tt_message \f2context\fP,
	Ttmedia_load_msg_cb \f2cb\fP,
	void *\f2clientdata\fP,
	Tttk_op \f2op\fP,
	const char *\f2media_type\fP,
	const unsigned char *\f2contents\fP,
	int \f2len\fP,
	const char *\f2file\fP,
	const char *\f2docname\fP,
	int \f2send\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_message ttmedia_load_reply('u
Tt_message ttmedia_load_reply(Tt_message \f2contract\fP,
	const unsigned char *\f2new_contents\fP,
	int \f2new_len\fP,
	int \f2reply_and_destroy\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status ttmedia_ptype_declare('u
Tt_status ttmedia_ptype_declare(const char *\f2ptype\fP,
	int \f2base_opnum\fP,
	Ttmedia_load_pat_cb \f2cb\fP,
	void *\f2clientdata\fP,
	int \f2declare\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'void tttk_Xt_input_handler('u
void tttk_Xt_input_handler(XtPointer \f2procid\fP,
	int *\f2source\fP,
	XtInputId *\f2id\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status tttk_block_while('u
Tt_status tttk_block_while(XtAppContext \f2app2run\fP,
	const int *\f2blocked\fP,
	int \f2ms_timeout\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status tttk_message_abandon('u
Tt_status tttk_message_abandon(Tt_message \f2msg\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_message tttk_message_create('u
Tt_message tttk_message_create(Tt_message \f2context\fP,
	Tt_class \f2the_class\fP,
	Tt_scope \f2the_scope\fP,
	const char *\f2handler\fP,
	const char *\f2op\fP,
	Tt_message_callback \f2callback\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status tttk_message_destroy('u
Tt_status tttk_message_destroy(Tt_message \f2msg\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status tttk_message_fail('u
Tt_status tttk_message_fail(Tt_message \f2msg\fP,
	Tt_status \f2status\fP,
	const char *\f2status_string\fP,
	int \f2destroy\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tt_status tttk_message_reject('u
Tt_status tttk_message_reject(Tt_message \f2msg\fP,
	Tt_status \f2status\fP,
	const char *\f2status_string\fP,
	int \f2destroy\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'char *tttk_op_string('u
char *tttk_op_string(Tttk_op \f2opcode\fP);
.PP
.fi
.PP
.ft 3
.nf
.ta \w'Tttk_op tttk_string_op('u
Tttk_op tttk_string_op(const char *\f2opstring\fP);
.PP
.fi
