.\" $Header: Ident.1,v 1.2 93/09/20 10:54:24 xbuild_hp_cv Exp $
.TH Ident 1
.ds )H Hewlett-Packard Company
.ds ]W HP-UX Release 9.0: August 1992
.SH NAME
Ident \- Identify files in \s+1RCS\s0
.SH SYNOPSIS
.I Ident
.IR file \0...
.SH DESCRIPTION
.I Ident
searches the named files for all occurrences of the pattern
.I $ keyword :\f1...\fP$\f1,
where
.I keyword
is one of the following:
.RS
.TP 20
.I Author
.I Log
.PD 0
.TP
.I Date
.I Revision
.TP
.I Header
.I Source
.TP
.I Locker
.I State
.PD
.RE
.PP
These patterns are normally inserted automatically by the
.SM RCS
.I Co
command, but can also be inserted manually (see
.IR Co (1)).
.PP
.I Ident
works on text files as well as object files.
For example, if the C program in file
.I f.c
contains:
.IP
.I char rcsid[] =
.I """$\&Header:  Header information $""";
.PP
and
.I f.c
is compiled into
.IR f.o ,
the command:
.IP
.I "Ident f.c f.o"
.PP
prints:
.RS
.TP 15
.I f.c:
.br
.I $\&Header: Header information $
.TP
.I f.o:
.br
.I $\&Header: Header information $
.RE
.SH AUTHOR
.I Ident
was developed by Walter F. Tichy.
.SH SEE ALSO
Ci(1), Co(1), Rcs(1), Rcsdiff(1), Rcsintro(5), Rcsmerge(1),
Rls(1), Rcslocks(1),
Rlog(1), Rcsfile(4).
.\"
.\" toc	\f3Ident(1)\f1:\0\0\f4Ident\f1 	 Identify files in \s-1RCS\s+1
.\"
.\" index	\f4Ident\f1 \- Identify files in Revision Control System 	 \f3Ident(1)\f1
.\" index	Identify files in Revision Control System 	 \f3Ident(1)\f1
.\" index	\s-1RCS\s+1: Identify files in Revision Control System 	 \f3Ident(1)\f1
.\"
.\" fileset_database	Ident.1 SRC-CNTL-MAN
