#! /bin/ksh
#This script correctly installs the rcs tools

for tool in `echo "Co Ci Rcsdiff Rcsmerge Rlog Rcs Rcslocks Rls"`
do
	(cd /usr/local/bin
	ln -s -f /x/toolsrc/BuildTools/rcs_tools/$tool .)
done

