.TH RCS_TOOLS 1 "" "" ""
.SH NAME
rcs_tools - new versions of standard RCS tools used for local access.
.SH DESCRIPTION
.I rcs_tools 
installs new versions of the standard RCS tools co, ci, rcs, etc. as Co,
Ci, Rcs, etc. Access to the Corvallis source and build trees must be
done with these tools instead of the standard RCS tools.
.SS Other Information
The new version of the RCS tools behave almost identically to the
standard versions except that some fussing with quotes may be necessary
to get the -m option of Ci to work correctly.  For more information see
the standard RCS man pages.
.SH AUTHOR
.I rcs_tools
was written by Marc Ayotte (marca@cv.hp.com).
