.\" $Header: Rcsmerge.1,v 1.1 92/11/18 16:28:32 bin Exp $
.TH Rcsmerge 1 "" "" HP-UX
.ds )H Hewlett-Packard Company UTD-CV
.ds ]W November 1992
.SH NAME
Rcsmerge \- UTD-CV RCS merge utility.
.SH SYNOPSIS
.B Rcsmerge
.RI [ \|options\| ]
.I file ...
.SH DESCRIPTION
.I Rcsmerge
is a ksh front-end to the
.I rcsmerge
program.
It is used exactly like the original RCS executable.
See 
.IR rcsmerge (1)
for more information.
.SH AUTHOR
.I Rcsmerge
was developed by Marc Ayotte,
UTD-CV, Hewlett-Packard.
.SH SEE ALSO
Co(1),
Ci(1), Rcsdiff(1),
Rlog(1), Rcs(1),
and the rcs utilities
ci(1), co(1), ident(1),
rcs(1), rcsdiff(1),
rcsmerge(1), rlog(1),
rcsfile(4),
acl(5), rcsintro(5).
