#! /bin/sh

# tool to merge files under RCS
# setgid for group of RCS directories and make RCS dir 775 permission

echo ""
echo "	*****************************************************"
echo "	Rcsmerge is temporarily unavailable."
echo "	*****************************************************"
echo ""

#/usr/bin/rcsmerge "$@"
