/* XPM */
static char * VIctrGenTbx [] = {
/* width height ncolors cpp [x_hot y_hot] */
"55 45 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s topShadowColor m white c #bdbdbdbdbdbd",
"O    s iconGray5     m black c #737373737373",
"+    s iconGray1     m white c #dededededede",
"@    s iconGray4     m white c #949494949494",
"#	s iconColor2	m white	c white",
"$    s iconGray7     m black c #424242424242",
"%    s iconGray3     m white c #adadadadadad",
"&	s iconColor1	m black	c black",
"*    s iconGray6     m black c #636363636363",
/* pixels */
"                                                       ",
"                                                       ",
"                                                       ",
"                                                       ",
"                    ............                       ",
"                   ..XXXXXXXXXXXo                      ",
"     ...............XOOOOOOOOOOO........oo             ",
"    .+@############XO$$$$$$$$$$OO$#####%&&oo           ",
"    .++O###########XO$#########XO$#######%&&oo         ",
"    .+++@########XXO$XXXXXXXXXXXXOOOX######%&&oo       ",
"    .++++O###################################%&&oo     ",
"    .+++++@####################################&&o     ",
"    .$++++%O@O@O@O@O@O@O@O@O@O@O@O@O@O@O@O@O@O@O&o     ",
"    .X$+++%XXXXXXXXXXXXXXXXX##XXXXXXXXXXXXXXXXXX&o     ",
"    .XX$++%OXXXXXXXXXXXXXXX#XXOXXXXXXXXXXXXXXXXX&o     ",
"    .X%X$+%XXX###XXXXXXXXXX#XXOXXXXXXXXXX###XXXX&o     ",
"    .X%%X$%OXX#++@XXXXXXXXXXOOXXXXXXXXXXX#++@XXX&o     ",
"    .X%%%X$$$$#++.$$$$$$$$$$$$$$$$$$$$$$$#++..$$&o     ",
"    .X%%%XOOOO#++.OOOOOOOOOOOOOOOOOOOOOOO#++.OOO&o     ",
"    .X%%%XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO&o     ",
"    .X%%%XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$%O&o     ",
"    .X%%%XO$%%%%%%%%%%%%%%%%%$%%%%%%%%%%%%%%%$%O&o     ",
"    .X%%%XO$%OOOOO+XXX*OOOOOO$%OOOO+XXX*OOOOO$%O&o     ",
"    .X%%%XO$%OOOOO*****OOOOOO$%OOOO*****OOOOO$%O&o     ",
"    .X%%%XO$%OOOOOOOOOOOOOOOO$%OOOOOOOOOOOOOO$%O&o     ",
"    .X%%%XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$%O&o     ",
"    .X%%%XO$%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$%O&o     ",
"    .X%%%XO$%OOOOO+XXX*OOOOOOOOOOOO+XXX*OOOOO$%O&o     ",
"    .X%%%XO$%OOOOO*****OOOOOOOOOOOO*****OOOOO$%O&o     ",
"    .X%%%XO$%OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO$%O&o     ",
"    .X%%%XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$%O&o     ",
"    .X%%%XO$%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$%O&o     ",
"    .X%%%XO$%OOOOO+XXX*OOOOOOOOOOOO+XXX*OOOOO$%O&o     ",
"    ..%%%XO$%OOOOO*****OOOOOOOOOOOO*****OOOOO$%O&o     ",
"    o&&%%XO$%OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO$%O&o     ",
"     o&&%XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$%O&o     ",
"      o&&XO$%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%O&o     ",
"       o&&OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO&o     ",
"        o&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&o     ",
"         ooooooooooooooooooooooooooooooooooooooooo     ",
"                                                       ",
"                                                       ",
"                                                       ",
"                                                       ",
"                                                       "};
