/* XPM */
static char * VIctrPerTbx [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 53 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X	s iconColor2	m white	c white",
"o    s topShadowColor m white c #bdbdbdbdbdbd",
"O    s iconGray4     m white c #949494949494",
"+	s iconColor1	m black	c black",
"@    s iconGray6     m black c #636363636363",
"#    s iconGray7     m black c #424242424242",
"$    s iconGray5     m black c #737373737373",
"%    s iconGray2     m white c #bdbdbdbdbdbd",
"&	s iconColor6	m white	c yellow",
"*	s iconColor8	m white	c magenta",
"=    s iconGray3     m white c #adadadadadad",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"        ...............................................         ",
"        .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo         ",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o         ",
"        .XOOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOO+o         ",
"        .XOOOOOOOOOOOOOOOOOOOX@OOOOOOOOOOOOOOOXXOOOOO+o +       ",
"        .XOOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXX#OXX$$OOOO+o+X+      ",
"        .XOOOOOOOO#O$$$$$$$$$$$$$$$$$$$$$$+%$$$++OOOO+oX&+o     ",
"        .XOOOOOOOOOO#+++++++++X#++++++++++%X+#+OOOOOO+X&*+o     ",
"     ....XOOOOOOOOOOOOOOOOOOOOX#OOOOOOOOX%$+==$$$$OO$X&*&+o     ",
"    ..XXXXXXXXXXXX$OO$$$$$$$$$X#O$$$$$$X%$+=$$OOOOO$X&*&*+o     ",
"    .XXXXXXXXXXXXXXOOOOOOOOOOOOXOOOOOOX%$+=$OOOOOO$X&*&*&+o     ",
"    .X++++++++++++X+OOOOOOOOOOOXXXOOOX%$+=$OOOOOO$X&*&*&*+o     ",
"    .X+@@@@@@@@@@OX+$OOOOOOOOXXX++$OX%$+=$OOOOOO$X&*&*&*&+o     ",
"    .X+@@X@X@X@X@OX+$OOOOOOOO$$+XO=X%$+=$OOOOOO$X&*&*&*&*+o     ",
"    .X+@@@@@@@@@@OX+$OOOOOOOOOOOX#X%$+=$OOOOOO$X&*&*&*&*&+o     ",
"    .X+@@@@@@@@@@OX+$OOOOOOOOOOOXX%$+=$OOOOOO$X&*&*&*&*&*+o     ",
"    .X+OOOOOOOOOOOX+$OOOOOOOOOOOX%$+=$OOOOOO$X&*&*&*&*&*&+o     ",
"    .XXXXXXXXXXXXXX+$OOOOOOOOOOX% +=$OOOOOO$X&*&*&*&*&*&*+o     ",
"    .XX====@X=@X=@X+$OOOOOOOOOX%$+X#OOOOOO$X&*&*&*&+&*&*&+o     ",
"    .X=====@X=@X=@X+$OOOOOOOOX%$+=X#$OOOO$X&*&*&*&+X*&*&*+o     ",
"    .X=@@@@@X@@X@@X+$OOOOOOOX%$+=$OO$OOO$X&*&*&*&+OX&*&*&+o     ",
"    .XXXXXXXXXXXXXX+$OOOOOOX%$+=$OOOOOO$X&*&*&*&+O$X*&*&*+o     ",
"    .XX=@X=@X=@X=@X+$OOOOOOX$+=$OOOOOO$X&*&*&*&+O$$X&*&*&+o     ",
"    .X==@X=@X=@X=@X+$OOOOOOX+=$OOOOOO$X&*&*&*&+O$O$X*&*&*+o     ",
"    .X=@@X@@X@@X@@X+$OOOOOX+=$OOOOOO$X&*&*&*&+O$OO$X&*&*&+o     ",
"    .XXXXXXXXXXXXXX+$OOOOX+=$OOOOOO$X&*&*&*&+O$OOO$X*&*&*+o     ",
"    .XX=@X=@X=@X=@X+$OOOO+=$OOOOOO$X&*&*&*&+O$OOOO$X&*&*&+o     ",
"    .X==@X=@X=@X=@X+$OOOOO$OOOOOO$X&*&*&*&+O$OOOOO$X*&*&*+o     ",
"    .X=@@X@@X@@X@@X+$OOOOOOOOOOO$X&*&*&*&+O$OOOOOO$X&*&*&+o     ",
"    .XXXXXXXXXXXXXX+$OOOOOOOOOO$X&*&*&*&+O$OOOOOOO$X*&*&*+o     ",
"    .XX=@X=@X====@X+$OOOOOOOOO$X&*&*&*&+O$$$$$$$$$$X&*&*&+o     ",
"    .X==@X=@X====@X+$OOOOOOOO$X&*&*&*&+XXXXXXXXXXXXX*&*&*+o     ",
"    .X=@@X@@X@@@@@X+$OOOOOOO$X&*&*&*&*&*&*&*&*&*&*&*&*&*&+o     ",
"    .=XXXXXXXXXXXX=+$OOOOOO$X&*&*&*&*&*&*&*&*&*&*&*&*&*&*+o     ",
"     o+++++++++++++@$OOOOO$X&*&*&*&*&*&*&*&*&*&*&*&*&*&*&+o     ",
"      oooX$$$$$$$$$$OOOOO$X&*&*&*&*&*&*&*&*&*&*&*&*&*&*&*+o     ",
"        .XOOOOOOOOOOOOOOOX&*&*&*&*&*&*&*&*&*&*&*&*&*&*&*&+o     ",
"        .XOOOOOOOOOOOOOOOO++++++++++++++++++++++++++++++++o     ",
"        .XOOOOOOOOOOOOOOOOO$$$$$$$$$$$$$$$$$$$$$$$$$$+ooooo     ",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o         ",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o         ",
"        .X++++++++++++++++++++++++++++++++++++++++++++o         ",
"        .oooooooooooooooooooooooooooooooooooooooooooooo         ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "};
