/* XPM */
static char * VIctrRemTbx [] = {
/* width height ncolors cpp [x_hot y_hot] */
"65 42 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X	s iconColor2	m white	c white",
"o    s iconGray7     m black c #424242424242",
"O    s topShadowColor m white c #bdbdbdbdbdbd",
"+    s iconGray3     m white c #adadadadadad",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray6     m black c #636363636363",
"$    s iconGray1     m white c #dededededede",
"%	s iconColor1	m black	c black",
"&    s iconGray4     m white c #949494949494",
"*    s iconGray5     m black c #737373737373",
/* pixels */
"                                                                 ",
"                                                                 ",
"                                                                 ",
"                                                                 ",
"                                                                 ",
"             ......                         ......               ",
"            .XXXXXXX                       .XXXXXXX              ",
"      .......ooooooo......           .......ooooooo......        ",
"     .XXXXXXXXXXXXXXXXXXXXO         .XXXXXXXXXXXXXXXXXXXXO       ",
"    .X+@@@@@@@@@Xo@@@@@@@@#O       .X+@@@@@@@@@Xo@@@@@@@@#O      ",
"   .X$+@@@@@@@@Xo@@@@@@@@@@#O     .X$+@@@@@@@@Xo@@@@@@@@@@#O     ",
"  .X$$ooooooooooooooooooooo%O    .X$$ooooooooooooooooooooo%O     ",
"  .X$o#&&&######%&%####oo%O      .X$o#&&&######%&%####oo%O       ",
"  .Xooo#&&&oooo%&&&&oooo%O       .Xooo#&&&oooo%&&&&oooo%O        ",
"    o###$@@@@#%@@%#@Xo#%O.         o###@@@@@#%@@%#@Xo#%O.        ",
"   .$oooo@@@@@@@%#@@%Xo#%%.       .$oooo@@@@@@@%#@@%Xo#%%.       ",
"   .@$##o@@XX@@%#@@%X%XXXX%%O     .@$##o@XXX@@%#@@%X%XXXX%%      ",
"   .@+$$$X+%$$$$$$$$$$X+%$$%O     .@+$$$X+%$$$$$$$$$$X+%$$%O     ",
"   .@+@********************%O     .@+@********************%O     ",
"   .@+@*oooooooooooooooooo*%O     .@+@*oooooooooooooooooo*%O     ",
"   .@+@*o+++X@o++o+++X@o+o*%O     .@+@*o+++X@o++o+++X@o+o*%O     ",
"   .@+@*o***ooo**o***ooo*o*%O     .@+@*o***ooo**o***ooo*o*%O     ",
"   .@+@*oooooooooooooooooo*%O     .@+@*oooooooooooooooooo*%O     ",
"   .@+@*o++++++++++++++++o*%O     .@+@*o++++++++++++++++o*%O     ",
"   .@+@*o+**X@o******X@o*o*%O     .@+@*o+**X@o******X@o*o*%O     ",
"   .@+@*o+**ooo******ooo*o*%O     .@+@*o+**ooo******ooo*o*%O     ",
"    %+@*oooooooooooooooooo*%O      %+@*oooooooooooooooooo*%O     ",
"    O%@********************%O      O%@********************%O     ",
"     O%%%%%%%%%%%%%%%%%%%%%%O       O%%%%%%%%%%%%%%%%%%%%%%O     ",
"      OOOOOOOOOO@%OOOOOOOOOOO        OOOOOOOOO@%OOOOOOOOOOOO     ",
"                @%O                           @%O                ",
"                @%O                           @%O                ",
"                @%O                           @%O                ",
"               @@%@                          @@%@                ",
"    @@@@@@@@@@@@%O%@@@@@@@@@@@@@@@@@@@@@@@@@@@%O%@@@@@@@@@@@@@   ",
"     %%%%%%%%%%%O O%%%%%%%%%%%%%%%%%%%%%%%%%%%O O%%%%%%%%%%%%%O  ",
"      OOOOOOOOOO   OOOOOOOOOOOOOOOOOOOOOOOOOOO   OOOOOOOOOOOOOO  ",
"                                                                 ",
"                                                                 ",
"                                                                 ",
"                                                                 ",
"                                                                 "};
