! XPM2
48 48 16 1
a c #000000
b c #212121
c c #424242
d c #636363
e c #737373
f c #949494
g c #adadad
h c #bdbdbd
i c #dedede
j c #ffffff
k c #ff0000
l c #00ff00
m c #0000ff
n c #00ffff
o c #ff00ff
p c #ffff00
jjjjjjjjjjjjjjjjjiiiiiiiiiiiiiiiiijjjjjjjjjjjjjf
jffffffffffffffffffhhiiippppiiihhhfffffffffffffc
jffffffffffffffffghhipppppppppiiihggfffffffffffa
jffffffffffffffgghiippjjpjppjjppiiiggffffffffffa
jfffffffffffffgghiipppjpjpjjpjpppiiihgfffffffffa
jfffffffffffffghiipppjppjjpjppjjpppiihgffffffffa
jffffffffffffhhippppjjjjjjjjjjjjjpppiihffffffffa
jffffffffffffghippjjjjjjjiiijjjjjjpppihgfffffffa
jfffffffffffghipppjjjjjjihhiijjjjjjppiigfffffffa
jfffffffffffgipppjppjiighhihhhijjppjppihgffffffa
jfffffffffffhipjjpihhhhhijiiihhhgiipipihgffffffa
jffffffffffghipjpphfdhijjjjjjihfdgppjjihgffffffa
jffffffffffghpppjjihhiijjjjjjjiigijjppihgffffffa
jffffffffffhhpppjpjihhijjjjjjjihiiipjpihgffffffa
jffffffffffghppjppjjihijjjjjjjhhijjpjjihgffffffa
jffffffedeeegpppjjppjhhijjjjjihijppjppihgffffffa
jffffefdmemchipjpjpjjhiipjjpihiipjpjppihgffffffa
jfffeddmememgipjppjppihhppjpigippjjpjjihgffffffa
jffmmemememdefppjjpjjpihiipihhpjjppjpphggffffffa
jfdbmmememecdgppppjppjphihphhpjpjpjjpihgfffffffa
jfdmbmmememedfhpppjjpjpphffgppjppjppphegfffffffa
jfdbmbmmememecfhipppjpihhfehhhpjjpppidgffffffffa
jfdmbmbmmememecehippiphggfdhhghpjpiffmdffffffffa
jfdbmbmbmmememedfhppphffgedhgfhipiffememfffffffa
jfdmbmbmbmmememedhiippighfdhghpiifcmmememffffffa
jfeembmbmbmmememeeffiiphphhphpifedmmemememfffffa
jffeembmbmbmmemememeddgpppppppfammmememememffffa
jffeedmbmbmbmmemfmfmmgfegfedfgacemfmemfmememfffa
jfeedddmbmbmbmmememfmfffigfffeabmemememememmmffa
jfddccddmbmbmbmmfmfmmdfgjiggfdammmfmfmemmmmmmffa
jffeddcddmbmbmbmmfmfmgfegfddfgabefmfmfmmmdhgfffa
jfffeddcddmbmbmbmmfmmfffigffffabmmfmemccffihfffa
jffffeddcedmbmbmbmmfmdehjiggfdammfmmmdeggijhfffa
jfffffeddcddmbmbmbmmmabcccccbammmmmdffhjjjjhfffa
jffffffeddcddmbmbmbmmcbbeeebbbmcddefhiijjjjigffa
jfffffffeeccedmbmbmbmdcagihammeedggijjjjjjjigffa
jffffffffdedcddmbmbmbmmmmmmmbdeghjjjjjjjihecmffa
jfffffffffedccddmbmbmbmmmmcmffhiijjjjjihfdmmdffa
jffffffffffeeccedmbmbmmmmceggijjjjjjjifdmmmdfffa
jfffffffffffeedcddmbmmmdfghjjjjjjjihecmmcddeeffa
jffffffffffffeddcdcmbmceghijjjjjigfdmmcmddddeefa
jfffffffffffffeddcdcmmcdgijjjjjhgdmmmccccedddffa
jffffffffffffffeddcddmcehijjihecmmcccdddddeffffa
jfffffffffffffffeddcdcmcfhihfdcmbmcdcdddeffffffa
jffffffffffffffffedccecmcfgdmmmcdcdddddffffffffa
jfffffffffffffffffdedcddmmmmcccddddddffffffffffa
jffffffffffffffffffdcbbcamamdddddddffffffffffffa
fcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
