/* XPM */
/****************************************************************
*  Copyright (c) 1996 Sun Microsystems, Inc.
*  All Rights Reserved
*****************************************************************/
static char * SDturlweb_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray7	m black	c #424242424242",
"#	s iconColor5	m black	c blue",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray3	m white	c #adadadadadad",
"&	s iconGray4	m white	c #949494949494",
"*	s iconColor7	m white	c cyan",
"=	s iconColor4	m white	c green",
/* pixels */
"       .........................",
"       .XXXXXXXXXXXXXXXXXXXXXXXo",
"       .XXXXXXXXXXXXXXXXXXXXXXXo",
"       .XO+OXX+O+OXX+O+OXX+OXXXo",
"       .XX+X+O+X+X+O+X+X+O+XXXXo",
"       .XX++++OX++++OX++++OXXXXo",
"       .XX+O+OXX+O+OXX+O+OXXXXXo",
"       .XX+X+XXX+X+XXX+X+XXXXXXo",
"       .XXXXXXXXXXXXXXXXXXXXXXXo",
"       .XXXXXXXXXXXXXXXXXXXXXXXo",
"       .XX@X#$###$###XXXXXXXXXXo",
"       .XX#@%&&%XX&&XXXXXXXXXXXo",
"       .XX@#@X$$+$$+$+++$XXXXXXo",
"       .XX#@#@XXXXXXXXXXXXXXXXXo",
"    @#@#@#@#@#@XXXXXXXXXXXXXXXXo",
"  #@#@#@#@#@#@#X$##XXXXXXXXXXXXo",
" #@#@#@#XX@#@#%&&%XXXXXXXXXXXXXo",
" @#@#@#.XX#@#X@+&&XXXXXXXXXXXXXo",
"@#@#@#@.XX@#%&&%XXXXXXXXXXXXXXXo",
"#@#@#@ .XX#XXXXXXXX&@@@@@@@XXXXo",
"@#@#@# .XXXXXXXXX&@@X&X.XX#@@XXo",
"#@#@#@ .XXXXXXXX@@X...X..XX&X@$o",
" #@#@# .XXXXXXX@&X....XX*&X*#&#o",
"  #@#@ .XXXXXXX@X....*=*X&&O&O&o",
"   #@# .XXXXXX@XX....=*X*&&&OO#o",
"    #@ .XXXXXX@XXX.=XXX*X&O=O#*o",
"     # .XXXXX@X.X.XX*XX&&&*&=X*o",
"       .XXXXX@&#*#=*X&&&&*&=O*Oo",
"       .XXXXX@&&X&&&&X&&*&*OXOOo",
"       .XXXXX@&#&XXX&&*X&*#O#OOo",
"       .XXXXX@&&#&&&&XO@*&*XOOOo",
"       .oooooooooooooooooooooooo"};
