/* XPM */
/****************************************************************
*  Copyright (c) 1996 Sun Microsystems, Inc.
*  All Rights Reserved
*****************************************************************/
static char * SDtwebbr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconColor1	m black	c black",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconColor7	m white	c cyan",
"#	s iconGray5	m black	c #737373737373",
"$	s iconColor2	m white	c white",
"%	s iconColor4	m white	c green",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconGray8	m black	c #212121212121",
"=	s iconColor5	m black	c blue",
"-	s iconGray1	m white	c #dededededede",
/* pixels */
"                    .XXXXXXXXX.                 ",
"                  XXoOO++OO@OooXX.#             ",
"                XXo++$$+%+OOOOOo@XX#$$$$        ",
"               XO+$$$$$$$$&+&&+@OO&X###+$       ",
"              XOO$$$$$$+$%&+&&++O&OOX**#$#      ",
"             XOO$$$$$$$$+$+o+@+@O@o@OXOO$O*     ",
"            XOO+$$$$$$$+$$+@+o@+Oo&oo.*O$O*     ",
"            XOO$&$$$$+$$+O+++++Oo%oooOO$+*#     ",
"           XO@+$$$$+$$+&+$$@OO@OOO@o=$$+*#      ",
"   $$$$$$$ XO++++$$$+@+++O@+OO+O%o+$$+**#       ",
"  $+######.Oo++@$+$+$+++&%+o+++$$$$+.*...       ",
" $##******XOo&&++@&&+++o&&+$$$$+O.***.o=X       ",
" $#**     XOo&&++@&&++$$$$$+OO.***..oo=XX       ",
" $$$$$$$$$$$$$$$$$$$$$$+OO.****oo+O.oo.XX       ",
"  OOOOOOOOOOOOOOOOOOO.*****OOoO.O=.oo.=XX       ",
"   #******************OO@++@OOOOoooo....X       ",
"          XO&O@O+O+OoOOoOooOOOooo..=.o.XX       ",
"          XOOOOO+@OO@OOOo=OOO.ooo..o.X.XX       ",
"          XoOOOOOOoOOO.O@OO.Ooo.......=XX       ",
"          XoOOOOO@oOO..OoOOOooO..=..X.XXX       ",
"          .ooO=O=OO.OOOOOOOooo=.o..X.XXX.       ",
"       $$$$$$$$$$$$$$$$$$$$ooo..oo..=XXX$$      ",
"      $&&&&&&&&&&&&&&&&&&&&*o...o..X.XXX*#$$    ",
"      $&&&&&&&&&&&&&&&&&&&&*o.oo=...XXX.***O$   ",
"      $&&...............O&&*oo=..XXXXXX   #*$$  ",
"      $&&.##############$&&*...o...XXX      #$# ",
"      $&&.##O$##########$&&*.=..XXXXX        $O*",
"      $&&.##$###########$&&*X..XXXXX         $O*",
"      $&&.##$###########$&&*XXXXXXX          $O*",
"      $&&.##$###########$&&*XXXXX           $$*#",
"      $&&.##############$&&*XX.             $O* ",
"      $&&.##############$&&*              $$O*# ",
"      $&&.##############$&&*            $$O**#  ",
"      $&&.##############$&&*          $$O**#    ",
"      $&&O$$$$$$$$$$$$$$$&&*        $$O**#      ",
"      $&&&&&&&&&&&&&&&&&&&&*      $$O**#        ",
"      $&&&&&&&&&&&&&&&&&&&&*     $$**#          ",
"       ********************     $O*#            ",
"         **............**      $O*#             ",
"          **oooooooooo**      $O*#              ",
"    ##########################*##               ",
"   #OOOOOOOOOOOOOOOOOOOOOOOOOOO*#               ",
"  #$$$#$$#$$#$$#$$#$$#$$$$#$#$#$*               ",
" #$$$#$$#$$#$$#$$#$$#$$#$$$#$#$$$*              ",
"#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*             ",
"$----------------------------------*            ",
"$OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*            ",
" **********************************             "};
