/*
 * File: AutoFiling_ui.C
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module AutoFiling
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/PanedW.h>
#include <Xm/Separator.h>
#include <Xm/Label.h>
#include <Xm/ScrollBar.h>
#include <Xm/ScrolledW.h>
#include <Xm/List.h>
#include <Xm/PushB.h>
#include "dtb_utils.h"
#include "dtmailopts.h"
#include "AutoFiling_ui.h"


DtbAutoFilingDialogInfoRec	dtb_auto_filing_dialog = 
{
    False	 /* initialized */
};

/*
 * Widget create procedure decls
 */
static int dtb_auto_filing_dialog_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_dialog_button_panel_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_controlpane_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_sep3_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_af_group_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_af_lb_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_mailbox_list_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_check_button_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_open_button_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_filing_button_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_cancel_button_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);
static int dtb_auto_filing_help_button_create(
    DtbAutoFilingDialogInfo	instance,
    Widget	parent
);

int 
dtbAutoFilingDialogInfo_clear(DtbAutoFilingDialogInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_auto_filing_dialog_initialize(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_auto_filing_dialog_create(instance,
        parent);
    dtb_auto_filing_dialog_button_panel_create(instance,
        instance->dialog_panedwin);
    dtb_auto_filing_controlpane_create(instance,
        instance->dialog_form);
    dtb_auto_filing_sep3_create(instance,
        instance->controlpane);
    dtb_auto_filing_af_group_create(instance,
        instance->controlpane);
    dtb_auto_filing_af_lb_create(instance,
        instance->af_group);
    dtb_auto_filing_mailbox_list_create(instance,
        instance->af_group);
    dtb_auto_filing_check_button_create(instance,
        instance->dialog_button_panel);
    dtb_auto_filing_open_button_create(instance,
        instance->dialog_button_panel);
    dtb_auto_filing_filing_button_create(instance,
        instance->dialog_button_panel);
    dtb_auto_filing_cancel_button_create(instance,
        instance->dialog_button_panel);
    dtb_auto_filing_help_button_create(instance,
        instance->dialog_button_panel);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->sep3,
        XmNtopWidget, instance->af_group,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    dtb_children_align(instance->af_group,
		DTB_GROUP_COLUMNS,
		DTB_ALIGN_NONE,
		DTB_ALIGN_LEFT,
		0, 1, 0, 0, 10);
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtManageChild(instance->mailbox_list);
    XtVaGetValues(instance->af_group,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->controlpane,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->dialog_form);
    XtManageChild(instance->dialog_button_panel);
    XtVaGetValues(instance->dialog_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->dialog_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->mailbox_list,
		XmNdefaultActionCallback, doubleClickCB,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->check_button,
		XmNactivateCallback, AFCheck_CB,
		(XtPointer)&(*instance));
	XtAddCallback(instance->open_button,
		XmNactivateCallback, AFOpen_CB,
		(XtPointer)&(*instance));
	XtAddCallback(instance->filing_button,
		XmNactivateCallback, AFFiling_CB,
		(XtPointer)&(*instance));
	XtAddCallback(instance->cancel_button,
		XmNactivateCallback, AFCancel_CB,
		(XtPointer)&(*instance));
	XtAddCallback(instance->help_button,
		XmNactivateCallback, AFHelp_CB,
		(XtPointer)&(*instance));
return 0;
}



static int 
dtb_auto_filing_dialog_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    String	title_str = NULL;
    
    if (instance->dialog == NULL) {
        title_str = XtNewString(catgets(Dtb_project_catd, 4, 1, "Mailer - Auto-filing Mailboxes"));
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, title_str);  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->dialog =
            XmCreateDialogShell(parent,
                "dtb_AutoFiling_dialog", args, n);
        XtFree(title_str);
        title_str = NULL;
    }
    if (instance->dialog == NULL)
        return -1;

    if (instance->dialog_shellform == NULL) {
        instance->dialog_shellform =
            XtVaCreateWidget("dtb_AutoFiling_dialog_shellform",
                xmFormWidgetClass,
                instance->dialog,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->dialog, "white"),
                NULL);
    }
    if (instance->dialog_shellform == NULL)
        return -1;

    if (instance->dialog_panedwin == NULL) {
        instance->dialog_panedwin =
            XtVaCreateWidget("dialog_panedwin",
                xmPanedWindowWidgetClass,
                instance->dialog_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->dialog_shellform, "white"),
                NULL);
    }
    if (instance->dialog_panedwin == NULL)
        return -1;

    if (instance->dialog_form == NULL) {
        instance->dialog_form =
            XtVaCreateWidget("dialog_form",
                xmFormWidgetClass,
                instance->dialog_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNbackground, dtb_cvt_string_to_pixel(instance->dialog_panedwin, "white"),
                NULL);
    }
    if (instance->dialog_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_dialog_button_panel_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel == NULL) {
        instance->dialog_button_panel =
            XtVaCreateWidget("dialog_button_panel",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_controlpane_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane == NULL) {
        instance->controlpane =
            XtVaCreateWidget("controlpane",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, -1,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, -1,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                NULL);
    }
    if (instance->controlpane == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_sep3_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    
    if (instance->sep3 == NULL) {
        instance->sep3 =
            XtVaCreateWidget("sep3",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 20,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 11,
                XmNy, 377,
                NULL);
    }
    if (instance->sep3 == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_af_group_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    
    if (instance->af_group == NULL) {
        instance->af_group =
            XtVaCreateWidget("af_group",
                xmFormWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 42,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 22,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 22,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNy, 22,
                XmNx, 22,
                NULL);
    }
    if (instance->af_group == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_af_lb_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 4, 2, "Mailboxes with asterisk (*) contain new mail"));
    if (instance->af_lb == NULL) {
        instance->af_lb =
            XtVaCreateWidget("af_lb",
                xmLabelWidgetClass,
                parent,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->af_lb == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_mailbox_list_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    Arg	args[10];	/* need 5 args (add 5 to be safe) */
    int	n = 0;
    
    
    if (instance->mailbox_list == NULL) {
        n = 0;
        XtSetArg(args[n], XmNscrollBarDisplayPolicy, XmAUTOMATIC);  ++n;
        XtSetArg(args[n], XmNlistSizePolicy, XmCONSTANT);  ++n;
        XtSetArg(args[n], XmNselectionPolicy, XmMULTIPLE_SELECT);  ++n;
        XtSetArg(args[n], XmNvisibleItemCount, 15);  ++n;
        XtSetArg(args[n], XmNwidth, 630);  ++n;
        instance->mailbox_list =
            XmCreateScrolledList(parent,
                "mailbox_list", args, n);
    }
    instance->mailbox_list_scrolledwin = XtParent(instance->mailbox_list);
    if (instance->mailbox_list == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_check_button_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 4, 3, "Check Selected"));
    if (instance->check_button == NULL) {
        instance->check_button =
            XtVaCreateWidget("check_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 19,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 2,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 118,
                XmNy, 457,
                XmNx, 601,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->check_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_open_button_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 4, 4, "Open"));
    if (instance->open_button == NULL) {
        instance->open_button =
            XtVaCreateWidget("open_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 39,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 21,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 126,
                XmNy, 457,
                XmNx, 701,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->open_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_filing_button_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 4, 5, "Filing Rules..."));
    if (instance->filing_button == NULL) {
        instance->filing_button =
            XtVaCreateWidget("filing_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 59,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 41,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 125,
                XmNy, 457,
                XmNx, 801,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->filing_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_cancel_button_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 4, 6, "Cancel"));
    if (instance->cancel_button == NULL) {
        instance->cancel_button =
            XtVaCreateWidget("cancel_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 79,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 61,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 126,
                XmNy, 457,
                XmNx, 901,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->cancel_button == NULL)
        return -1;

    return 0;
}



static int 
dtb_auto_filing_help_button_create(
    DtbAutoFilingDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized(catgets(Dtb_project_catd, 4, 7, "Help"));
    if (instance->help_button == NULL) {
        instance->help_button =
            XtVaCreateWidget("help_button",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 98,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 81,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, False,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 23,
                XmNwidth, 118,
                XmNy, 457,
                XmNx, 1001,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->help_button == NULL)
        return -1;

    return 0;
}

