/*
 * File: options_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module options
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _OPTIONS_UI_H_
#define _OPTIONS_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct {
    Widget	Basic_item;
    Widget	Aliases_item;
    Widget	Compose_Window_item;
    Widget	Message_View_item;
    Widget	Move_Menu_Setup_item;
    Widget	Notification_item2;
    Widget	Signature_item;
    Widget	Templates_item;
    Widget	Toolbar_item;
    Widget	Vacation_Message_item;
    Widget	Advanced_item;
} OptionsCategoryOpmenuItemsRec, *OptionsCategoryOpmenuItems;
typedef struct {
    Widget	Basic_item;
    Widget	Aliases_item;
    Widget	Compose_Window_item;
    Widget	Message_View_item;
    Widget	Move_Menu_Setup_item;
    Widget	Notification_item2;
    Widget	Signature_item;
    Widget	Templates_item;
    Widget	Toolbar_item;
    Widget	Vacation_Message_item;
    Widget	Advanced_item;
} OptionsCategoryOpmenuMenuItemsRec, *OptionsCategoryOpmenuMenuItems;
typedef struct {
    Widget	When_I_close_the_mailbox_item;
    Widget	Show_confirmation_notice_item;
} OptionsDeletedMsgCbItemsRec, *OptionsDeletedMsgCbItems;
typedef struct {
    Widget	Show_To_recipient_when_mail_is_from_me_item;
    Widget	Display_message_numbers_item;
} OptionsCheckboxItemsRec, *OptionsCheckboxItems;
typedef struct {
    Widget	Save_a_copy_of_outgoing_mail_in_item;
} OptionsCheckbox2ItemsRec, *OptionsCheckbox2Items;
typedef struct {
    Widget	Save_mailbox_every_item;
} OptionsSaveMbEveryCbItemsRec, *OptionsSaveMbEveryCbItems;
typedef struct {
    Widget	Icons_item;
    Widget	Text_item;
} OptionsToolbarDisplayTypeRbItemsRec, *OptionsToolbarDisplayTypeRbItems;
typedef struct {
    Widget	Icons_item;
    Widget	Text_item;
} OptionsToolbarDisplayTypeRbChoiceItemsRec, *OptionsToolbarDisplayTypeRbChoiceItems;
typedef struct {
    Widget	Show_Attachment_List_item;
} OptionsWrapCheckboxItemsRec, *OptionsWrapCheckboxItems;
typedef struct {
    Widget	Local_item;
    Widget	IMAP_Server_item;
} OptionsImapChoiceCbItemsRec, *OptionsImapChoiceCbItems;
typedef struct {
    Widget	Display_up_to_item;
} OptionsDpyUpMboxCbItemsRec, *OptionsDpyUpMboxCbItems;
typedef struct {
    Widget	On_item;
    Widget	Off_item;
} OptionsVacationRbItemsRec, *OptionsVacationRbItems;
typedef struct {
    Widget	Show_confirmation_notices_item;
    Widget	Use_network_aware_mail_file_locking_item;
    Widget	Keep_empty_mailboxes_item;
    Widget	Save_messages_in_MIME_format_item;
    Widget	Send_mail_in_MIME_format_item;
} OptionsAdvDefCbItemsRec, *OptionsAdvDefCbItems;
typedef struct {
    Widget	Ignore_host_name_in_address_item;
    Widget	Include_me_item;
    Widget	Treat_the_following_as_username_item;
} OptionsAdvReplyCbItemsRec, *OptionsAdvReplyCbItems;
typedef struct {
    Widget	Warn_if_message_exceeds_item;
} OptionsWarnMsgCbItemsRec, *OptionsWarnMsgCbItems;
typedef struct {
    Widget	Include_signature_in_every_message_item;
} OptionsSignatureCbItemsRec, *OptionsSignatureCbItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	dialog;	/* object "dialog" */
    Widget	dialog_shellform;
    Widget	dialog_panedwin;
    Widget	dialog_form;
    
    Widget	dialog_button_panel;
    Widget	ctrl_panel;
    Widget	layer;
    
    Widget	category_opmenu_rowcolumn;	/* object "category_opmenu" */
    Widget	category_opmenu_menu;
    Widget	category_opmenu_label;
    Widget	category_opmenu;
    OptionsCategoryOpmenuItemsRec	category_opmenu_items;
    
    Widget	separator10;
    Widget	msg_header_pane;
    Widget	toolbar_pane;
    Widget	msg_view_pane;
    Widget	compose_win_pane;
    Widget	msg_filing_pane;
    Widget	vacation_pane;
    Widget	templates_pane;
    Widget	aliases_pane;
    Widget	advanced_pane;
    Widget	notification_pane;
    Widget	signature_pane;
    Widget	separator4;
    Widget	separator12;
    Widget	update_mailbox_lb;
    Widget	display_group;
    Widget	seconds_lbl;
    Widget	save_mb_lb;
    Widget	update_mb_lb;
    Widget	log_group;
    Widget	separator15;
    Widget	destroy_del_msg_lbl;
    
    Widget	deleted_msg_cb;	/* object "deleted_msg_cb" */
    OptionsDeletedMsgCbItemsRec	deleted_msg_cb_items;
    
    Widget	separator2;
    Widget	group13;
    Widget	group17;
    Widget	compose_display_headers_group;
    
    Widget	checkbox;	/* object "checkbox" */
    OptionsCheckboxItemsRec	checkbox_items;
    
    Widget	display_sb_rowcolumn;	/* object "display_sb" */
    Widget	display_sb_label;
    Widget	display_sb;
    
    Widget	headers_lbl;
    
    Widget	checkbox2;	/* object "checkbox2" */
    OptionsCheckbox2ItemsRec	checkbox2_items;
    
    Widget	sent_mail_tf;
    Widget	group11;
    Widget	group12;
    Widget	check_new_mail_lbl;
    Widget	check_new_mail_sb;
    Widget	update_seconds_lb;
    
    Widget	save_mb_every_cb;	/* object "save_mb_every_cb" */
    OptionsSaveMbEveryCbItemsRec	save_mb_every_cb_items;
    
    Widget	save_mb_sb;
    Widget	update_minutes_lb;
    Widget	imap_inbox_server_lb;
    Widget	imap_inbox_server_tf;
    Widget	toolbar_separator;
    
    Widget	toolbar_display_type_rb_rowcolumn;	/* object "toolbar_display_type_rb" */
    Widget	toolbar_display_type_rb_label;
    Widget	toolbar_display_type_rb;
    OptionsToolbarDisplayTypeRbItemsRec	toolbar_display_type_rb_items;
    
    Widget	toolbar_all_cmds_group;
    Widget	add_remove_group;
    Widget	group6;
    Widget	group2;
    Widget	toolbar_upper_group;
    Widget	toolbar_all_cmds_label;
    
    Widget	toolbar_all_cmds_scrolledwin;	/* object "toolbar_all_cmds" */
    Widget	toolbar_all_cmds;
    
    Widget	toolbar_add_but;
    Widget	toolbar_delete_but;
    Widget	toolbar_my_cmds_label;
    
    Widget	toolbar_my_cmds_scrolledwin;	/* object "toolbar_my_cmds" */
    Widget	toolbar_my_cmds;
    
    Widget	toolbar_move_up_but;
    Widget	toolbar_move_down_but;
    Widget	toolbar_preview_pane;
    Widget	toolbar_status_help;
    Widget	separator6;
    Widget	abr_header_lbl;
    Widget	group3;
    Widget	head_group;
    Widget	abbrev_header_box_group;
    Widget	msg_pane_group;
    Widget	msg_pane_lbl_group;
    Widget	h_field_add;
    Widget	h_field_delete;
    Widget	h_field_change;
    Widget	header_fields_lbl;
    Widget	hidden_fields_lbl;
    Widget	fields_hide;
    
    Widget	hidden_fields_list_scrolledwin;	/* object "hidden_fields_list" */
    Widget	hidden_fields_list;
    
    
    Widget	display_row_sb_rowcolumn;	/* object "display_row_sb" */
    Widget	display_row_sb_label;
    Widget	display_row_sb;
    
    Widget	characters_wide_sb_rowcolumn;	/* object "characters_wide_sb" */
    Widget	characters_wide_sb_label;
    Widget	characters_wide_sb;
    
    Widget	rows_lbl;
    Widget	char_wide_lbl;
    Widget	separator3;
    Widget	separator7;
    Widget	separator9;
    Widget	format_menu_lbl;
    Widget	compose_display_group;
    Widget	group7;
    Widget	custom_lbl_group;
    Widget	custom_box_group;
    Widget	indent_str_tf;
    Widget	indent_str_lbl;
    Widget	dead_letter_group;
    Widget	group27;
    
    Widget	wrap_checkbox;	/* object "wrap_checkbox" */
    OptionsWrapCheckboxItemsRec	wrap_checkbox_items;
    
    Widget	compose_display_sb_rowcolumn;	/* object "compose_display_sb" */
    Widget	compose_display_sb_label;
    Widget	compose_display_sb;
    
    Widget	group10;
    Widget	compose_display_lb;
    Widget	add_button;
    Widget	del_button;
    Widget	change_button;
    Widget	hdr_field_lbl;
    Widget	def_value_lbl;
    Widget	hdr_field;
    Widget	def_value_field;
    
    Widget	list_scrolledwin;	/* object "list" */
    Widget	list;
    
    Widget	deadletter_lbl;
    Widget	deadletter_field;
    Widget	separator5;
    Widget	msg_filing_label;
    Widget	path_file_lbl;
    Widget	move_menu_box_gp;
    Widget	mm_but_gp;
    Widget	separator14;
    Widget	imap_local_rb_group;
    Widget	display_upto_group;
    Widget	group14;
    Widget	group16;
    Widget	path_file_name_tf;
    
    Widget	mv_menu_lst_scrolledwin;	/* object "mv_menu_lst" */
    Widget	mv_menu_lst;
    
    Widget	auto_up_butt2;
    Widget	auto_down_butt2;
    Widget	alphalist_but;
    Widget	mm_add_butt;
    Widget	mm_delete_butt;
    Widget	mm_change_butt;
    Widget	mm_browse_butt;
    
    Widget	imap_choice_cb;	/* object "imap_choice_cb" */
    OptionsImapChoiceCbItemsRec	imap_choice_cb_items;
    
    Widget	imap_server_tf;
    Widget	group8;
    Widget	group9;
    
    Widget	dpy_up_mbox_cb;	/* object "dpy_up_mbox_cb" */
    OptionsDpyUpMboxCbItemsRec	dpy_up_mbox_cb_items;
    
    Widget	recent_sb;
    Widget	visit_mailb_lbl;
    Widget	top_level_lbl;
    Widget	srt_looking_tf;
    Widget	default_imap_folder_lb;
    Widget	imapfolder_tf;
    Widget	imap_filing_server_lb;
    Widget	imapserver_tf;
    Widget	separator11;
    Widget	vacation_lbl_group;
    Widget	vacation_box_group;
    Widget	vacation_on_off_group;
    Widget	reply_vacation_unit_group;
    Widget	start_end_date_group;
    Widget	msg_list_lbl;
    Widget	subject_lbl;
    
    Widget	vacation_msg_tp_scrolledwin;	/* object "vacation_msg_tp" */
    Widget	vacation_msg_tp;
    
    Widget	subject_tf;
    Widget	vacation_rb_lbl;
    
    Widget	vacation_rb;	/* object "vacation_rb" */
    OptionsVacationRbItemsRec	vacation_rb_items;
    
    
    Widget	reply_vacation_every_sb_rowcolumn;	/* object "reply_vacation_every_sb" */
    Widget	reply_vacation_every_sb_label;
    Widget	reply_vacation_every_sb;
    
    Widget	reply_vacation_units_lb;
    
    Widget	startdate_tf_rowcolumn;	/* object "startdate_tf" */
    Widget	startdate_tf_label;
    Widget	startdate_tf;
    
    Widget	enddate_tf_rowcolumn;	/* object "enddate_tf" */
    Widget	enddate_tf_label;
    Widget	enddate_tf;
    
    Widget	date_format_lbl;
    Widget	temm_name_group;
    Widget	templates_list_lbl;
    
    Widget	templates_list_scrolledwin;	/* object "templates_list" */
    Widget	templates_list;
    
    Widget	tem_butt_group;
    Widget	new_template_button;
    Widget	include_template_button;
    Widget	edit_template_button;
    Widget	rename_template_button;
    Widget	delete_template_button;
    Widget	group15;
    Widget	alias_box_group;
    Widget	alis_lbl_group;
    Widget	alias_add_but;
    Widget	alias_delete_but;
    Widget	al_change_but;
    Widget	alias_tf;
    Widget	addresses_tf;
    
    Widget	alias_list_scrolledwin;	/* object "alias_list" */
    Widget	alias_list;
    
    Widget	alias_tf_lbl;
    Widget	address_tf_lbl;
    
    Widget	adv_def_cb;	/* object "adv_def_cb" */
    OptionsAdvDefCbItemsRec	adv_def_cb_items;
    
    Widget	adv_add_group;
    Widget	advanced_box_group;
    Widget	warn_group;
    
    Widget	adv_reply_cb;	/* object "adv_reply_cb" */
    OptionsAdvReplyCbItemsRec	adv_reply_cb_items;
    
    Widget	separator8;
    Widget	reply_to_all_lbl;
    
    Widget	sendmail_host_tf_rowcolumn;	/* object "sendmail_host_tf" */
    Widget	sendmail_host_tf_label;
    Widget	sendmail_host_tf;
    
    Widget	local_name_add_but;
    Widget	local_name_del_but;
    Widget	local_name_chg_but;
    Widget	local_name_tf;
    
    Widget	local_name_list_scrolledwin;	/* object "local_name_list" */
    Widget	local_name_list;
    
    Widget	warn_msg_cb;	/* object "warn_msg_cb" */
    OptionsWarnMsgCbItemsRec	warn_msg_cb_items;
    
    Widget	warn_msg_sb;
    Widget	warn_msg_lb;
    Widget	separator13;
    Widget	msg_filing_lbl;
    Widget	general_notif_lbl;
    Widget	signal_lb2;
    Widget	signal_types_group;
    Widget	signal_boxes_group;
    Widget	group;
    Widget	msg_filing_lbl2;
    
    Widget	auto_list_scrolledwin;	/* object "auto_list" */
    Widget	auto_list;
    
    Widget	up_down_gp;
    Widget	beep_lbl;
    Widget	flash_lbl;
    Widget	audio_lbl;
    Widget	beep_sb2;
    Widget	flash_sb2;
    Widget	sound_txt_group;
    Widget	audio_tf2;
    Widget	sound_browse_button2;
    Widget	auto_edit_butt;
    Widget	auto_new_butt;
    Widget	auto_delete_butt;
    Widget	auto_up_butt;
    Widget	auto_down_butt;
    
    Widget	signature_cb;	/* object "signature_cb" */
    OptionsSignatureCbItemsRec	signature_cb_items;
    
    Widget	group4;
    Widget	group5;
    Widget	save_sig_lbl;
    Widget	signature_file_tf;
    Widget	signature_lbl;
    
    Widget	signature_tp_scrolledwin;	/* object "signature_tp" */
    Widget	signature_tp;
    
    Widget	ok_button;
    Widget	reset_button;
    Widget	cancel_button;
    Widget	separator;
    Widget	apply_button;
    Widget	help_button;
} DtbOptionsDialogInfoRec, *DtbOptionsDialogInfo;


extern DtbOptionsDialogInfoRec dtb_options_dialog;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbOptionsDialogInfo_clear(DtbOptionsDialogInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_options_dialog_initialize(
    DtbOptionsDialogInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */
void opt_dlog_cancelCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void opt_pane_okCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void options_applyCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void opt_dlog_resetCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void message_header_listCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void message_viewCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void compose_windowCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void message_filingCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void vacationCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void templatesCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void aliasesCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void advancedCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void vacationOnCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void vacationOffCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void vaca_msg_changedCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void signature_windowCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void toolbarAddCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void toolbarRemoveCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void toolbarSortUpCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void toolbarSortDownCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void toolbarCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void new_templateCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void include_templateCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void edit_templateCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void rename_templateCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void toolbar_preview_createCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void create_mm_path_file_name_tf(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void auto_edit_cb(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void auto_delete_cb(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void auto_new_cb(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void MoveMenu_MoveUpButtonCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void MoveMenu_MoveDownButtonCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void mv_alphaCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void auto_up_butt_cb(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void auto_down_butt_cb(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void autofiling_notificationCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void local_serverCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void imap_serverCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void delete_templateCB(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);

/*
 * Connections
 */
#endif /* _OPTIONS_UI_H_ */
