#ifndef lint
static char sccsid[] = "@(#)fileui.c 1.9 97/03/19";
#endif

/*
 * Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
 */

/*
 * fileui.c - User interface object initialization functions
 * for open/openas/save/saveas pop ups.
 * This file was generated by `gxv' from `imagetool.G'.
 */

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/FileSB.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/PushB.h>
#include <Xm/PushBG.h>
#include <Xm/RowColumn.h>

#include "help.h"
#include "imagetool.h"
#include "ui_imagetool.h"

/* 
 * Initialize an instance of object `open_dialog'
 */
Widget
OpenObjectsInitialize(parent)
     Widget   parent;
{
     register int  ac = 0;
     Arg           al[16];
     Widget        shell, dialog;
	
     extern void   OpenOKCallback();
     extern void   OpenCancelCallback();
     extern void   PopupEventHandler();
     
     ac = 0;
     XtSetArg (al[ac], XmNallowShellResize, True); ac++;
     XtSetArg (al[ac], XmNtitle, 
	       catgets (prog->catd, 1, 36, "Image Viewer - Open")); ac++;
     shell = XmCreateDialogShell (parent, "OpenShell", al, ac);
     
     /*
      * Set the directory while creating or we'll be stat'ing the
      * directory twice if we change it again after creating it.
      * That's why we're using XtVaCreateWidget() instead of
      * XmCreateFileSelectionBox() which doesn't take XtVaTypedArgs.
      */
     dialog = XtVaCreateWidget ("OpenDialog", xmFileSelectionBoxWidgetClass,
				shell,
				XtVaTypedArg, XmNdirectory, XtRString,
				prog->directory, strlen (prog->directory) + 1,
				"pathMode", 1,
				XmNautoUnmanage, False,
                                XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL,
				NULL);
     
     XtAddCallback (dialog, XmNcancelCallback, OpenCancelCallback, NULL);
     XtAddCallback (dialog, XmNokCallback, OpenOKCallback, NULL);
     XtAddCallback (dialog, XmNhelpCallback, HelpItemCallback, HELP_OPEN_ITEM);
     /*
      * Set Event handler to cath Maps/Unmaps.
      */
     XtAddEventHandler (shell, StructureNotifyMask, False,
			PopupEventHandler, dialog);
     
     return dialog;
}

/* 
 * Initialize an instance of object `openas_dialog'
 */
OpenAsObjects *
OpenAsObjectsInitialize(parent)
     Widget   parent;
{
     register int  ac = 0;
     Arg           al[16];
     Widget        form; 
     XmString      xmstrings[5];
     OpenAsObjects *o;
     
     extern void   OpenAsOKCallback();
     extern void   OpenAsCancelCallback();
     extern void   PopupEventHandler();
     
     o = (OpenAsObjects *) calloc (1, sizeof (OpenAsObjects));

     ac = 0;
     XtSetArg (al[ac], XmNallowShellResize, True); ac++;
     XtSetArg (al[ac], XmNtitle, 
	       catgets (prog->catd, 1, 37, "Image Viewer - Open As")); ac++;
     o->shell = XmCreateDialogShell (parent, "OpenAsShell", al, ac);
     
     /*
      * Set the directory while creating or we'll be stat'ing the
      * directory twice if we change it again after creating it.
      * That's why we're using XtVaCreateWidget() instead of
      * XmCreateFileSelectionBox() which doesn't take XtVaTypedArgs.
      */
     o->dialog = XtVaCreateWidget ("OpenAsDialog", xmFileSelectionBoxWidgetClass,
			        o->shell,
				XtVaTypedArg, XmNdirectory, XtRString,
				prog->directory, strlen (prog->directory) + 1,
				"pathMode", 1,
				XmNautoUnmanage, False,
                                XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL,
				NULL);
/*
 * Create Form for extra widgets.
 */
     ac = 0;
     XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
     XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
     form = XmCreateForm ( o->dialog, "SaveAsForm", al, ac );
/*
 * Create File Format list label
 */
     ac = 0;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 38,
						      "File Format:"));
     XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
     XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
     XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
     o->format_label = XmCreateLabel (form, "FileFormatLabel", al, ac );
     XmStringFree ( xmstrings [ 0 ] );
/*
 * Create File Format List
 */
     ac = 0;
     XtSetArg(al[ac], XmNvisibleItemCount, 4); ac++; 
     XtSetArg(al[ac], XmNlistSizePolicy, XmRESIZE_IF_POSSIBLE); ac++;
     XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
     XtSetArg(al[ac], XmNtopWidget, o->format_label); ac++;
     XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
     XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
     o->format_list = XmCreateScrolledList (form, "PrinterList", al, ac );

     XtManageChild (o->format_list);
     XtManageChild (o->format_label);
     XtManageChild (form);

     XtAddCallback (o->dialog, XmNcancelCallback, OpenAsCancelCallback, NULL);
     XtAddCallback (o->dialog, XmNokCallback, OpenAsOKCallback, NULL);
     XtAddCallback (o->dialog, XmNhelpCallback, HelpItemCallback, HELP_OPENAS_ITEM);
     /*
      * Set Event handler to cath Maps/Unmaps.
      */
     XtAddEventHandler (o->shell, StructureNotifyMask, False,
			PopupEventHandler, o->dialog);
     return o;
}

/* 
 * Initialize an instance of object `save_dialog'
 */
Widget
SaveObjectsInitialize(parent)
     Widget   parent;
{
     register int  ac = 0;
     Arg           al[16];
     Widget        shell, dialog;
     
     extern void   SaveOKCallback();
     extern void   SaveCancelCallback();
     extern void   PopupEventHandler();
     
     ac = 0;
     XtSetArg (al[ac], XmNallowShellResize, True); ac++;
     XtSetArg (al[ac], XmNtitle, 
	       catgets (prog->catd, 1, 39, "Image Viewer - Save")); ac++;
     shell = XmCreateDialogShell (parent, "SaveShell", al, ac);
     
     /*
      * Set the directory while creating or we'll be stat'ing the
      * directory twice if we change it again after creating it.
      * That's why we're using XtVaCreateWidget() instead of
      * XmCreateFileSelectionBox() which doesn't take XtVaTypedArgs.
      */
     dialog = XtVaCreateWidget ("SaveDialog", xmFileSelectionBoxWidgetClass,
				shell,
				XtVaTypedArg, XmNdirectory, XtRString,
				prog->directory, strlen (prog->directory) + 1,
				"pathMode", 1,
				XmNautoUnmanage, False,
				NULL);
     
     XtAddCallback (dialog, XmNcancelCallback, SaveCancelCallback, NULL);
     XtAddCallback (dialog, XmNokCallback, SaveOKCallback, NULL);
     XtAddCallback (dialog, XmNhelpCallback, HelpItemCallback, HELP_SAVE_ITEM);
     /*
      * Set Event handler to cath Maps/Unmaps.
      */
     XtAddEventHandler (shell, StructureNotifyMask, False,
			PopupEventHandler, dialog);

     return dialog;
}

/* 
 * Initialize an instance of object `saveas_dialog'
 */
SaveAsObjects *
SaveAsObjectsInitialize(parent)
     Widget   parent;
{
     register int   ac = 0;
     Arg            al[16];
     Widget         menu1, menu2;
     XmString       xmstrings[16];   
     Widget         children[24], form;
     SaveAsObjects *s;
     
     extern void   SaveAsOKCallback();
     extern void   SaveAsCancelCallback();
     extern void   SaveFormatListCallback();
     extern void   PopupEventHandler();
     
     s = (SaveAsObjects *) calloc (1, sizeof (SaveAsObjects));

     ac = 0;
     XtSetArg (al[ac], XmNallowShellResize, True); ac++;
     XtSetArg (al[ac], XmNtitle,
               catgets (prog->catd, 1, 40, "Image Viewer - Save As")); ac++;

     s->shell = XmCreateDialogShell (parent, "SaveAsShell", al, ac);
     
     /*
      * Set the directory while creating or we'll be stat'ing the
      * directory twice if we change it again after creating it.
      * That's why we're using XtVaCreateWidget() instead of
      * XmCreateFileSelectionBox() which doesn't take XtVaTypedArgs.
      */
     s->dialog = XtVaCreateWidget ("SaveAsDialog", xmFileSelectionBoxWidgetClass,
				   s->shell,
				   XtVaTypedArg, XmNdirectory, XtRString,
				   prog->directory, strlen (prog->directory) + 1,
				   "pathMode", 1,
				   XmNautoUnmanage, False,
                                   XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL,
				   NULL);
/*
 * Create Form for extra widgets.
 */
     ac = 0;
     XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
     XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
     form = XmCreateForm ( s->dialog, "SaveAsForm", al, ac );
/*
 * Create File Format list label
 */
     ac = 0;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 41,
						      "File Format:"));
     XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
     XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
     XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
     s->format_label = XmCreateLabel (form, "FileFormatLabel", al, ac );
     XmStringFree ( xmstrings [ 0 ] );
/*
 * Create File Format List
 */
     ac = 0;
     XtSetArg(al[ac], XmNvisibleItemCount, 4); ac++; 
     XtSetArg(al[ac], XmNlistSizePolicy, XmRESIZE_IF_POSSIBLE); ac++;
     XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
     XtSetArg(al[ac], XmNtopWidget, s->format_label); ac++;
     XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
     XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
     s->format_list = XmCreateScrolledList (form, "PrinterList", al, ac );
/*
 * Create Compression Menu
 */
     ac = 0;
     XtSetArg (al[ac], XmNpacking, XmPACK_COLUMN); ac++;
     XtSetArg (al[ac], XmNorientation, XmVERTICAL); ac++;
     XtSetArg (al[ac], XmNnumColumns, 1); ac++;
     menu1 = XmCreatePulldownMenu (form, "CompressionPulldown", al, ac);

     ac = 0;
     XtSetArg (al[ac], XmNsubMenuId, menu1); ac++;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 42,
						      "Compression:"));
     XtSetArg (al[ac], XmNlabelString, xmstrings[0]); ac++;
     XtSetArg (al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
     XtSetArg (al[ac], XmNtopWidget, s->format_list); ac++;
     XtSetArg (al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
     s->compression_menu = XmCreateOptionMenu (form, "CompressionOptionMenu", 
					       al, ac); 
     XmStringFree ( xmstrings [ 0 ] );
     XtVaSetValues (XmOptionButtonGadget (s->compression_menu), 
		    XmNuserData, "None", NULL);

     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 43, "None"));
     xmstrings[1] = XmStringCreateLocalized (catgets (prog->catd, 1, 44, "Unix"));
     xmstrings[2] = XmStringCreateLocalized (catgets (prog->catd, 1, 45, "Encoded"));
     xmstrings[3] = XmStringCreateLocalized (catgets (prog->catd, 1, 46, "LZW"));
     xmstrings[4] = XmStringCreateLocalized (catgets (prog->catd, 1, 47, "JPEG"));
     s->none_item = XtVaCreateWidget ("NoneMenuItem", 
				     xmPushButtonGadgetClass, menu1,
				     XmNlabelString, xmstrings[0],
				     NULL);
     s->unix_item = XtVaCreateWidget ("UnixMenuItem", 
				     xmPushButtonGadgetClass, menu1,
				     XmNlabelString, xmstrings[1],
				     NULL);
     s->encoded_item = XtVaCreateWidget ("EncodedMenuItem", 
				     xmPushButtonGadgetClass, menu1,
				     XmNlabelString, xmstrings[2],
				     NULL);
     s->lzw_item = XtVaCreateWidget ("LZWMenuItem", 
				     xmPushButtonGadgetClass, menu1,
				     XmNlabelString, xmstrings[3],
				     NULL);
     s->jpeg_item = XtVaCreateWidget ("JPEGMenuItem", 
				     xmPushButtonGadgetClass, menu1,
				     XmNlabelString, xmstrings[4],
				     NULL);
     XmStringFree ( xmstrings [ 0 ] );
     XmStringFree ( xmstrings [ 1 ] );
     XmStringFree ( xmstrings [ 2 ] );
     XmStringFree ( xmstrings [ 3 ] );
     XmStringFree ( xmstrings [ 4 ] );
/*
 * Create Colors Menu
 */
     ac = 0;
     XtSetArg (al[ac], XmNpacking, XmPACK_COLUMN); ac++;
     XtSetArg (al[ac], XmNorientation, XmVERTICAL); ac++;
     XtSetArg (al[ac], XmNnumColumns, 1); ac++;
     menu2 = XmCreatePulldownMenu (form, "ColorsPulldown", al, ac);

     ac = 0;
     XtSetArg (al[ac], XmNsubMenuId, menu2); ac++;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 48,
						      "Colors:"));
     XtSetArg (al[ac], XmNlabelString, xmstrings[0]); ac++;
     XtSetArg (al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
     XtSetArg (al[ac], XmNtopWidget, s->format_list); ac++;
     XtSetArg (al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
     XtSetArg (al[ac], XmNleftWidget, s->compression_menu); ac++;
     XtSetArg (al[ac], XmNleftOffset, 10); ac++;
     XtSetArg (al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
     XtSetArg (al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
     s->colors_menu = XmCreateOptionMenu (form, "ColorsOptionMenu", 
					       al, ac); 
     XmStringFree ( xmstrings [ 0 ] );
     XtVaSetValues (XmOptionButtonGadget (s->colors_menu), 
		    XmNuserData, "None", NULL);

     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 49, "B&W"));
     xmstrings[1] = XmStringCreateLocalized (catgets (prog->catd, 1, 50, "256"));
     xmstrings[2] = XmStringCreateLocalized (catgets (prog->catd, 1, 51, "Millions"));
     s->bw_item = XtVaCreateWidget ("B&WMenuItem", 
				     xmPushButtonGadgetClass, menu2,
				     XmNlabelString, xmstrings[0],
				     NULL);
     s->colors_256_item = XtVaCreateWidget ("Colors256MenuItem", 
				     xmPushButtonGadgetClass, menu2,
				     XmNlabelString, xmstrings[1],
				     NULL);
     s->colors_millions_item = XtVaCreateWidget ("ColorsMillionsMenuItem", 
				     xmPushButtonGadgetClass, menu2,
				     XmNlabelString, xmstrings[2],
				     NULL);
     XmStringFree ( xmstrings [ 0 ] );
     XmStringFree ( xmstrings [ 1 ] );
     XmStringFree ( xmstrings [ 2 ] );

/*
 * Manage the widgets
 */
     ac = 0;
     children[ac++] = s->none_item;
     children[ac++] = s->unix_item;
     children[ac++] = s->encoded_item;
     children[ac++] = s->lzw_item;
     children[ac++] = s->jpeg_item;
     XtManageChildren (children, ac);

     ac = 0;
     children[ac++] = s->bw_item;
     children[ac++] = s->colors_256_item;
     children[ac++] = s->colors_millions_item;
     XtManageChildren (children, ac);

     XtManageChild (s->format_list);
     ac = 0;
     children[ac++] = s->format_label;
     children[ac++] = s->compression_menu; 
     children[ac++] = s->colors_menu; 
     XtManageChildren (children, ac);
     XtManageChild (form);
     
     s->showing = False;
     s->button_selected = SAVE_UNDEFINED;

     XtAddCallback (s->format_list, XmNbrowseSelectionCallback, 
		    SaveFormatListCallback, NULL);
     XtAddCallback (s->dialog, XmNcancelCallback, SaveAsCancelCallback, NULL);
     XtAddCallback (s->dialog, XmNokCallback, SaveAsOKCallback, NULL);
     XtAddCallback (s->dialog, XmNhelpCallback, HelpItemCallback, 
		    HELP_SAVEAS_ITEM);
     /*
      * Set Event handler to cath Maps/Unmaps.
      */
     XtAddEventHandler (s->shell, StructureNotifyMask, False,
			PopupEventHandler, s->dialog);

     return s;
}
