#ifndef lint
static char sccsid[] = "@(#)printprevui.c 1.10 95/02/22";
#endif

/*
 * Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
 */

/*
 * printprevui.c - User interface object initialization functions
 * for print preview pop up.
 * This file was generated by `gxv' from `imagetool.G'.
 */

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/MessageB.h>
#include <Xm/PushB.h>
#include "DrawingAVis.h"
#include "display.h"
#include "help.h"
#include "imagetool.h" 
#include "ui_imagetool.h"

/*
 * Initialize an instance of object `print_prev'.
 */
PrintPrevObjects *
PrintPrevObjectsInitialize (parent)
     Widget  parent;
{
     Widget             children[6];      /* Children to manage */
     Arg                al[64];           /* Arg List */
     register int       ac = 0;           /* Arg Count */
     XmString           xmstrings[16];    /* temporary storage for XmStrings */
     PrintPrevObjects  *p;
     int                depth, status, vis_class;
     Visual	       *def_visual;
     XVisualInfo        visual_info;
     extern void        pop_open_print();
     extern void        PopupEventHandler();
     extern void        PrintPrevEventHandler();
     extern void        PrintPrevRepaintCallback();
     extern void        PrintPrevInputCallback();
     extern void        PrintPrevPrintCallback();
     extern void        PrintPrevCancelCallback();

     p = (PrintPrevObjects *) calloc (1,sizeof (PrintPrevObjects));
/*
 * Create Shell, Dialog, Forms.
 */	
     ac = 0;
     XtSetArg(al[ac], XmNtitle, catgets (prog->catd, 1, 168, 
				"Image Viewer - Print Preview")); ac++;
     p->shell = XmCreateDialogShell ( parent, "PrintPrevShell", al, ac );
/*
 * Create Message Dialog Box
 */
     ac = 0;
     XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
     XtSetArg(al[ac], XmNdialogType, XmDIALOG_TEMPLATE); ac++;	
     XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
     XtSetArg(al[ac], XmNmarginHeight, 0); ac++; 
     XtSetArg(al[ac], XmNnoResize, TRUE); ac++;
     p->dialog = XmCreateMessageBox (p->shell, "PrintPrevDialog", al, ac );
/*
 * Add event handler to catch Maps/Unmaps.
 */
     XtAddEventHandler (p->shell, StructureNotifyMask, False,
			PopupEventHandler, p->dialog);
/*
 * Create Form
 */
     ac = 0;
     XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
     XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
     XtSetArg(al[ac], XmNmarginHeight, 0); ac++; 
     p->form = XmCreateForm ( p->dialog, "PrintPrevForm", al, ac );
/*
 * Create the drawing area.
 */
     XtVaGetValues (current_display->new_canvas, XmNdepth, &depth, NULL);
     vis_class = canvas_visual_class (depth);
/*
 * Get the visual that matches this depth and visual class.
 */
     status = XMatchVisualInfo (current_display->xdisplay, 
				DefaultScreen (current_display->xdisplay), depth, 
				vis_class, &visual_info);
/*
 * If visual desired not found, use default visual.
 */
     if (status == 0) {
       Visual             *def_visual;
       int		   def_depth;
       XtVaGetValues (base->scrolledw, XmNdepth, &def_depth, NULL);
       def_visual = DefaultVisual (current_display->xdisplay, 
				   DefaultScreen (current_display->xdisplay));
       status = XMatchVisualInfo (current_display->xdisplay, 
				  DefaultScreen (current_display->xdisplay), 
				  def_depth, def_visual->class, &visual_info);
       depth = def_depth;
       if (status == 0)
	 fprintf (stderr, catgets (prog->catd, 1, 383, 
			  "Could not find visual to display image.\n"));
     }

     p->page = XtVaCreateManagedWidget ("PrintPrevCanvas",
			xmDrawingAreaVisWidgetClass, p->form,
			XmNvisual, visual_info.visual,
 			XmNdepth, depth,
			XmNheight, PRINT_PREVIEW_PAGE_FACTOR * 11,
			XmNtopAttachment, XmATTACH_FORM,
			XmNleftAttachment, XmATTACH_FORM,
			XmNrightAttachment, XmATTACH_FORM,
			XmNbottomAttachment, XmATTACH_FORM, 
			NULL);
/*
 * Change the cursor for the Print Preview drawing area
 */
     if (!cursor)
       cursor = CursorObjectsInitialize (base->top_level);

     XtAddCallback (p->page, XmNexposeCallback, PrintPrevRepaintCallback, p);
/*
 * Install Callback to catch first button clock
 */
     XtAddCallback (p->page, XmNinputCallback, PrintPrevInputCallback, p);
	
/*
 * Install event handler for Button1Motion events.
 */
     XtAddEventHandler (p->page, Button1MotionMask, False, 
			PrintPrevEventHandler, p);

/*
 * Create Print Button
 */
     ac = 0;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 169, 
						      "Print..."));
     XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
     p->print_button = XmCreatePushButton (p->dialog, "PrintPrevPrintButton", 
					   al, ac ); 
     XmStringFree ( xmstrings [ 0 ] );

/*
 * Create Cancel Button
 */
     ac = 0;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 170, 
						      "Close"));
     XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
     p->cancel_button = XmCreatePushButton (p->dialog, "PrintPrevCancelButton", 
					    al, ac );
     XmStringFree ( xmstrings [ 0 ] );
/*
 * Create Help Button
 */
     ac = 0;
     xmstrings[0] = XmStringCreateLocalized (catgets (prog->catd, 1, 171, 
						      "Help"));
     XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
     p->help_button = XmCreatePushButton (p->dialog, "PrintPrevHelpButton", 
					  al, ac );
     XmStringFree ( xmstrings [ 0 ] );
/*
 * Set Print to be default button
 */
     XtVaSetValues (p->dialog, XmNdefaultButton, p->print_button, 
		               XmNminimizeButtons, True, NULL);

     p->showing = False;
/*
 * Set help callback on dialog
 */
     XtAddCallback (p->dialog, XmNhelpCallback, HelpItemCallback, 
		    HELP_PRINTPREV_ITEM);
/*
 * Set callbacks on buttons
 */
     XtAddCallback (p->print_button, XmNactivateCallback, 
		    PrintPrevPrintCallback, p);
     XtAddCallback (p->cancel_button, XmNactivateCallback, 
		    PrintPrevCancelCallback, p);
     XtAddCallback (p->help_button, XmNactivateCallback, HelpItemCallback, 
		    HELP_PRINTPREV_ITEM);
/*
 * Manage the children
 */
     XtManageChild (p->page);
     ac = 0;
     children[ac++] = p->form;
     children[ac++] = p->print_button;
     children[ac++] = p->cancel_button;
     children[ac++] = p->help_button;
     XtManageChildren(children, ac);

     return p;
}

/*
 * Print callback (pops open print pop up)
 */

void
PrintPrevPrintCallback (w, client_data, call_data)
     Widget     w;
     XtPointer  client_data;
     XtPointer  call_data;
{
     Boolean    set_min = False;
     
     if (printer_exists () == TRUE) {
       setbusy();
       if (print == (PrintObjects *) NULL) {
	 print = PrintObjectsInitialize (base->top_level);
	 set_min = True;

	 if (current_display == ps_display)
	   set_ps_print_options ();
	 else 
	   set_image_print_options ();
	 
	 update_margins ();
       }

       ShowDialog (print->dialog, print->showing);
       if (set_min == True) {
	 Dimension  width, height;
	 XtVaGetValues (print->shell, XmNwidth, &width, 
			              XmNheight, &height, NULL);
	 XtVaSetValues (print->shell, XmNminWidth, width,
		                      XmNminHeight, height, NULL);
       }
       setactive();
     }

}

void
PrintPrevCancelCallback (w, client_data, call_data)
     Widget     w;
     XtPointer  client_data;
     XtPointer  call_data;
{
     PrintPrevObjects *p = (PrintPrevObjects *)client_data;

     XtPopdown (XtParent (p->dialog));
}

void 
resize_print_prev (p, xpages, ypages, width, height)
     PrintPrevObjects	*p;
     int	 	 xpages;
     int	 	 ypages;
     float		 width;
     float		 height;
{
     Dimension canvas_width = (Dimension) (xpages * width * 
					   PRINT_PREVIEW_PAGE_FACTOR);
     Dimension canvas_height = (Dimension) (ypages * height * 
					    PRINT_PREVIEW_PAGE_FACTOR);
     
     XtVaSetValues (p->form, XmNwidth, canvas_width,
 		             XmNheight, canvas_height, NULL);
     XtVaSetValues (p->page, XmNwidth, canvas_width,
 		             XmNheight, canvas_height, NULL);
     XSync (image_display->xdisplay, 0);

     XtVaSetValues (p->shell, 
		    XmNwidth, (Dimension) (canvas_width + p->extra_width),
		    XmNheight, (Dimension) (canvas_height + p->extra_height),
		    NULL);
}
