/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: sdtimage_snap.c
 * Contains: dtb_sdtimage_snap_initialize and cross-module connections
 *
 * This file was generated by dtcodegen, from project sdtimage_snap
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <X11/Intrinsic.h>
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/Protocols.h>
#include <Dt/Help.h>
#include <Dt/HelpQuickD.h>
#include <Dt/HelpDialog.h>
#include <nl_types.h>
#include "snap_dialog.h"
#include "sdtimage_snap.h"
#include "dtb_utils.h"


/* Handle for standard message catalog for the project */
nl_catd	Dtb_project_catd = (nl_catd)-1;

DtbAppResourceRec	dtb_app_resource_rec;


/*
 * initialization for application sdtimage_snap
 * This should be called from user-defined main()
 */
int
dtb_sdtimage_snap_initialize(
    int *argc_in_out,
    char **argv_in_out[],
    Widget toplevel
)
{
    #define argc (*argc_in_out)
    #define argv (*argv_in_out)
    XtLanguageProc	language_proc = (XtLanguageProc)NULL;
    XtPointer		language_proc_client_data = (XtPointer)NULL;



    /*
     * Get display and verify initialization was successful.
     */
    if (toplevel == NULL)
      {
        fprintf(stderr, "\nWARNING: dtb_sdtimage_snap_initialize() called with invalid widget.\n");
        fprintf(stderr, "Initialization failed.\n\n");
        return -1;
    }
    
    /*
     * Open the standard message catalog for the project.
     */
    Dtb_project_catd = catopen(DTB_PROJECT_CATALOG, NL_CAT_LOCALE);
    if (Dtb_project_catd == (nl_catd)-1)
    {
        fprintf(stderr, "WARNING: Could not open message catalog: %s. Messages will be defaults.\n",
            DTB_PROJECT_CATALOG);
    }

    /*
     * Save the toplevel widget so it can be fetched later as needed.
     */
    dtb_save_toplevel_widget(toplevel);

    /*
     * Save the command used to invoke the application.
     */
    dtb_save_command(argv[0]);


    /*
     * Initialize all global variables.
     */
    dtbSnapDlogDialogInfo_clear(&dtb_snap_dlog_dialog);


    return 0;
    #undef argc
    #undef argv
}
