/* $XConsortium: AccessCCDFP.h /main/cde1_maint/1 1995/07/17 17:18:05 drk $ */
/************************************<+>*************************************
 ****************************************************************************
 **
 **   File:        AccessCCDFP.h
 **
 **   Project:     Run Time Project File Access
 **
 **  
 **   Description: Private header file for AccessCCDFP.h
 **
 **  (c) Copyright 1987, 1988, 1989, 1990, 1991, 1992 Hewlett-Packard Company
 **
 **  (c) Copyright 1993, 1994 Hewlett-Packard Company
 **  (c) Copyright 1993, 1994 International Business Machines Corp.
 **  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
 **  (c) Copyright 1993, 1994 Novell, Inc.
 **
 **
 ****************************************************************************
 ************************************<+>*************************************/
#ifndef _DtAccessCcdfP_h
#define _DtAccessCcdfP_h

/*
 * The following structure holds loaded volumes.  The fields of this 
 * structure should not be accessed by any code outside of the volume
 * module.
 */
struct _CcdfVolumeInfo {
    XrmDatabase volDb;		/* A pointer to the Resource Manager */
				/* database that was loaded from the */
				/* volume file.  */

    char **topicList;		/* A pointer to a string array containing */
				/* the locationIDs for all of the topics */
				/* in the volume.  This array is not created */
				/* until the first time it is needed. */

    char *keywordFile;		/* A pointer to the name of the keyword */
				/* file.  This name is generated by */
				/* adding "k" to the end of volFile. */
				/* This filename is not generated until */
				/* the first time it is needed. */
};

typedef struct _CcdfVolumeInfo *CcdfVolumePtr;

#endif /* _DtAccessCcdfP_h */
