#! /bin/ksh
MACHINE=`uname -m`

  if [ "$MACHINE" = "i86pc" ];then
    exec /x/cdesrc/admin/BuildTools/gnumake/gnumake.UNIX_SV "$@"
  else
    exec /x/cdesrc/admin/BuildTools/gnumake/gnumake.$(uname -s) "$@"
  fi

