.\" @ (#) Intro.1
.\" Introduction section for ToolTalk 1.3 Reference Manual
.TH Intro 1 "1 March 1996" "ToolTalk 1.3" "ToolTalk Commands"
.BH "1 March 1996"
.\" (c) Copyright 1996 Sun Microsystems, Inc.
.IX "Tooltalk Commands" "" "Tooltalk Commands" ""
.SH NAME
Intro \- introduction to the ToolTalk commands and application programs.
.SH OVERVIEW
This section describes commands which are used by ToolTalk or the
Tooltalk developer to monitor ToolTalks' passing of  messages, or
to interact with ToolTalks' storage of message data on disk.
