.de LI
.\" simulate -mm .LIs by turning them into .TPs
.TP \\n()Jn
\\$1
..
.TH ttrm 1 "1 March 1996" "ToolTalk 1.3" "ToolTalk Commands"
.BH "1 March 1996"
.\" CDE Common Source Format, Version 1.0.0
.\" (c) Copyright 1993, 1994 Hewlett-Packard Company
.\" (c) Copyright 1993, 1994 International Business Machines Corp.
.\" (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\" (c) Copyright 1993, 1994 Novell, Inc.
.IX "ttrm" "" "ttrm.1" ""
.SH "NAME"
ttrm \- remove files or directories and inform the ToolTalk service
.SH "SYNOPSIS"
.ft 3
.fi
.na
ttrm
[\(mifrL]
\f2pathname\fP
\&.\|.\|.
.PP
.fi
.ft 3
.fi
.na
ttrm
\(mih
\(bv
\(miv
.PP
.fi
.SH "DESCRIPTION"
The
.BR ttrm 
utility
invokes
.BR rm (1)
to remove files and directories and informs
ToolTalk about its actions so that the ToolTalk objects
associated with the deleted files and directories can also be deleted.
.PP
The
.BR ttrm 
utility
removes the ToolTalk objects before it removes the files and does not
check whether the file-removing operation will succeed before performing
the object-removing operation.
.SH "OPTIONS"
The following options are available:
.PP
.RS 3
.nr )J 6
.LI \f3\(mif\f1
Force.
Do not report any errors, and pass the
.B \(mif
option to
.BR rm (1).
.LI \f3\(mih\f1
Write a help message for invoking
.BR ttrm 
and then exit.
.LI \f3\(miL\f1
Remove the ToolTalk objects of the files or directories, but do not invoke
.BR rm (1)
to remove the actual files or directories.
.LI \f3\(mir\f1
Recursively remove the ToolTalk objects of any directories named,
along with their files (including any
subdirectories and their files), and pass the
.B \(mir
option to
.BR rm (1).
.LI \f3\(miv\f1
Write the version number of
.BR ttrm 
and then exit.
.PP
.RE
.nr )J 0
.PP
The
.B \(mii
or
.B \(miR
options to
.BR rm (1)
are not supported.
.SH OPERANDS
The following operand is supported:
.PP
.RS 3
.nr )J 6
.LI \f2pathname\fP
.br
A pathname of a file to be removed.
.PP
.RE
.nr )J 0
.SH STDIN
Not used.
.SH "INPUT FILES"
The input files specified as operands can be of any file type.
.SH "ENVIRONMENT VARIABLES"
The following environment variables affect the execution of
.BR ttrm :
.PP
.RS 3
.nr )J 15
.LI \f2LANG\fP
Provide a default value for the internationalization variables
that are unset or null.
If
.I LANG
is unset or null, the corresponding value from the
implementation-specific default locale will be used.
If any of the internationalization variables contains an invalid setting, the
utility behaves as if none of the variables had been defined.
.LI \f2LC_ALL\fP
If set to a non-empty string value,
override the values of all the other internationalization variables.
.LI \f2LC_MESSAGES\fP
Determine the locale that is used to affect
the format and contents of diagnostic
messages written to standard error
and informative messages written to standard output.
.LI \f2NLSPATH\fP
Determine the location of message catalogues
for the processing of
.IR LC_MESSAGES .
.PP
.RE
.nr )J 0
.SH "RESOURCES"
None.
.SH "ASYNCHRONOUS EVENTS"
The
.BR ttrm 
utility takes the standard action for all signals.
.SH STDOUT
When the
.B \(mih
option is used,
.BR ttrm 
writes to standard output a help message
in an unspecified format.
.PP
When the
.B \(miv
option is used,
.BR ttrm 
writes to standard output a version number
in an unspecified format.
.SH STDERR
Used only for diagnostic messages.
.SH "OUTPUT FILES"
None.
.SH "EXTENDED DESCRIPTION"
None.
.SH "EXIT STATUS"
The following exit values are returned:
.PP
.RS 3
.nr )J 4
.LI \h"\w'>'u"0
All files and ToolTalk objects were removed successfully.
.LI >0
An error occurred or the invoked
.BR rm (1)
command exited with a non-zero value.
.PP
.RE
.nr )J 0
.SH "CONSEQUENCES OF ERRORS"
Default.
.SH FILES
.TP 20
/\f2mountpoint\fP/TT_DB
The directory used as a database
for the ToolTalk objects of files in the
file system mounted at
.IR /mountpoint .
.SH "APPLICATION USAGE"
None.
.SH EXAMPLES
None.
.SH "SEE ALSO"
.na
.BR rm (1),
.BR ttrmdir (1),
.BR ttsession (1).
