.\" Copyright 1994, The X/Open Company Ltd.
.ds SI @(#) 1.2 94/12/19
.H 1 "Terminal Emulation Services"
.nr Ej 1
.xR1 termsvcs
.H 2 "Introduction"
.mc 3
The \*(Zx terminal emulation services provide a
window for applications written for character-based terminals such as
the VT220.
These applications include XPG4 commands, shell scripts, and other
applications not written for an X Windows environment.
The services are available in two forms:
a stand-alone
client and a widget that can be used inside applications that require
terminal emulation.
.P
The \*(Zx terminal emulation services are consistent with
the \*(Z5 and the \*(Z6.
The services are based in part on the X Consortium's
.Cm xterm
and popular terminals compatible with the VT220.
.P
The user interface is consistent with the \*(ZY, so the client and widget
blend well on a screen populated by windowed applications.
.br
.mc
.H 2 "Functions" S
.xR2 termfuncs
This section defines the functions, macros and
external variables that provide \*(Zx terminal emulation services
to support application portability at the C-language source level.
.so ../fx/DtCreateTerm.mm
.so ../fx/DtTermDisplaySend.mm
.so ../fx/DtTermInitialize.mm
.so ../fx/DtTermSubprocReap.mm
.so ../fx/DtTermSubprocSend.mm
.ds XC Widgets
.SK
.H 2 "Widgets" S
This section defines the widget class
that provides the widget used by the \*(Zx terminal emulation services
to support application portability at the C-language source level.
.so ../fx/DtTerm.mm
.ds XC Headers
.SK
.H 2 "Headers" S
This section describes the contents of headers used
by the \*(Zx terminal emulation functions, macros and external variables.
.P
Headers contain the definition of symbolic constants, common structures,
preprocessor macros and defined types.
Each function in
.cX termfuncs "" 1
specifies the headers that an application must include in order to use
that function.
In most cases only one header is required.
These headers are present on an application development
system; they do not have to be present on the target execution system.
.so ../hx/DtTerm.mm
.ds XC Command-Line Interfaces
.SK
.H 2 "Command-Line Interfaces"
This section defines the utilities that provide
\*(Zx terminal emulation services.
.so ../fx/dtterm.mm
.ds XC Actions
.SK
.mc 6
.H 2 "Actions"
This section defines the actions that provide \*(Zx terminal emulation services
to support application portability at the C-language source
or shell script levels.
.so ../hx/dttermaction.mm
.ds XC Formats
.SK
.mc
.H 2 "Formats"
.xR2 termformats
.so ../hx/dtterm.mm
.ds XC Capabilities
.SK
.H 2 "Capabilities"
A conforming implementation of the \*(Zx terminal emulation services
supports at least the following capabilities:
.AL
.LI
Provides users with a window that behaves like a terminal supporting the
escape sequences specified in
.cX termformats ,
which are consistent with the the \*(Z5 and the \*(Z6.
.LI
.mc 5
Conforms to the Required items in the Application Style Checklist in
.cX checklist .
.LI
.mc
Has been internationalised using the standard interfaces
in the \*(ZK, the \*(Zl, and the \*(ZM,
and supports any locale available in the underlying X Window System
Xlib implementation.
.LI
Allows users to customise the window in at least the following ways:
.AL a
.LI
Visibility of the cursor (visible or invisible)
.LI
Shape of the cursor (box or underline)
.LI
Blinking of the cursor (blinking on or off)
.LI
Type of scrolling (smooth scrolling or jump scrolling)
.LI
Type of bell (audible or visual)
.LI
Enabling the margin bell (enable or disable)
.LI
Position of the right margin for the margin bell
.LI
Control sequences generated by the keyboard and numeric pad
(normal or application)
.LI
Locking the user-defined function keys (lock or unlock)
.LI
End-of-line wrapping (enable or disable)
.LI
Reverse end-of-line wrapping (enable or disable)
.LI
Selection of end-of-line character to generate (carriage return or carriage
return/linefeed)
.LI
Size of the terminal window
.LI
Normal or reverse-video operation
.LI
Size of the font used for terminal operation
.LE
.LI
Supports the command-line options, resources and environment variables
described in the man page
.Cm dtterm .
.LI
Supports copy and paste operations for text.
.LI
Supports both soft and hard resets.
.LI
Supports \*(Zx font naming conventions for interface fonts,
as described in
.cX fontconv .
.LE
.H 2 "Rationale and Open Issues" S
.I
The following is text copied from the
.R
CDE X/Open Specification Framework Proposal, Draft 2.
.I
It is not intended to remain in this specification when it is published
by X/Open.
.R
.P
APIs are required for application portability.
.mc 1
The format of the escape sequences is required for interoperability.
.mc 6
CLIs and Actions are required for application portability.
Actions are included in addition to the CLI because the CLI
has numerous command-line options to control its operation.
Capabilities are required to
ensure that conforming implementations provide the minimum expected
.mc
services, without overly constraining tool design.
.P
.mc 3
The \*(Zx terminal emulation services are
based in part on the X Consortium's xterm and in part on a
widget architecture developed by HP.
Xterm is not wholly adopted
because it is not based on Motif, does not conform to the DT/CUA user
model, is not fully internationalised, has been announced to be mature
code by the X Consortium with no further enhancements planned for it by
that body, and contains space-consuming non-ANSI TEK 4014 graphics
terminal emulation that is not sufficiently documented or maintained by
the X Consortium, or sufficiently used by customers, to justify
inclusion in CDE.
.br
.mc
.eF e
