
#
#	$Revision: 1.1 $
#
#  @(#)Makefile.old	1.84 01/17/94	cde_app_builder/src/ab
#
# 	RESTRICTED CONFIDENTIAL INFORMATION:
#	
#	The information in this document is subject to special
#	restrictions in a confidential disclosure agreement between
#	HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
#	document outside HP, IBM, Sun, USL, SCO, or Univel without
#	Sun's specific written approval.  This document and all copies
#	and derivative works thereof must be returned or destroyed at
#	Sun's request.
#
#	Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
#
#

# Remove when not needed.
CDE_EXTRA_STUFF = /net/onebit/export/ow2/app_builder_dev_env

PROJECTDIR = ../..

LIBPART	  =	ab

SOURCES.c = \
		ab_uil.c	\
		ab_bil.c	\
		ab_dnd.c	\
		ab_globals.c	\
                abobj_align.c   \
                abobj_events.c  \
                abobj_layout.c  \
                abobj_menu.c    \
                abobj_move.c    \
                abobj_resize.c  \
                abobj_select.c  \
                abobj_set.c     \
		abobj_util.c	\
		brws.c		\
		brws_mthds.c	\
		brws_utils.c	\
		cgen.c		\
		group.c		\
		help.c		\
		layout.c	\
		pal.c		\
		pal_create.c	\
		pal_basewin.c	\
		pal_button.c	\
		pal_choice.c	\
		pal_cpanel.c	\
		pal_custdlg.c	\
		pal_graphp.c	\
		pal_label.c	\
		pal_list.c	\
		pal_menu.c	\
		pal_menubar.c	\
		pal_termp.c	\
		pal_textf.c	\
		pal_textp.c	\
		proj.c		\
		proj_utils.c	\
		prop.c		\
		ttalk.c		\
		conn.c	\
		conn_drag.c	\
		conn_obj.c	\
		conn_interpret.c	\
		ui_util.c	\
		vwr.c		\
		x_util.c

SOURCES.h.shipped = \

SOURCES.h.shared = \
		ab.h		\
		abobj.h		\
		abobj_set.h	\
		abobjP.h	\
		ab_bil.h	\
		ab_dnd.h	\
		brws.h		\
		brwsP.h		\
		cgen.h		\
		pal.h		\
		proj.h		\
		projP.h		\
		prop.h		\
		conn.h	\
		connP.h	\
		ui_util.h	\
		vwr.h		\
		x_util.h


SOURCES.h.unshared = \
		abobjP.h

SOURCES.h = \
		$(SOURCES.h.shipped)			\
		$(SOURCES.h.shared)			\
		$(SOURCES.h.unshared)

SOURCES.uil = \
		brws.uil				\
		cgen.uil				\
		conn.uil			\
		group.uil				\
		help.uil				\
		layout.uil				\
		ab_palette_main.uil			\
		proj.uil				\
		ttalk.uil				

SOURCES.xres = \
		Ab

SOURCES.misc = \
		app_builder.hlp

IMAGES = \
		bitmaps/ab_default_item.xbm		\
		bitmaps/align_bottom.xbm		\
		bitmaps/align_grid.xbm			\
		bitmaps/align_hcenter.xbm		\
		bitmaps/align_labels.xbm		\
		bitmaps/align_left.xbm			\
		bitmaps/align_right.xbm			\
		bitmaps/align_top.xbm			\
		bitmaps/align_vcenter.xbm		\
		bitmaps/attach_form.xbm			\
		bitmaps/attach_none.xbm			\
		bitmaps/attach_opposite_widget_bottom.xbm \
		bitmaps/attach_position_top.xbm		\
		bitmaps/attach_widget.xbm		\
		bitmaps/attach_xy.xbm			\
		bitmaps/basewin.xbm			\
		bitmaps/black16.xbm			\
		bitmaps/canvaspane.xbm			\
		bitmaps/chooser.xbm			\
		bitmaps/command.xbm			\
		bitmaps/container.xbm			\
		bitmaps/controlarea.xbm			\
		bitmaps/copy_cursor.xbm			\
		bitmaps/distribute_center.xbm		\
		bitmaps/distribute_hcenter.xbm		\
		bitmaps/distribute_horizontal.xbm	\
		bitmaps/distribute_left.xbm		\
		bitmaps/distribute_hcenter.xbm		\
		bitmaps/distribute_right.xbm		\
		bitmaps/distribute_vcenter.xbm		\
		bitmaps/distribute_vertical.xbm		\
		bitmaps/drawarea.xbm			\
		bitmaps/fsb.xbm				\
		bitmaps/ggp_as_is.xbm			\
		bitmaps/ggp_col.xbm			\
		bitmaps/ggp_row.xbm			\
		bitmaps/ggp_rowcol.xbm			\
		bitmaps/menubar.xbm			\
		bitmaps/messagebox.xbm			\
		bitmaps/move_cursor.xbm			\
		bitmaps/panedwin.xbm			\
		bitmaps/popupwin.xbm			\
		bitmaps/printbox.xbm			\
		bitmaps/revolving.xbm			\
		bitmaps/rowcolumn.xbm			\
		bitmaps/scrollwin.xbm			\
		bitmaps/selectionbox.xbm		\
		bitmaps/selection_box.xbm		\
		bitmaps/termpane.xbm			\
		bitmaps/term_pane.xbm			\
		bitmaps/textpane.xbm			\
		bitmaps/text_pane.xbm			\
		bitmaps/copy_cursor_bm			\
		bitmaps/left_up_link.xbm		\
		bitmaps/right_up_link.xbm		\
		bitmaps/right_down_link.xbm		\
		bitmaps/left_down_link.xbm		\
		bitmaps/ab.pm				\
		bitmaps/basewin.pm			\
		bitmaps/command.pm			\
		bitmaps/container.pm			\
		bitmaps/drawarea.pm			\
		bitmaps/ex_choice.s.pm			\
		bitmaps/non_ex_choice.s.pm		\
		bitmaps/fontbox.pm			\
		bitmaps/fsb.pm				\
		bitmaps/messagebox.pm			\
		bitmaps/panedwin.pm			\
		bitmaps/popupwin.pm			\
		bitmaps/printbox.pm			\
		bitmaps/scrollwin.pm			\
		bitmaps/selection_box.pm		\
		bitmaps/term_pane.pm			\
		bitmaps/text_pane.pm			\
		bitmaps/basewin.s.pm			\
		bitmaps/container.s.pm			\
		bitmaps/drawarea.s.pm			\
		bitmaps/module.s.pm			\
		bitmaps/popupwin.s.pm			\
		bitmaps/text_pane.s.pm			\
		bitmaps/ab_b_def.s.pm			\
		bitmaps/pushbutton.s.pm			\
		bitmaps/cascade.s.pm			\
		bitmaps/textfield.s.pm			\
		bitmaps/menubar.s.pm			\
		bitmaps/pulldown.s.pm			\
		bitmaps/list.s.pm			\
		bitmaps/option_menu.s.pm		\
		bitmaps/bilfile.s.pm			\
		bitmaps/bilfile.l.pm

PROGRAM = ab

ULIBDIR		= $(PROJECTDIR)/src/lib

CPPFLAGS        +=  -I$(MOTIFHOME)/include -I$(OPENWINHOME)/include -I$(CDE_EXTRA_STUFF)/include

LDFLAGS		+=  -L$(MOTIFHOME)/lib -L$(CDE_EXTRA_STUFF)/lib

ULIBS		+= \
		$(ULIBDIR)/libABil.a \
		$(ULIBDIR)/libABobjXm.a \
		$(ULIBDIR)/libABobj.a

X_LIBS		= -lXm -lDtWidget -lDtTerm -lDtHelp -lDtSvc -lXpm -lUil -lMrm -lbento -lXt -lX11 -lnsl
LDLIBS		= $(X_LIBS) -lgen -lC -lm

.PARALLEL: $(PROGRAM)
.INIT:  $(PROJECTDIR)/Makefile.include
include $(PROJECTDIR)/Makefile.include
