/*** DTB_USER_CODE_START vvv Add file header below vvv ***/


/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: sdtformat_floppy_stubs.c
 * Contains: Module callbacks and connection functions
 *
 * This file was generated by dtcodegen_build, from module sdtformat_floppy
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <stdio.h>
#include <Xm/Xm.h>
#include "dtb_utils.h"
#include "sdtformat_floppy.h"
#include "sdtformat_floppy_ui.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/

#include <unistd.h>
#include <sys/param.h>
#include <Xm/Text.h>
extern "C" {
#include <Dt/HourGlass.h>
}
#include "format_floppy.h"

static char *vol_label;
static int button_pushed;
static char buf[MAXPATHLEN];
 
void
run_cmd(char *command, int root)
{
	int pid;
	int stat_loc;

    switch (pid = fork()) {
        case -1:   /* Error */
            perror("fork");
            _exit(1);
        case 0:    /* Inside child */
            if ( root == 0) {
                setuid(0);
            }
            execl("/bin/sh", "sh", "-c", command, (char *)0);
            _exit(2);
        default:   /* Back in parent */
            if ( wait(&stat_loc) < 0 ) {
                perror("wait");
            }
    }
}

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



void 
sdtformat_floppy_button2_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

exit(0);

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_textfield_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

vol_label = XmTextGetString(widget);

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_button_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSdtformatFloppyMainwindowInfo	dtbTarget = (DtbSdtformatFloppyMainwindowInfo)clientData;
    DtbSdtformatFloppyMainwindowInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_sdtformat_floppy_mainwindow_initialize(dtbTarget, dtb_get_toplevel_widget());
    }

    XtSetSensitive(instance->textfield_rowcolumn, False);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_button_CB2(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSdtformatFloppyMainwindowInfo	dtbTarget = (DtbSdtformatFloppyMainwindowInfo)clientData;
    DtbSdtformatFloppyMainwindowInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_sdtformat_floppy_mainwindow_initialize(dtbTarget, dtb_get_toplevel_widget());
    }

    XtSetSensitive(instance->optionmenu_rowcolumn, False);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_button_CB3(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSdtformatFloppyMainwindowInfo	dtbTarget = (DtbSdtformatFloppyMainwindowInfo)clientData;
    DtbSdtformatFloppyMainwindowInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_sdtformat_floppy_mainwindow_initialize(dtbTarget, dtb_get_toplevel_widget());
    }

    XtSetSensitive(instance->button3, False);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_button_CB4(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSdtformatFloppyMainwindowInfo	dtbTarget = (DtbSdtformatFloppyMainwindowInfo)clientData;
    DtbSdtformatFloppyMainwindowInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_sdtformat_floppy_mainwindow_initialize(dtbTarget, dtb_get_toplevel_widget());
    }

    XtSetSensitive(instance->button2, False);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_button_CB5(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSdtformatFloppyMainwindowInfo	dtbTarget = (DtbSdtformatFloppyMainwindowInfo)clientData;
    DtbSdtformatFloppyMainwindowInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_sdtformat_floppy_mainwindow_initialize(dtbTarget, dtb_get_toplevel_widget());
    }

    XtSetSensitive(instance->button, False);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_button_CB6(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/


char *dir;
int x =0;


    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

x = x + 1;

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/

_DtTurnOnHourGlass( widget );
if ( (dir = (char *)getenv("DESKSETHOME")) != NULL) {
	sprintf(buf, "%s/ff.core %d %d %s %s ", dir, popup_type, button_pushed, rawdev, mntpt);
}else if ( (dir = (char *)getenv("OPENWINHOME")) != NULL) {
	sprintf(buf, "%s/bin/ff.core %d %d %s %s ", dir, popup_type, button_pushed, rawdev, mntpt);
}else {
	fprintf(stderr, "Cannot locate ff.core\n");
}

if ( (vol_label != NULL) && (strlen(vol_label) > 0) ) {
		strcat(buf, vol_label);
	}
	
run_cmd(buf, 0);

exit(0);    



    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_optionmenu_UNIX_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

button_pushed = 0;

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/



    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_optionmenu_DOS_High_Density_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

button_pushed = 1;

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_optionmenu_NEC_DOS_Medium_Density_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

button_pushed = 2;

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sdtformat_floppy_mainwindow_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    DtbSdtformatFloppyMainwindowInfo	dtbSource = (DtbSdtformatFloppyMainwindowInfo)callData;
    
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    

button_pushed = 0;
vol_label="";

    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
CancelAndEject(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    sprintf( buf, "/bin/eject %s", rawdev );
    run_cmd( buf, 0 );
    exit( 2 );
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}



/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/
 

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


