/*** DTB_USER_CODE_START vvv Add file header below vvv ***/

/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: sdtformat_floppy.c
 * Contains: main() and cross-module connections
 *
 * This file was generated by dtcodegen_build, from project sdtformat_floppy
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <X11/Intrinsic.h>
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/Protocols.h>
#include <Dt/Help.h>
#include <Dt/HelpQuickD.h>
#include <Dt/HelpDialog.h>
#include <nl_types.h>
#include "sdtformat_floppy_ui.h"
#include "sdtformat_floppy.h"
#include "dtb_utils.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/

#include <fcntl.h>
#include <sys/param.h>
#include "format_floppy.h"

char rawdev[MAXPATHLEN], mntpt[MAXPATHLEN];
Popup_Type popup_type = Format;

const char usage[] =
"Usage: sdtformat_floppy -d raw_device -m mount_point [-p popup]\n"
"where popup = {format, unlabeled, or unformatted}\n"
"default for popup is format\n";

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



/* Workaround for XPG4 API compatibility */
#if !defined(NL_CAT_LOCALE)
#define NL_CAT_LOCALE 0
#endif

/* Handle for standard message catalog for the project */
nl_catd	Dtb_project_catd = (nl_catd)-1;

/*
 * command line options...
 */
static XrmOptionDescRec optionDescList[] = {
    {"-session", "*session", XrmoptionSepArg, (XPointer)NULL}
    
    /*** DTB_USER_CODE_START vvv Add structure fields below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add structure fields above ^^^ ***/
};

/*
 * Application Resources
 */
static XtResource resources[] = {
    {"session", "Session", XtRString, sizeof(String),
        XtOffsetOf(DtbAppResourceRec, session_file), XtRImmediate, (XtPointer)NULL}
    
    /*** DTB_USER_CODE_START vvv Add structure fields below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add structure fields above ^^^ ***/
};

DtbAppResourceRec	dtb_app_resource_rec;


/*
 * main for application sdtformat_floppy
 */
int 
main(
    int argc,
    char **argv
)
{
    Widget		toplevel = (Widget)NULL;
    XtAppContext	app = (XtAppContext)NULL;
    String		*fallback_resources = (String*)NULL;
    ArgList		init_args = (ArgList)NULL;
    Cardinal		num_init_args = (Cardinal)0;
    ArgList		get_resources_args = (ArgList)NULL;
    Cardinal		num_get_resources_args = (Cardinal)0;
    XtLanguageProc	language_proc = (XtLanguageProc)NULL;
    XtPointer		language_proc_client_data = (XtPointer)NULL;
    Pixmap	icon_pixmap = NULL;
    Pixmap	icon_mask_pixmap = NULL;
    
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***  No initialization has been done.
     ***
     *** Add local variables and code.
     ***/
    
int arg, rename_floppy, i_count, j_set;


char *dir;

        if ( argc < 5 ) {
		fprintf( stderr, catgets(Dtb_project_catd, 2, 18, usage) );
                exit(1);
        }
	i_count = 1;
	j_set = 0;
	
	
	while(i_count < argc) {
		arg = argv[i_count][1];
		switch(arg) {
		case 'd' :
			strcpy(rawdev, argv[i_count + 1]);
			argv[i_count][1] = 'D';
			j_set = j_set + 4;
			break;
		case 'm' :
			strcpy(mntpt, argv[i_count + 1]);
			j_set = j_set + 2;
			break;
		case 'p' :
		        if (strcmp(argv[i_count + 1], FORMAT) == 0) {
			    popup_type = Format;
			} else if (strcmp(argv[i_count + 1], UNFORMAT) == 0) {
			    popup_type = Unformatted;
			} else if (strcmp(argv[i_count + 1], UNLABEL) == 0) {
			    popup_type = Unlabeled;
			}
			j_set = j_set + 1;
			break;	
		case '?' :
			break;	
		}
		i_count = i_count + 2;
	}

	if (j_set < 6){
		fprintf( stderr, catgets(Dtb_project_catd, 2, 18, usage) );
		exit(1);
		}


    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /* NULL language_proc installs the default Xt language procedure */
    XtSetLanguageProc((XtAppContext)NULL,
        language_proc, language_proc_client_data);
    
    toplevel = XtAppInitialize(&app, "Sdtformat_floppy",
        optionDescList, XtNumber(optionDescList),
        &argc, argv, fallback_resources,
        init_args, num_init_args);

    /*
     * Get display and verify initialization was successful.
     */
    if (toplevel == NULL)
    {
        fprintf(stderr, "Could not open display.\n");
        exit(1);
    }
    
    /*
     * Open the standard message catalog for the project.
     */
    Dtb_project_catd = catopen(DTB_PROJECT_CATALOG, NL_CAT_LOCALE);
    if (Dtb_project_catd == (nl_catd)-1)
    {
        fprintf(stderr, "WARNING: Could not open message catalog: %s. Messages will be defaults.\n",
            DTB_PROJECT_CATALOG);
    }
    
    /*
     * Save the toplevel widget so it can be fetched later as needed.
     */
    dtb_save_toplevel_widget(toplevel);
    
    /*
     * Save the command used to invoke the application.
     */
    dtb_save_command(argv[0]);
    
    XtGetApplicationResources(toplevel, (XtPointer)&dtb_app_resource_rec,
        resources, XtNumber(resources),
        get_resources_args, num_get_resources_args);
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      A connection to the X server has been established, and all
     *** initialization has been done.
     ***
     ***  Add extra initialization code after this comment.
     ***/
    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /*
     * Initialize all global variables.
     */
    dtbSdtformatFloppyMainwindowInfo_clear(&dtb_sdtformat_floppy_mainwindow);
    
    /*
     * Set up the application's root (primary) window.
     */
    dtb_sdtformat_floppy_mainwindow.mainwindow = toplevel;
    dtb_cvt_image_file_to_pixmap(dtb_sdtformat_floppy_mainwindow.mainwindow,
        "SDtRM.ffp.m", &icon_pixmap);
    XtVaSetValues(dtb_sdtformat_floppy_mainwindow.mainwindow,
        XmNallowShellResize, True,
        XmNtitle, catgets(Dtb_project_catd, 2, 1, "Format Floppy"),
        XmNiconName, catgets(Dtb_project_catd, 2, 2, "Format"),
        XmNiconPixmap, icon_pixmap,
        XmNinitialState, NormalState,
        XmNmwmDecorations, MWM_DECOR_ALL | MWM_DECOR_RESIZEH,
        XmNmwmFunctions, MWM_FUNC_ALL | MWM_FUNC_RESIZE,
        NULL);
    
    dtb_sdtformat_floppy_mainwindow_initialize(&(dtb_sdtformat_floppy_mainwindow), dtb_get_toplevel_widget());
    
    
    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      All initially-mapped widgets have been created, but not
     *** realized. Set resources on widgets, or perform other operations
     *** that must be completed before the toplevel widget is
     *** realized.
     ***/
    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    XtRealizeWidget(toplevel);

    
    /**************************************************************************
     *** DTB_USER_CODE_START
     ***
     ***      All automatic initialization is complete. Add any additional
     *** code that should be executed before the Xt main loop is entered.
     ***/
    
    /*** DTB_USER_CODE_END
     ***
     *** End of user code section
     ***
     **************************************************************************/
    

    /*
     * Enter event loop
     */
    XtAppMainLoop(app);
    return 0;
}


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


