/* XPM */
static char * bilfile_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor6	m white	c yellow",
"o	s iconColor2	m white	c white",
/* pixels */
"    ..................          ",
"    .XXXXXXXXXXXXXXXX..         ",
"    .XXXXXXXXX.XXX.XX.o.        ",
"    .XXXXXXXX.XXXXX.X.oo.       ",
"    .XXXXXXXXX.XXX.XX.ooo.      ",
"    .XXXXXXXX.o.X.o.X.oooo.     ",
"    .XXXXXXXXX.o.o.XX.ooooo.    ",
"    .XXXXXXXXXX.o.XXX........   ",
"    .XXXXXXXXXXX.XXXXXXXXXX..   ",
"    .XXXXXXXXXX.o.XXXXXXXXX..   ",
"    .XX.XXXXXXXX.XXXXXXXXXX..   ",
"    .XXX.XXXXXX.o.XXXXXXXXX..   ",
"    .XX.o.XXXXXX.XXXXXXXXXX..   ",
"    .XXX.o.XXXX.o.XXXXXXXXX..   ",
"    .XX.o.o.XXXX.XXXXXXXXXX..   ",
"    .XXX.o.o.XX.o.XXXXXXXXX..   ",
"    .XX.o.X.o.XX.XXXXXXXXXX..   ",
"    .XXX.XXX.o.XX.XXXXXXXXX..   ",
"    .XX.o.XXX.o.XXXXXXXXXXX..   ",
"    .XXX.XXXXX.o.XXXXXXXXXX..   ",
"    .XX.o.XXXXX.o.XXXXXXXXX..   ",
"    .XXX.XXXXXXX.o.XXXXXXXX..   ",
"    .XX.o.XXXXXXX.o.XXXXXXX..   ",
"    .XXX.XXXXXXXXX.o.XXXXXX..   ",
"    .XX.o.X.X.X.X.o.o.XXXXX..   ",
"    .XXX.o.o.o.o.o.o.o.XXXX..   ",
"    .XX.X.X.X.X.X.X.X.X.XXX..   ",
"    .XXXXXXXXXXXXXXXXXXXXXX..   ",
"    .XXXXXXXXXXXXXXXXXXXXXX..   ",
"    .XXXXXXXXXXXXXXXXXXXXXX..   ",
"    .........................   ",
"     ........................   "};
