/* XPM */
static char * commandwindow_new_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 7 1 0 0",
/* colors */
" 	c #C3C3C3C3C3C3",
".    s iconGray2     m white c #bdbdbdbdbdbd",
"X    s iconGray8     m black c #212121212121",
"o	s iconColor1	m black	c black",
"O	c #8C8C8C8C8C8C",
"+    s iconGray5     m black c #737373737373",
"@	s iconColor2	m white	c white",
/* pixels */
"   .X                                          o",
" OO+XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
" O++X++++++++++OOOOOOOOOOOOOOOOOOOOOOOOOOO++++Oo",
"OoooXooooooooooooooooooooooooooooooooooooooooooo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo                                           Oo",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
" OooooooooooooooooooooooooooooooooooooooooooooOo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Oo",
" Oo                                           Oo",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
" ooooooooooooooooooooooooooooooooooooooooooooooo"};
