/* XPM */
static char * drawarea_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 19 1 0 0",
/* colors */
" 	s iconColor1	m black	c black",
".    s iconGray4     m white c #949494949494",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray1     m white c #dededededede",
"O    s iconGray6     m black c #636363636363",
"+	s iconColor6	m white	c yellow",
"@	c #D9D9D9D9D9D9",
"#	c #B7B7B7B7B7B7",
"$    s iconGray3     m white c #adadadadadad",
"%    s iconGray8     m black c #212121212121",
"&	s iconColor2	m white	c white",
"*	c #BFBF26262626",
"=    s iconGray5     m black c #737373737373",
"-	s iconColor3	m black	c red",
";	c #E5E5B1B12D2D",
":	c #3E3E57578C8C",
"?	c #61618787D9D9",
">	c #C4C4D7D7FFFF",
",	c #8C8C8C8C8C8C",
/* pixels */
"                                          .     ",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXXXXX+@+@+@+@+XXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXXXX+@+@+@+@+#XXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXXX+@+@+@+@+#+XXXXXXXXXXXXXXXXXXo. $#%X",
" XXXXXXXXXX+++++++&+#+#XX#*XXXXXXXXXXXXXXo. $=%X",
" XXXXXXXXXX+++++++&#+#+XX-*XXXXXXXXXXXXXXo. $=%X",
" XXXXXXXXXX+++++++&+#+#X;#-*XXXXXXXXXXXXXo. $=%X",
" XXXXXXX:::::+++++&#+#+X;-#**XXXXXXXXXXXXo. $=%X",
" XXXXXX:::::::++++&+#+#;-#-#*XXXXXXXXXXXXo. $=%X",
" XXXXX::???::::+++&#+#+;#-#-**XXXXXXXXXXXo. $=%X",
" XXXX::>>>??::::++&+#+;#-#-#-**XXXXXXXXXXo. $=%X",
" XXX::?>>>???::::+&#+#;-#-#-#***XXXXXXXXXo. $=%X",
" XXX::?>>>???::::,&+#;-#-#-#-#**XXXXXXXXXo. $=%X",
" XXX::???????::::,&#+;#-#-#-#-#**XXXXXXXXo.    X",
" XXX:::?????:::::,&+;#-#-#-#-#-***XXXXXXXo. OOOX",
" XXX::::???::::::,&#;-#-#-#-#-#-***XXXXXXo. OOOX",
" XXXX:::::::::::,,&;-#-#-#-#-#-#***XXXXXXo. OOOX",
" XXXXX:::::::::,,+&;#-#-#-#-#-#-#*XXXXXXXo. OOOX",
" XXXXXX:::::::,,++&,,,,XXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXX:::::,,+++&+#+#XXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXX,,,++++&#+#+XXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXX+++++++&+#+XXXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXX++++++++#+XXXXXXXXXXXXXXXXXXXXo. OOOX",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo. OOOX",
" ooooooooooooooooooooooooooooooooooooooooo, OOOX",
".........................................,..XXXX",
"                                          ......",
" OOOOOOOOOOXXXXXXXXXXXXXXXXXXXX%OOOOOOOOOOX.....",
" OOOOOOOOOOX...................%OOOOOOOOOOX.....",
" OOOOOOOOOO%%%%%%%%%%%%%%%%%%%%%OOOOOOOOOOX.....",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....."};
