/* XPM */
static char * fontbox_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 6 1 0 0",
/* colors */
" 	c #E5E5E5E5E5E5",
".	c #8C8C8C8C8C8C",
"X	s iconColor1	m black	c black",
"o	c #7E7E7E7E7E7E",
"O	c #4C4C4C4C4C4C",
"+	c #B7B7B7B7B7B7",
/* pixels */
"      .                                        X",
" oooooXooooooooooooooooooooooooooooooooooooooooO",
" oooooXooooooooooooooooooooooooooooooooooooooooO",
" oooooXooooooooooooooooooooooooooooooooooooooooO",
" oooooXooooooooooooooooooooooooooooooooooooooooO",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" oooooooooXXXXooooooXXXXXXooooooXXXXXXXooooooooO",
" ooooooooXXXXXXoooooXXXXXXXooooXXXXXXXXXoooooooO",
" oooooooXXooooXXooooXXoooXXooooXXXooooXXoooooooO",
" oooooooXXooooXXooooXXoooXXooooXXoooooXXoooooooO",
" oooooooXXooooXXooooXXoooXXooooXXooooooooooooooO",
" oooooooXXooooXXooooXXoooXXooooXXooooooooooooooO",
" oooooooXXooooXXooooXXXXXXoooooXXooooooooooooooO",
" oooooooXXooooXXooooXXXXXXoooooXXooooooooooooooO",
" oooooooXXXXXXXXooooXXoooXXooooXXooooooooooooooO",
" oooooooXXXXXXXXooooXXoooXXooooXXooooooooooooooO",
" oooooooXXooooXXooooXXoooXXooooXXoooooXXoooooooO",
" oooooooXXooooXXooooXXoooXXooooXXXooooXXoooooooO",
" oooooooXXooooXXooooXXXXXXXooooXXXXXXXXXoooooooO",
" oooooooXXooooXXooooXXXXXXooooooXXXXXXXooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooo++++++++++ooooo++++++++++ooooo++++++++++oooO",
" ooo+ooooooooXooooo+ooooooooXooooo+ooooooooXoooO",
" ooo+ooooooooXooooo+ooooooooXooooo+ooooooooXoooO",
" ooo+XXXXXXXXXooooo+XXXXXXXXXooooo+XXXXXXXXXoooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO"};
