/* XPM */
static char * printbox_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 10 1 0 0",
/* colors */
" 	c #CCCCCCCCCCCC",
".	s iconColor1	m black	c black",
"X	c #7E7E7E7E7E7E",
"o	c #4C4C4C4C4C4C",
"O	c #C3C3C3C3C3C3",
"+	s iconColor2	m white	c white",
"@	c #B7B7B7B7B7B7",
"#	c #E3E3E5E5B7B7",
"$	c #E5E5E5E5E5E5",
"%	c #8C8C8C8C8C8C",
/* pixels */
"                                               .",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXOOOOOOOOOOOO.XXXXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXO++++++++++O+.XXXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXO+X+XX+XX+XO++.XXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXO++++++++++O+++.XXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXO+XXX++XX+X@@@@.XXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXO+++++++++++OOO.XXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXX..O+X+XX++X+XX+X+...XXXXXXXXXXXXXo",
" XXXXXXXXXXXX.#+O++++++++++++++.##.XXXXXXXXXXXXo",
" XXXXXXXXXXX.#+.O$$$$$$$$$$$$$$..##.XXXXXXXXXXXo",
" XXXXXXXXXX.#+#+#+#+#+#+#+#+#+#+#+#+.XXXXXXXXXXo",
" XXXXXXXXX.#+#+#+#+#+#+#+#+#+#+#+#+#+.XXXXXXXXXo",
" XXXXXXXX.++++++++++++++++++++++++++++.XXXXXXXXo",
" XXXXXXXX. # # # # # # # # # # # # # #.XXXXXXXXo",
" XXXXXXXX.# # # # # # # # # # # # # # .XXXXXXXXo",
" XXXXXXXX. # # # # # # # # # # # # # #.XXXXXXXXo",
" XXXXXXXXX.%@%@%@%@%@%@%@%@%@%@%@%@%@.XXXXXXXXXo",
" XXXXXXXXX.#%#%#%#%#%#%#%#%#%#%#%#%#%.XXXXXXXXXo",
" XXXXXXXXX.%#%....................#%#.XXXXXXXXXo",
" XXXXXXXX.++++..XXXXXXXXXXXXXXXX..++++.XXXXXXXXo",
" XXXXXXXX.#####X@X@X@X@X@X@X@X@X@#####.XXXXXXXXo",
" XXXXXXXX.####.@X@X@X@X@X@X@X@X@X.####.XXXXXXXXo",
" XXXXXXXX......XXXXXXXXXXXXXXXXXX......XXXXXXXXo",
" XXXXXXXXXXXXX....................XXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%o",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" ..............................................o"};
