/* XPM */
static char * selection_box_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 10 1 0 0",
/* colors */
" 	c #C3C3C3C3C3C3",
".    s iconGray8     m black c #212121212121",
"X	s iconColor1	m black	c black",
"o	c #8C8C8C8C8C8C",
"O	c #CCCCCCCCCCCC",
"+	c #B7B7B7B7B7B7",
"@    s iconGray4     m white c #949494949494",
"#    s iconGray2     m white c #bdbdbdbdbdbd",
"$    s iconGray3     m white c #adadadadadad",
"%	c #7E7E7E7E7E7E",
/* pixels */
"    .                                          X",
" ooo.ooooooooooooooooooooooooooooooooooooooooooX",
" oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOoX",
" oX++++++++++++++++++++++++++++++++++++++++++OoX",
" oX+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O+OoX",
" oX+XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OoX",
" oX++++++++++++++++++++++++++++++++++++++++++OoX",
" oX+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+OoX",
" oX+X######################################.+OoX",
" oX+X######################################.+OoX",
" oX+X######################################.+OoX",
" oX+XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#.+OoX",
" o..........................................$#oX",
" oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoX",
" ooooooooooooooooooooooooooooooooooooooooooooooX",
" oOOOOOOOOOOOOXoooOOOOOOOOOOOOXoooOOOOOOOOOOOXoX",
" oO%%%%%%%%%%%XoooO%%%%%%%%%%%XoooO%%%%%%%%%%XoX",
" oO%%%%%%%%%%%XoooO%%%%%%%%%%%XoooO%%%%%%%%%%XoX",
" oOXXXXXXXXXXXXoooOXXXXXXXXXXXXoooOXXXXXXXXXXXoX",
" ooooooooooooooooooooooooooooooooooooooooooooooX",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
