/* XPM */
static char * termpane_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"28 20 16 1 0 0",
/* colors */
"     s iconGray3     m white c #adadadadadad",
".	s iconColor1	m black	c black",
"X	c #F4F4F4F4F4F4",
"o    s iconGray1     m white c #dededededede",
"O	c #CCCCCCCCCCCC",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#	c #E5E5E5E5E5E5",
"$	s iconColor2	m white	c white",
"%	c #959595959595",
"&	c #D9D9D9D9D9D9",
"*	c #F9F9F9F9F9F9",
"=	c #C7C7C7C7C7C7",
"-	c #999999999999",
";	c #C3C3C3C3C3C3",
":	c #E3E3E3E3E3E3",
/* pixels */
"                            ",
"          .........         ",
"         .XXXXXXXXX.        ",
"        .ooooooooooo.       ",
"        .O+++++++++@.       ",
"        .O.........@.       ",
"        .O.o..ooo..@.       ",
"        .O.........@.       ",
"        .O.#.#.##..@.       ",
"        .O.........@.       ",
"        .O.........@.       ",
"        .O$$$$$$$$$@.       ",
"         ...........        ",
"          .%%%%%%%.         ",
"       ...............      ",
"      .X#&XX*&*&&&*=&$.     ",
"     .$$---$$$-XXX&&**$.    ",
"    .$=***&X****XX;;**:$.   ",
"    .....................   ",
"                            "};
