$ $XConsortium: template.msg /main/cde1_maint/2 1995/09/06 02:05:25 lehors $
$
$	template.msg
$
$	message catalog for template example
$

$ Module: template.c
$

$set 1
$ General application messages
1 Template
2 Template Open
3 Template Save As
4 Template Help
5  - 
6 (untitled)
7 ttdt_open failed
8 ttmedia_ptype_declare failed
9 ttdt_join_session failed
10 template: can't open %s\n

$set 2
$ These messages are used in the main window of the template example.
1 File
2 Open...
3 Save As...
4 Print
5 Clear
6 Exit
7 Help
8 Overview...
9 New...
