.\"---
.\"     (c) Copyright 1993, 1994 Hewlett-Packard Company
.\"     (c) Copyright 1993, 1994 International Business Machines Corp.
.\"     (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\"     (c) Copyright 1993, 1994 Novell, Inc.
.\"---
.TH dtchooser 1 "05 Dec 1994"
.BH "05 Dec 1994""
.SH NAME
dtchooser - CDE dtlogin chooser screen display utility
.SH SYNOPSIS
dtchooser
.P
NOTE: The Common Desktop Environment (CDE)
.B dtchooser
utility is used by
.B dtlogin(1)
to display the chooser screen when an
.B XDMCP indirect
request is received. It is not intended to be run directly from
the command line.
.SH DESCRIPTION
The CDE dtchooser utility is used by
.B dtlogin
to display the host chooser screen on a display when an
.B XDMCP indirect
request is received. The user can select a host from the
list presented, and
.B dtlogin
on that host will display a login screen on the display. There will be one
.B dtchooser
process per display on which a chooser screen is visible.
.P
All customization of the chooser screen is done via
.B dtlogin
configuration files. Refer to the
.B dtlogin(1)
man page for information regarding chooser screen customization.
