.\"---
.\"     (c) Copyright 1993, 1994 Hewlett-Packard Company
.\"     (c) Copyright 1993, 1994 International Business Machines Corp.
.\"     (c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\"     (c) Copyright 1993, 1994 Novell, Inc.
.\"---
.TH dtgreet 1 "05 Dec 1994"
.BH "05 Dec 1994""
.SH NAME
dtgreet - CDE dtlogin login screen display utility
.SH SYNOPSIS
dtgreet
.P
NOTE: The Common Desktop Environment (CDE)
.B dtgreet
utility is used by
.B dtlogin(1)
to display the login screen. It is not intended to be run directly from
the command line.
.SH DESCRIPTION
The CDE dtgreet utility is used by
.B dtlogin
to display the login screen on a display. There will be one
.B dtgreet
process per display on which a login screen is visible.
.P
All customization of the login screen is done via
.B dtlogin
configuration files. Refer to the
.B dtlogin(1)
man page for information regarding login screen customization.
