.\"(c) Copyright 1993, 1994 Hewlett-Packard Company
.\"(c) Copyright 1993, 1994 International Business Machines Corp.
.\"(c) Copyright 1993, 1994 Sun Microsystems, Inc.
.\"(c) Copyright 1993, 1994 Novell, Inc.
.TH DTMAILPR 1 "" "" "" ""
.ds ]W CDE 1.0 (8/94)
.na
.SH NAME
\fBdtmailpr \(em electronic mail message print filter\fP
.sp 1
.SH SYNOPSIS
.B dtmailpr
[
.B \-f
.I filename
]
[
.B \-p
]
.sp 1
.SH DESCRIPTION
The
.B dtmailpr
program reads a
.I filename
(which contains one or more mail messages from
.I mailx
or
.I dtmail
), and sends the message to standard out with headers abbreviated
and attachments removed.  If no filename argument is provided
.B dtmailpr
reads from standard in.
.LP
.B dtmailpr
adds an attachment summary in place of the actual attachments.
.sp 1
.SH OPTIONS
.br
.TP
.BI \-p
Insert page breaks between each mail message so that they print one 
per page.
.TP
.BI \-f " filename" 
Read from the specified file instead of standard in.

