.TH dtqueueinfo 1X "14 March 1994"
.BH "14 March -1994"
.SH NAME
dtqueueinfo - prints status of print queues
.SH SYNOPSIS
.B dtqueueinfo 
[
.I printer ...
]
.if t .ti +.5i
.LP
.nf
.SH DESCRIPTION
dtqueueinfo displays the status of the print queues and print jobs in
a graphical interface. Additional information about print queues or print
jobs can be retrieved within the interface. dtqueueinfo allows individual
print jobs to be deleted.  This program is basically an interface on
top of the lpstat command.

If no printers are given, dtqueueinfo will display all of the print
queues.

.SH OPTION
.TP
.B "printer"
Only display information for the specified print queue.
If the environment variable LPDEST is set, the printer option
will override the value in LPDEST.
.SH EXAMPLES 
.TP
View the status of the print queues:

.B dtqueueinfo
.TP
View the status of the print queue called lp0:

.B dtqueueinfo lp0
.TP
View the status of print queues called lp0 and lp1:

.B dtqueueinfo lp0 lp1
.SH ENVIRONMENT
.LP
.\"Introductionory paragraph.
.TP 15
.SM LPDEST
The environment variable LPDEST determines which print queue to display. 
If this value is set
and dtqueueinfo is started with no options, only the print queue in
LPDEST will be shown.  This value can be overridden by specifying the
printer.


